# Run Go tests, lint, etc.
steps:

- id: go_test
  # https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/go
  name: "golang"
  entrypoint: "go"
  env: ["GO111MODULE=on"]
  args: ["test", "./..."]

# TODO: Add go linter, any other useful Go tools.
- id: go_linter
  name: "golangci/golangci-lint"
  args: ["golangci-lint","run"]
