# Run Go tests, lint, etc.
steps:

- id: go_build
  name: "golang"
  entrypoint: "go"
  #  env: ["GO111MODULE=on"]
  args: ["build", "./..."]

- id: go_test
  name: "golang"
  entrypoint: "go"
  #env: ["GO111MODULE=on"]
  args: ["test", "./..."]

# TODO: Add go linter, any other useful Go tools.
- id: go_linter
  name: "golangci/golangci-lint"
  args: ["golangci-lint", "run", " --enable-all"]
