# Run Go tests, lint, etc.
steps:

- id: go_build
  name: "golang"
  entrypoint: "go"
  #  env: ["GO111MODULE=on"]
  args: ["build", "./..."]

- id: go_test
  name: "golang"
  entrypoint: "go"
  #env: ["GO111MODULE=on"]
  args: ["test", "./..."]

- id: go_vet
  name: "golang"
  entrypoint: "go"
  #env: ["GO111MODULE=on"]
  args: ["test", "./..."]

- id: check_go_fmt
  name: "golang"
  entrypoint: "go"
  #env: ["GO111MODULE=on"]
  args: ["test", "./..."]

- id: go_linter
  name: "golangci/golangci-lint"
  args: ["golangci-lint", " --enable-all", "run" ]


# TODO: Add any other useful Go tools.

