# NOTE: Keep all lower case.

replace_headers = {
    "active cases": "active_cases", # Get rid of spaces
    "active cases and recoveries": "cases", # See Connecticut, USA
    "cumulative cases (revised)": "active_cases", # See Contra Costa County, CA
    "tested or c.d.": "active_cases", #See China
    "active cases & recoveries": "cases",
    "kdhe reported cases": "active_cases", # See Kansas, USA
    "confirmed cases": "active_cases" # See Indiana, USA
}


places = [
   {
      "url":"https://en.wikipedia.org/w/index.php?title=Template:COVID-19_pandemic_data/United_States_medical_cases_chart\n",
      "wikidataId":"Q30"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Alabama_medical_cases_chart\n",
      "wikidataId":"Q173"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Alaska_medical_cases_chart\n",
      "wikidataId":"Q797"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Arizona_medical_cases_chart\n",
      "wikidataId":"Q816"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Arkansas_medical_cases_chart\n",
      "wikidataId":"Q1612"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/California_medical_cases_chart\n",
      "wikidataId":"Q99"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/California/Alameda_County_medical_cases_chart\n",
      "wikidataId":"Q107146"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/California/Contra_Costa_County_medical_cases_chart\n",
      "wikidataId":"Q108058"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/California/Los_Angeles_County_medical_cases_chart\n",
      "wikidataId":"Q104994"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/California/Marin_County_medical_cases_chart\n",
      "wikidataId":"Q108117"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/California/Napa_County_medical_cases_chart\n",
      "wikidataId":"Q108137"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/California/Orange_County_medical_cases_chart\n",
      "wikidataId":"Q110472"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/California/San_Diego_County_medical_cases_chart\n",
      "wikidataId":"Q108143"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/California/San_Francisco_County_medical_cases_chart\n",
      "wikidataId":"Q62"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/California/San_Mateo_County_medical_cases_chart\n",
      "wikidataId":"Q108101"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/California/Santa_Barbara_County_medical_cases_chart\n",
      "wikidataId":"Q108106"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/California/Santa_Clara_County_medical_cases_chart\n",
      "wikidataId":"Q110739"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/California/Solano_County_medical_cases_chart\n",
      "wikidataId":"Q108083"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/California/Sonoma_County_medical_cases_chart\n",
      "wikidataId":"Q108067"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/California/Ventura_County_medical_cases_chart\n",
      "wikidataId":"Q108127"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Colorado_medical_cases_chart\n",
      "wikidataId":"Q1261"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Connecticut_medical_cases_chart\n",
      "wikidataId":"Q779"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Delaware_medical_cases_chart\n",
      "wikidataId":"Q1393"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Washington,_D.C._medical_cases_chart\n",
      "wikidataId":"Q61"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Florida_medical_cases_chart\n",
      "wikidataId":"Q812"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Georgia_medical_cases_chart\n",
      "wikidataId":"Q4962"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Hawaii_medical_cases_chart\n",
      "wikidataId":"Q782"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Idaho_medical_cases_chart\n",
      "wikidataId":"Q1221"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Illinois_medical_cases_chart\n",
      "wikidataId":"Q1204"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Indiana_medical_cases_chart\n",
      "wikidataId":"Q1415"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Iowa_medical_cases_chart\n",
      "wikidataId":"Q1546"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Kansas_medical_cases_chart\n",
      "wikidataId":"Q1558"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Kentucky_medical_cases_chart\n",
      "wikidataId":"Q1603"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Louisiana_medical_cases_chart\n",
      "wikidataId":"Q1588"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Louisiana/Orleans_Parish_medical_cases_chart\n",
      "wikidataId":"Q34404"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Maine_medical_cases_chart\n",
      "wikidataId":"Q724"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Maryland_medical_cases_chart\n",
      "wikidataId":"Q1391"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Massachusetts_medical_cases_chart\n",
      "wikidataId":"Q771"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Massachusetts/Boston_medical_cases_chart\n",
      "wikidataId":"Q100"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Michigan_medical_cases_chart\n",
      "wikidataId":"Q1166"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Minnesota_medical_cases_chart\n",
      "wikidataId":"Q1527"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Mississippi_medical_cases_chart\n",
      "wikidataId":"Q1494"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Missouri_medical_cases_chart\n",
      "wikidataId":"Q1581"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Montana_medical_cases_chart\n",
      "wikidataId":"Q1212"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Nebraska_medical_cases_chart\n",
      "wikidataId":"Q1553"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Nebraska/Douglas_County_medical_cases_chart\n",
      "wikidataId":"Q226255"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Nevada_medical_cases_chart\n",
      "wikidataId":"Q1227"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/New_Hampshire_medical_cases_chart\n",
      "wikidataId":"Q759"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/New_Jersey_medical_cases_chart\n",
      "wikidataId":"Q1408"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/New_Mexico_medical_cases_chart\n",
      "wikidataId":"Q1522"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/New_York_State_medical_cases_chart\n",
      "wikidataId":"Q1384"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/New_York_State/New_York_City_medical_cases_chart\n",
      "wikidataId":"Q60"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/North_Carolina_medical_cases_chart\n",
      "wikidataId":"Q1454"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/North_Dakota_medical_cases_chart\n",
      "wikidataId":"Q1207"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Ohio_medical_cases_chart\n",
      "wikidataId":"Q1397"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Ohio/Franklin_County_medical_cases_chart\n",
      "wikidataId":"Q224042"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Oklahoma_medical_cases_chart\n",
      "wikidataId":"Q1649"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Oregon_medical_cases_chart\n",
      "wikidataId":"Q824"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Pennsylvania_medical_cases_chart\n",
      "wikidataId":"Q1400"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Rhode_Island_medical_cases_chart\n",
      "wikidataId":"Q1387"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/South_Carolina_medical_cases_chart\n",
      "wikidataId":"Q1456"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/South_Dakota_medical_cases_chart\n",
      "wikidataId":"Q1211"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Tennessee_medical_cases_chart\n",
      "wikidataId":"Q1509"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Texas_medical_cases_chart\n",
      "wikidataId":"Q1439"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Utah_medical_cases_chart\n",
      "wikidataId":"Q829"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Vermont_medical_cases_chart\n",
      "wikidataId":"Q16551"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Virginia_medical_cases_chart\n",
      "wikidataId":"Q1370"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Washington_State_medical_cases_chart\n",
      "wikidataId":"Q7972225"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/West_Virginia_medical_cases_chart\n",
      "wikidataId":"Q1371"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Wisconsin_medical_cases_chart\n",
      "wikidataId":"Q1537"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Wyoming_medical_cases_chart\n",
      "wikidataId":"Q1214"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Guam_medical_cases_chart\n",
      "wikidataId":"Q16635"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/Puerto_Rico_medical_cases_chart\n",
      "wikidataId":"Q1183"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_States/U.S._Virgin_Islands_medical_cases_chart\n",
      "wikidataId":"Q11703"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Algeria_medical_cases_chart\n",
      "wikidataId":"Q262"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Angola_medical_cases_chart\n",
      "wikidataId":"Q916"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Burkina_Faso_medical_cases_chart\n",
      "wikidataId":"Q965"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Burundi_medical_cases_chart\n",
      "wikidataId":"Q967"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Cameroon_medical_cases_chart\n",
      "wikidataId":"Q1009"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Egypt_medical_cases_chart\n",
      "wikidataId":"Q79"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Eswatini_medical_cases_chart\n",
      "wikidataId":"Q1050"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Ethiopia_medical_cases_chart\n",
      "wikidataId":"Q115"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Ghana_medical_cases_chart\n",
      "wikidataId":"Q117"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Ivory_Coast_medical_cases_chart\n",
      "wikidataId":"Q1008"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Kenya_medical_cases_chart\n",
      "wikidataId":"Q114"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Libya_medical_cases_chart\n",
      "wikidataId":"Q1016"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Malawi_medical_cases_chart\n",
      "wikidataId":"Q1020"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Mali_medical_cases_chart\n",
      "wikidataId":"Q912"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Mauritania_medical_cases_chart\n",
      "wikidataId":"Q1025"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Mauritius_medical_cases_chart\n",
      "wikidataId":"Q1027"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Morocco_medical_cases_chart\n",
      "wikidataId":"Q1028"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Nigeria_medical_cases_chart\n",
      "wikidataId":"Q1033"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Senegal_medical_cases_chart\n",
      "wikidataId":"Q1041"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Sierra_Leone_medical_cases_chart\n",
      "wikidataId":"Q1044"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/South_Africa_medical_cases_chart\n",
      "wikidataId":"Q258"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/South_Sudan_medical_cases_chart\n",
      "wikidataId":"Q958"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Sudan_medical_cases_chart\n",
      "wikidataId":"Q1049"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Tanzania_medical_cases_chart\n",
      "wikidataId":"Q924"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Togo_medical_cases_chart\n",
      "wikidataId":"Q945"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Tunisia_medical_cases_chart\n",
      "wikidataId":"Q948"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Argentina_medical_cases_chart\n",
      "wikidataId":"Q414"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Bolivia_medical_cases_chart\n",
      "wikidataId":"Q750"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Brazil_medical_cases_chart\n",
      "wikidataId":"Q155"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Canada_medical_cases_chart\n",
      "wikidataId":"Q16"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Chile_medical_cases_chart\n",
      "wikidataId":"Q298"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Colombia_medical_cases_chart\n",
      "wikidataId":"Q739"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Costa_Rica_medical_cases_chart\n",
      "wikidataId":"Q800"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Cuba_medical_cases_chart\n",
      "wikidataId":"Q241"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Dominican_Republic_medical_cases_chart\n",
      "wikidataId":"Q786"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Ecuador_medical_cases_chart\n",
      "wikidataId":"Q736"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/El_Salvador_medical_cases_chart\n",
      "wikidataId":"Q792"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Guatemala_medical_cases_chart\n",
      "wikidataId":"Q774"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Haiti_medical_cases_chart\n",
      "wikidataId":"Q790"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Honduras_medical_cases_chart\n",
      "wikidataId":"Q783"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Mexico_medical_cases_chart\n",
      "wikidataId":"Q96"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Nicaragua_medical_cases_chart\n",
      "wikidataId":"Q811"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Panama_medical_cases_chart\n",
      "wikidataId":"Q804"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Paraguay_medical_cases_chart\n",
      "wikidataId":"Q733"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Peru_medical_cases_chart\n",
      "wikidataId":"Q419"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Uruguay_medical_cases_chart\n",
      "wikidataId":"Q77"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Venezuela_medical_cases_chart\n",
      "wikidataId":"Q717"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Afghanistan_medical_cases_chart\n",
      "wikidataId":"Q889"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Armenia_medical_cases_chart\n",
      "wikidataId":"Q399"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Azerbaijan_medical_cases_chart\n",
      "wikidataId":"Q227"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Bahrain_medical_cases_chart\n",
      "wikidataId":"Q398"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Bangladesh_medical_cases_chart\n",
      "wikidataId":"Q902"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Bhutan_medical_cases_chart\n",
      "wikidataId":"Q917"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Brunei_medical_cases_chart\n",
      "wikidataId":"Q921"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Cambodia_medical_cases_chart\n",
      "wikidataId":"Q424"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Mainland_China_medical_cases_chart\n",
      "wikidataId":"Q19188"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Georgia_medical_cases_chart\n",
      "wikidataId":"Q4962"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Hong_Kong_medical_cases_chart\n",
      "wikidataId":"Q8646"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India_medical_cases_chart\n",
      "wikidataId":"Q668"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Indonesia_medical_cases_chart\n",
      "wikidataId":"Q252"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Iran_medical_cases_chart\n",
      "wikidataId":"Q794"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Iraq_medical_cases_chart\n",
      "wikidataId":"Q796"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Israel_medical_cases_chart\n",
      "wikidataId":"Q801"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Japan_medical_cases_chart\n",
      "wikidataId":"Q17"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Jordan_medical_cases_chart\n",
      "wikidataId":"Q810"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Kazakhstan_medical_cases_chart\n",
      "wikidataId":"Q232"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/South_Korea_medical_cases_chart\n",
      "wikidataId":"Q884"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Kuwait_medical_cases_chart\n",
      "wikidataId":"Q817"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Kyrgyzstan_medical_cases_chart\n",
      "wikidataId":"Q813"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Lebanon_medical_cases_chart\n",
      "wikidataId":"Q822"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Malaysia_medical_cases_chart\n",
      "wikidataId":"Q833"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Myanmar_medical_cases_chart\n",
      "wikidataId":"Q836"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Nepal_medical_cases_chart\n",
      "wikidataId":"Q837"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Oman_medical_cases_chart\n",
      "wikidataId":"Q842"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Pakistan_medical_cases_chart\n",
      "wikidataId":"Q843"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Palestine_medical_cases_chart\n",
      "wikidataId":"Q1176995"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Philippines_medical_cases_chart\n",
      "wikidataId":"Q928"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Qatar_medical_cases_chart\n",
      "wikidataId":"Q846"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Russia_medical_cases_chart\n",
      "wikidataId":"Q159"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Saudi_Arabia_medical_cases_chart\n",
      "wikidataId":"Q851"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Singapore_medical_cases_chart\n",
      "wikidataId":"Q334"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Sri_Lanka_medical_cases_chart\n",
      "wikidataId":"Q854"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Syria_medical_cases_chart\n",
      "wikidataId":"Q858"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Taiwan_medical_cases_chart\n",
      "wikidataId":"Q865"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Tajikistan_medical_cases_chart\n",
      "wikidataId":"Q863"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Thailand_medical_cases_chart\n",
      "wikidataId":"Q869"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Turkey_medical_cases_chart\n",
      "wikidataId":"Q43"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_Arab_Emirates_medical_cases_chart\n",
      "wikidataId":"Q878"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Uzbekistan_medical_cases_chart\n",
      "wikidataId":"Q265"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Vietnam_medical_cases_chart\n",
      "wikidataId":"Q881"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Yemen_medical_cases_chart\n",
      "wikidataId":"Q805"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Albania_medical_cases_chart\n",
      "wikidataId":"Q222"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Austria_medical_cases_chart\n",
      "wikidataId":"Q40"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Belarus_medical_cases_chart\n",
      "wikidataId":"Q184"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Belgium_medical_cases_chart\n",
      "wikidataId":"Q31"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Bosnia_and_Herzegovina_medical_cases_chart\n",
      "wikidataId":"Q225"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Bulgaria_medical_cases_chart\n",
      "wikidataId":"Q219"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Croatia_medical_cases_chart\n",
      "wikidataId":"Q224"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Cyprus_medical_cases_chart\n",
      "wikidataId":"Q229"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Czech_Republic_medical_cases_chart\n",
      "wikidataId":"Q213"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Denmark_medical_cases_chart\n",
      "wikidataId":"Q35"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Estonia_medical_cases_chart\n",
      "wikidataId":"Q191"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Faroe_Islands_medical_cases_chart\n",
      "wikidataId":"Q4628"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Finland_medical_cases_chart\n",
      "wikidataId":"Q33"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/France_medical_cases_chart\n",
      "wikidataId":"Q142"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Germany_medical_cases_chart\n",
      "wikidataId":"Q183"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Greece_medical_cases_chart\n",
      "wikidataId":"Q41"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Hungary_medical_cases_chart\n",
      "wikidataId":"Q28"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Iceland_medical_cases_chart\n",
      "wikidataId":"Q189"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Republic_of_Ireland_medical_cases_chart\n",
      "wikidataId":"Q27"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Italy_medical_cases_chart\n",
      "wikidataId":"Q38"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Kosovo_medical_cases_chart\n",
      "wikidataId":"Q1246"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Latvia_medical_cases_chart\n",
      "wikidataId":"Q211"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Lithuania_medical_cases_chart\n",
      "wikidataId":"Q37"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Luxembourg_medical_cases_chart\n",
      "wikidataId":"Q32"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Malta_medical_cases_chart\n",
      "wikidataId":"Q233"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Moldova_medical_cases_chart\n",
      "wikidataId":"Q217"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Monaco_medical_cases_chart\n",
      "wikidataId":"Q235"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Montenegro_medical_cases_chart\n",
      "wikidataId":"Q236"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Netherlands_medical_cases_chart\n",
      "wikidataId":"Q55"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/North_Macedonia_medical_cases_chart\n",
      "wikidataId":"Q221"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Norway_medical_cases_chart\n",
      "wikidataId":"Q20"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Poland_medical_cases_chart\n",
      "wikidataId":"Q36"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Portugal_medical_cases_chart\n",
      "wikidataId":"Q45"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Romania_medical_cases_chart\n",
      "wikidataId":"Q218"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Russia_medical_cases_chart\n",
      "wikidataId":"Q159"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/San_Marino_medical_cases_chart\n",
      "wikidataId":"Q238"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Serbia_medical_cases_chart\n",
      "wikidataId":"Q403"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Slovakia_medical_cases_chart\n",
      "wikidataId":"Q214"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Slovenia_medical_cases_chart\n",
      "wikidataId":"Q215"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Spain_medical_cases_chart\n",
      "wikidataId":"Q29"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Asturias_medical_cases_chart\n",
      "wikidataId":"Q3934"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Community_of_Madrid_medical_cases_chart\n",
      "wikidataId":"Q5756"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Sweden_medical_cases_chart\n",
      "wikidataId":"Q34"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Switzerland_medical_cases_chart\n",
      "wikidataId":"Q39"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Turkey_medical_cases_chart\n",
      "wikidataId":"Q43"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Ukraine_medical_cases_chart\n",
      "wikidataId":"Q212"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Donetsk_People%27s_Republic_medical_cases_chart\n",
      "wikidataId":"Q16150196"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Luhansk_People%27s_Republic_medical_cases_chart\n",
      "wikidataId":"Q16746854"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/United_Kingdom_medical_cases_chart\n",
      "wikidataId":"Q145"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Vatican_City_medical_cases_chart\n",
      "wikidataId":"Q237"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Australia_medical_cases_chart\n",
      "wikidataId":"Q408"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Fiji_medical_cases_chart\n",
      "wikidataId":"Q712"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/French_Polynesia_medical_cases_chart\n",
      "wikidataId":"Q30971"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/New_Caledonia_medical_cases_chart\n",
      "wikidataId":"Q33788"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/New_Zealand_medical_cases_chart\n",
      "wikidataId":"Q664"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Papua_New_Guinea_medical_cases_chart\n",
      "wikidataId":"Q691"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Andhra_Pradesh_medical_cases_chart\n",
      "wikidataId":"Q1159"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Assam_medical_cases_chart\n",
      "wikidataId":"Q1164"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Bihar_medical_cases_chart\n",
      "wikidataId":"Q1165"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Delhi_medical_cases_chart\n",
      "wikidataId":"Q1353"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Goa_medical_cases_chart\n",
      "wikidataId":"Q1171"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Gujarat_medical_cases_chart\n",
      "wikidataId":"Q1061"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Haryana_medical_cases_chart\n",
      "wikidataId":"Q1174"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Jammu_and_Kashmir_medical_cases_chart\n",
      "wikidataId":"Q2746364"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Jharkhand_medical_cases_chart\n",
      "wikidataId":"Q1184"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Karnataka_medical_cases_chart\n",
      "wikidataId":"Q1185"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Kerala_medical_cases_chart\n",
      "wikidataId":"Q1186"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Madhya_Pradesh_medical_cases_chart\n",
      "wikidataId":"Q1188"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Maharashtra/Mumbai_medical_cases_chart\n",
      "wikidataId":"Q1156"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Maharashtra_medical_cases_chart\n",
      "wikidataId":"Q1191"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Nagaland_medical_cases_chart\n",
      "wikidataId":"Q1599"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Odisha_medical_cases_chart\n",
      "wikidataId":"Q22048"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Puducherry_medical_cases_chart\n",
      "wikidataId":"Q66743"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Punjab_medical_cases_chart\n",
      "wikidataId":"Q169132"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Rajasthan_medical_cases_chart\n",
      "wikidataId":"Q1437"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Sikkim_medical_cases_chart\n",
      "wikidataId":"Q1505"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Tamil_Nadu_medical_cases_chart\n",
      "wikidataId":"Q1445"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Telangana_medical_cases_chart\n",
      "wikidataId":"Q677037"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Uttar_Pradesh_medical_cases_chart\n",
      "wikidataId":"Q1498"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/Uttarakhand_medical_cases_chart\n",
      "wikidataId":"Q1499"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India/West_Bengal_medical_cases_chart\n",
      "wikidataId":"Q1356"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/India_medical_cases_chart\n",
      "wikidataId":"Q668"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Greenland_medical_cases_chart\n",
      "wikidataId":"Q223"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Asturias_medical_cases_chart\n",
      "wikidataId":"Q3934"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Canada/British_Columbia_medical_cases_chart\n",
      "wikidataId":"Q1974"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Alberta_medical_cases_chart\n",
      "wikidataId":"Q1951"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Canada/Manitoba_medical_cases_chart\n",
      "wikidataId":"Q1948"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/New_Brunswick_medical_cases_chart\n",
      "wikidataId":"Q1965"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Canada/Nova_Scotia_medical_cases_chart\n",
      "wikidataId":"Q1952"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Canada/Ontario_medical_cases_chart\n",
      "wikidataId":"Q1904"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Canada/Quebec_medical_cases_chart\n",
      "wikidataId":"Q176"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Isle_of_Man_medical_cases_chart\n",
      "wikidataId":"Q9676"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Bailiwick_of_Guernsey_medical_cases_chart\n",
      "wikidataId":"Q25230"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Bailiwick_of_Jersey_medical_cases_chart\n",
      "wikidataId":"Q785"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Northern_Ireland_medical_cases_chart\n",
      "wikidataId":"Q26"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Scotland_medical_cases_chart\n",
      "wikidataId":"Q22"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Wales_medical_cases_chart\n",
      "wikidataId":"Q25"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/French_Saint_Martin_medical_cases_chart\n",
      "wikidataId":"Q126125"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Turks_and_Caicos_Islands_medical_cases_chart\n",
      "wikidataId":"Q18221"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Trinidad_and_Tobago_medical_cases_chart\n",
      "wikidataId":"Q754"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/South_Africa,_Western_Cape_medical_cases_chart\n",
      "wikidataId":"Q127167"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Sint_Maarten_medical_cases_chart\n",
      "wikidataId":"Q26273"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Sint_Eustatius_medical_cases_chart\n",
      "wikidataId":"Q26180"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Seychelles_medical_cases_chart\n",
      "wikidataId":"Q1042"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Saint_Vincent_and_Grenadines_medical_cases_chart\n",
      "wikidataId":"Q757"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Saint_Barth%C3%A9lemy_medical_cases_chart\n",
      "wikidataId":"Q25362"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Saba_medical_cases_chart\n",
      "wikidataId":"Q25528"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Morocco_(including_occupied_Western_Sahara)_medical_cases_chart\n",
      "wikidataId":"Q1028"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Uganda_medical_cases_chart\n",
      "wikidataId":"Q1036"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Kyrgyzstan_medical_cases_chart/sandbox\n",
      "wikidataId":"Q813"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Haiti_medical_cases_chart\n",
      "wikidataId":"Q790"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Europe_medical_cases_chart\n",
      "wikidataId":"Q46"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Equatorial_Guinea_medical_cases_chart\n",
      "wikidataId":"Q983"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Dominica_medical_cases_chart\n",
      "wikidataId":"Q784"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Bonaire_medical_cases_chart\n",
      "wikidataId":"Q25396"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Benin_medical_cases_chart\n",
      "wikidataId":"Q962"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Belize_medical_cases_chart\n",
      "wikidataId":"Q242"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/The_Bahamas_medical_cases_chart\n",
      "wikidataId":"Q778"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Aruba_medical_cases_chart\n",
      "wikidataId":"Q21203"
   },
   {
      "url":"https://en.wikipedia.org/wiki/Template:COVID-19_pandemic_data/Republic_of_Artsakh_medical_cases_chart",
      "wikidataId":"Q244165"
   }
]
