# gcloud builds submit --config=cloudbuild.yaml . --project=datcom-import-automation-prod 

steps:
- id: 'import-automation-workflow'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['workflows', 'deploy', 'import-automation-workflow', '--source', 'import-automation-workflow.yaml']

- id: 'spanner-ingestion-workflow'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['workflows', 'deploy', 'spanner-ingestion-workflow', '--source', 'spanner-ingestion-workflow.yaml']

- id: 'spanner-ingestion-helper'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'spanner-ingestion-helper', '--runtime', 'python312', '--source', 'ingestion-helper', '--no-allow-unauthenticated', '--trigger-http', '--entry-point', 'ingestion_helper']

- id: 'import-automation-helper'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'import-automation-helper', '--runtime', 'python312', '--source', 'automation-helper', '--trigger-topic', 'import-automation-trigger' , '--entry-point', 'handle_feed_event']

