# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Parent Cloud Build configuration that orchestrates Staging and Production deployments.
# Usage: gcloud builds submit . --config=cloudbuild.yaml --project=datcom-ci

substitutions:
  # Staging Configuration (Overrides defaults in child build)
  _PROJECT_ID: 'datcom-ci'
  _SPANNER_PROJECT_ID: 'datcom-ci'
  _SPANNER_INSTANCE_ID: 'datcom-spanner-test'
  _SPANNER_DATABASE_ID: 'dc-test-db'
  _GCS_BUCKET_ID: 'datcom-ci-test'
  _GCS_MOUNT_BUCKET: 'datcom-ci-test'
  _BQ_DATASET_ID: 'datacommons'
  _LOCATION: 'us-central1'

steps:

# 1. Trigger Staging Build (Child)
# Overrides default (Production) values with Staging values.
- id: 'deploy-staging'
  name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'builds'
    - 'submit'
    - '.'
    - '--config=cloudbuild.yaml'
    - '--project=${_PROJECT_ID}'
    - '--substitutions=_ENV=staging,_PROJECT_ID=${_PROJECT_ID},_SPANNER_PROJECT_ID=${_SPANNER_PROJECT_ID},_SPANNER_INSTANCE_ID=${_SPANNER_INSTANCE_ID},_SPANNER_DATABASE_ID=${_SPANNER_DATABASE_ID},_GCS_BUCKET_ID=${_GCS_BUCKET_ID},_LOCATION=${_LOCATION},_GCS_MOUNT_BUCKET=${_GCS_MOUNT_BUCKET},_BQ_DATASET_ID=${_BQ_DATASET_ID}'
  dir: 'import-automation/workflow'

# 2. Run E2E Tests on Staging
- id: 'e2e-test-staging'
  name: 'python:3.11'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      pip install google-cloud-spanner google-cloud-workflows absl-py
      python spanner_ingestion_test.py
  env:
    - 'PROJECT_ID=${_PROJECT_ID}'
    - 'LOCATION=${_LOCATION}'
    - 'SPANNER_PROJECT_ID=${_SPANNER_PROJECT_ID}'
    - 'SPANNER_INSTANCE_ID=${_SPANNER_INSTANCE_ID}'
    - 'SPANNER_DATABASE_ID=${_SPANNER_DATABASE_ID}'
    - 'GCS_BUCKET_ID=${_GCS_BUCKET_ID}'
  dir: 'import-automation/workflow'

# 3. Trigger Production Build (Child)
# Uses default (Production) values defined in cloudbuild_deploy.yaml.
- id: 'deploy-prod'
  name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'builds'
    - 'submit'
    - '.'
    - '--config=cloudbuild.yaml'
    - '--project=${_PROJECT_ID}'  # Build runs in CI project, deploys to Prod
  dir: 'import-automation/workflow'
