# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Generic staging golden test verification gate for Data Commons imports.

Evaluates an allowlist of sensitive imports (e.g. Schema, Place). When an import
is in the allowlist, it clears the Staging Redis cache and runs Explore/NL golden
tests via Cloud Build in diff mode to gate production promotion.
All other imports skip this gate and auto-approve immediately.
"""

from __future__ import annotations

from datetime import datetime, timezone
import json
import logging
import os
import re
import sys
import time
from typing import Any

from airflow.decorators import task
from airflow.exceptions import AirflowFailException
from airflow.models import Variable
from airflow.sensors.base import BaseSensorOperator
from airflow.utils.trigger_rule import TriggerRule

current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir not in sys.path:
    sys.path.insert(0, current_dir)

DEFAULT_GOLDEN_TEST_IMPORTS = frozenset({
    "Schema",
    "Place",
})

DEFAULT_IMPORT_TRIGGERS: dict[str, str] = {
    "schema": "ingestion-golden-verification",
    "place": "ingestion-golden-verification",
}
FALLBACK_TRIGGER_ID = "ingestion-golden-verification"
DEFAULT_BUILD_PROJECT = "datcom-ci"
DEFAULT_BRANCH = "master"
DEFAULT_DIFF_BUCKET = "datcom-ci-test"


def get_golden_test_imports() -> set[str]:
    """Retrieves allowlist from Airflow Variable, OS env, or defaults."""
    fallback = os.environ.get("GOLDEN_TEST_IMPORTS", "")
    try:
        raw = Variable.get("GOLDEN_TEST_IMPORTS", default_var=fallback)
    except Exception:
        raw = fallback

    if raw and isinstance(raw, str):
        try:
            parsed = json.loads(raw)
            if isinstance(parsed, list):
                return {item.strip() for item in parsed if isinstance(item, str) and item.strip()}
        except Exception:
            pass
        return {item.strip() for item in re.split(r"[,;\s]+", raw) if item.strip()}

    return set(DEFAULT_GOLDEN_TEST_IMPORTS)


def is_golden_test_import(import_name: str, allowlist: set[str] | None = None) -> bool:
    """Checks whether the import matches the golden test allowlist."""
    if not import_name:
        return False
    targets = allowlist if allowlist is not None else get_golden_test_imports()
    short_name = import_name.split(":")[-1]
    normalized = {t.lower() for t in targets}
    return import_name.lower() in normalized or short_name.lower() in normalized


def get_golden_trigger_id(import_name: str, custom_trigger: str = "") -> str:
    """Resolves the Cloud Build trigger ID for an import."""
    if custom_trigger:
        return custom_trigger
    short_name = import_name.split(":")[-1].lower()
    return DEFAULT_IMPORT_TRIGGERS.get(short_name, FALLBACK_TRIGGER_ID)


def get_diff_bucket(custom_bucket: str = "") -> str:
    """Resolves the GCS bucket storing golden diff summaries."""
    if custom_bucket:
        return custom_bucket
    fallback = os.environ.get("GOLDEN_DIFF_BUCKET", DEFAULT_DIFF_BUCKET)
    try:
        return Variable.get("GOLDEN_DIFF_BUCKET", default_var=fallback)
    except Exception:
        return fallback


def _fetch_diff_summary(
    build_id: str,
    bucket_name: str = DEFAULT_DIFF_BUCKET,
    max_retries: int = 3,
) -> dict[str, Any]:
    """Fetches diff_summary.json generated by Cloud Build from GCS."""
    if not build_id:
        return {"has_diff": False, "pr_url": "", "message": "No build ID provided"}

    object_path = f"golden_diffs/{build_id}/diff_summary.json"
    logging.info("Fetching diff summary from gs://%s/%s...", bucket_name, object_path)

    for attempt in range(1, max_retries + 1):
        # 1. Try GCSHook
        try:
            from airflow.providers.google.cloud.hooks.gcs import GCSHook
            hook = GCSHook(gcp_conn_id="google_cloud_default")
            content = hook.download(bucket_name=bucket_name, object_name=object_path)
            if isinstance(content, bytes):
                content = content.decode("utf-8")
            parsed = json.loads(content)
            logging.info("Fetched diff summary via GCSHook on attempt %d: %s", attempt, parsed)
            return parsed
        except Exception as ex:
            logging.debug("GCSHook download attempt %d failed: %s", attempt, ex)

        # 2. Try google.cloud.storage client
        try:
            from google.cloud import storage
            client = storage.Client()
            bucket = client.bucket(bucket_name)
            blob = bucket.blob(object_path)
            if blob.exists():
                content = blob.download_as_text()
                parsed = json.loads(content)
                logging.info("Fetched diff summary via google.cloud.storage on attempt %d: %s", attempt, parsed)
                return parsed
        except Exception as ex:
            logging.debug("google.cloud.storage attempt %d failed: %s", attempt, ex)

        # 3. Direct REST API via AuthorizedSession
        try:
            import google.auth
            from google.auth.transport.requests import AuthorizedSession

            credentials, _ = google.auth.default(
                scopes=[
                    "https://www.googleapis.com/auth/devstorage.read_only",
                    "https://www.googleapis.com/auth/cloud-platform",
                ]
            )
            session = AuthorizedSession(credentials)
            url = f"https://storage.googleapis.com/storage/v1/b/{bucket_name}/o/{object_path.replace('/', '%2F')}?alt=media"
            resp = session.get(url, timeout=30)
            if resp.ok:
                parsed = resp.json()
                logging.info("Fetched diff summary via REST API on attempt %d: %s", attempt, parsed)
                return parsed
        except Exception as ex:
            logging.debug("REST API attempt %d failed: %s", attempt, ex)

        if attempt < max_retries:
            time.sleep(2)

    logging.warning(
        "Could not retrieve diff_summary.json from gs://%s/%s after %d attempts",
        bucket_name, object_path, max_retries
    )
    return {
        "has_diff": False,
        "pr_url": "",
        "message": f"Could not retrieve diff_summary.json from gs://{bucket_name}/{object_path}",
    }


def _run_cloud_build_verification(
    project_id: str,
    trigger_id: str,
    branch_name: str = "master",
    timeout: int = 2400,
    poll_interval: int = 30,
) -> dict[str, Any]:
    """Triggers and polls Cloud Build trigger for golden test verification."""
    try:
        from airflow.providers.google.cloud.hooks.cloud_build import CloudBuildHook
        hook = CloudBuildHook(gcp_conn_id="google_cloud_default")
        try:
            build = hook.run_build_trigger(
                trigger_id=trigger_id,
                source={"branch_name": branch_name},
                project_id=project_id,
                wait=True,
            )
        except TypeError:
            build = hook.run_build_trigger(
                request={
                    "project_id": project_id,
                    "trigger_id": trigger_id,
                    "source": {"branch_name": branch_name},
                }
            )
        b_status = getattr(build, "status", None) or (build.get("status") if isinstance(build, dict) else "")
        b_id = getattr(build, "id", None) or (build.get("id") if isinstance(build, dict) else "")
        b_log = getattr(build, "log_url", None) or getattr(build, "logUrl", None) or (build.get("logUrl") if isinstance(build, dict) else "")
        status_str = getattr(b_status, "name", str(b_status))
        return {"id": str(b_id), "status": status_str, "logUrl": str(b_log)}
    except Exception as ex:
        logging.warning("CloudBuildHook execution error, falling back to direct API: %s", ex)

    # Fallback to direct REST API
    import google.auth
    from google.auth.transport.requests import AuthorizedSession

    credentials, _ = google.auth.default(scopes=["https://www.googleapis.com/auth/cloud-platform"])
    authed_session = AuthorizedSession(credentials)

    run_url = f"https://cloudbuild.googleapis.com/v1/projects/{project_id}/triggers/{trigger_id}:run"
    resp = authed_session.post(run_url, json={"branchName": branch_name}, timeout=60)
    resp.raise_for_status()
    op = resp.json()

    metadata = op.get("metadata", {})
    build_info = metadata.get("build", {})
    build_id = build_info.get("id") or op.get("name", "").split("/")[-1]
    log_url = build_info.get("logUrl", "")

    logging.info("Started Cloud Build '%s' via trigger '%s'. Waiting for completion...", build_id, trigger_id)
    start_time = time.time()
    build_url = f"https://cloudbuild.googleapis.com/v1/projects/{project_id}/builds/{build_id}"
    while time.time() - start_time < timeout:
        time.sleep(poll_interval)
        poll_resp = authed_session.get(build_url, timeout=60)
        if not poll_resp.ok:
            continue
        b_data = poll_resp.json()
        b_status = b_data.get("status", "")
        log_url = b_data.get("logUrl", log_url)
        if b_status in ("SUCCESS", "FAILURE", "INTERNAL_ERROR", "TIMEOUT", "CANCELLED", "EXPIRED"):
            return {"id": build_id, "status": b_status, "logUrl": log_url}

    raise TimeoutError(f"Cloud Build verification '{build_id}' timed out after {timeout} seconds.")


@task(task_id="verify_golden_tests", trigger_rule=TriggerRule.NONE_FAILED)
def verify_golden_tests(**context) -> dict[str, Any]:
    """Runs staging verification gate for allowlisted imports (e.g. Schema, Place)."""
    # Lazy import to avoid circular dependency
    from import_automation_workflow import resolve_workflow_context, _report_import_failure

    cfg = resolve_workflow_context(context)
    ti = context.get("ti")
    staging_res = ti.xcom_pull(task_ids="trigger_staging_ingestion") if ti else None

    dag_run = context.get("dag_run")
    conf = dag_run.conf if dag_run and dag_run.conf else {}
    params = context.get("params") or {}

    def _p(key: str, default: Any = None) -> Any:
        if key in conf and conf[key] is not None:
            return conf[key]
        return params.get(key, default)

    explicit_skip = bool(_p("skipGoldenTests", False))
    explicit_run = bool(_p("runGoldenTests", False))
    import_name = cfg["importName"]

    # 1. Eligibility Check: Allowlist or explicit run flag
    if not (explicit_run or is_golden_test_import(import_name)) or explicit_skip:
        logging.info("Import '%s' is not configured for golden verification; skipping.", import_name)
        return {
            "status": "SKIPPED",
            "hasDiff": False,
            "prUrl": "",
            "reason": f"Import '{import_name}' not in golden test allowlist",
        }

    # 2. Check staging prerequisite
    if (
        cfg["skipStagingIngestion"]
        or not staging_res
        or staging_res.get("status") not in ("SUBMITTED", "SUCCESS")
    ):
        logging.info("Staging ingestion was not successful; skipping golden gate.")
        return {
            "status": "SKIPPED",
            "hasDiff": False,
            "prUrl": "",
            "reason": "Staging ingestion was not SUCCESS",
        }

    # 3. Resolve Trigger ID, Project, Branch, and Diff Bucket
    trigger_id = get_golden_trigger_id(
        import_name,
        custom_trigger=_p("goldenTestTriggerId") or os.environ.get("GOLDEN_TEST_TRIGGER_ID", ""),
    )
    project_id = _p("goldenTestProjectId") or os.environ.get("GOLDEN_TEST_PROJECT_ID", DEFAULT_BUILD_PROJECT)
    branch_name = _p("goldenTestBranch") or os.environ.get("GOLDEN_TEST_BRANCH", DEFAULT_BRANCH)
    diff_bucket = get_diff_bucket(_p("goldenDiffBucket") or os.environ.get("GOLDEN_DIFF_BUCKET", ""))

    logging.info("Triggering staging golden verification Cloud Build '%s' on %s (%s)...", trigger_id, project_id, branch_name)
    start_time = time.time()
    try:
        build_res = _run_cloud_build_verification(
            project_id=project_id,
            trigger_id=trigger_id,
            branch_name=branch_name,
        )
        build_id = build_res.get("id", "")
        log_url = build_res.get("logUrl", "")
        b_status = build_res.get("status", "")
        duration = int(time.time() - start_time)

        if b_status == "SUCCESS":
            diff_summary = _fetch_diff_summary(build_id=build_id, bucket_name=diff_bucket)
            has_diff = bool(diff_summary.get("has_diff", False))
            pr_url = str(diff_summary.get("pr_url", ""))
            branch = str(diff_summary.get("branch_name", ""))
            logging.info(
                "Golden verification succeeded in %ss (build: %s, hasDiff: %s, prUrl: %s, log: %s).",
                duration, build_id, has_diff, pr_url, log_url
            )
            return {
                "status": "SUCCESS",
                "buildId": build_id,
                "logUrl": log_url,
                "executionTime": duration,
                "hasDiff": has_diff,
                "prUrl": pr_url,
                "branchName": branch,
                "diffSummary": diff_summary,
            }

        # Failure: Report failure to import-helper and raise exception to block prod
        exec_dt = context.get("logical_date") or context.get("execution_date")
        exec_time = int(time.time() - (exec_dt.timestamp() if exec_dt else start_time))
        helper_url = cfg["helperUrlFn"](cfg["importHelperService"], "-staging")
        _report_import_failure(helper_url, cfg["jobId"], cfg["importName"], cfg["gcsImportBucket"], exec_time)

        err_msg = f"Golden gate failed with status '{b_status}' (build: {build_id}, logs: {log_url}). Blocking prod promotion."
        logging.error(err_msg)
        raise AirflowFailException(err_msg)

    except AirflowFailException:
        raise
    except Exception as e:
        exec_dt = context.get("logical_date") or context.get("execution_date")
        exec_time = int(time.time() - (exec_dt.timestamp() if exec_dt else start_time))
        helper_url = cfg["helperUrlFn"](cfg["importHelperService"], "-staging")
        _report_import_failure(helper_url, cfg["jobId"], cfg["importName"], cfg["gcsImportBucket"], exec_time)
        raise AirflowFailException(f"Golden verification error: {e}") from e


class HumanApprovalSensor(BaseSensorOperator):
    """Airflow sensor that pauses DAG execution awaiting human approval if golden diffs were detected.

    Auto-approves immediately if:
    - Golden test verification was skipped, or
    - Golden test verification succeeded and detected no diffs (hasDiff is False), or
    - autoApproveGoldenDiff parameter is set to True.

    Waits for approval if:
    - Golden test verification detected diffs (hasDiff is True).

    Approval options:
    - Set Airflow Variable `PROD_APPROVE_<job_id>` = 'true'
    - Set Airflow Variable `PROD_APPROVE_<import_name>` = 'true'
    - Set Airflow Variable `PROD_APPROVE_ALL` = 'true'
    - Click 'Mark Success' on this task in the Airflow UI.

    Rejection options:
    - Set Airflow Variable `PROD_REJECT_<job_id>` = 'true'
    - Set Airflow Variable `PROD_REJECT_<import_name>` = 'true'
    - Click 'Mark Failed' on this task in the Airflow UI.
    """

    template_fields = ("job_id", "import_name")

    def __init__(
        self,
        job_id: str = "",
        import_name: str = "",
        mode: str = "reschedule",
        poke_interval: int = 60,
        timeout: int = 86400,  # 24 hours
        soft_fail: bool = False,
        trigger_rule: str = TriggerRule.NONE_FAILED,
        **kwargs,
    ):
        super().__init__(
            mode=mode,
            poke_interval=poke_interval,
            timeout=timeout,
            soft_fail=soft_fail,
            trigger_rule=trigger_rule,
            **kwargs,
        )
        self.job_id = job_id
        self.import_name = import_name

    def poke(self, context: dict[str, Any]) -> bool:
        dag_run = context.get("dag_run")
        conf = dag_run.conf if dag_run and dag_run.conf else {}
        params = context.get("params") or {}

        def _p(key: str, default: Any = None) -> Any:
            if key in conf and conf[key] is not None:
                return conf[key]
            return params.get(key, default)

        if bool(_p("autoApproveGoldenDiff", False)):
            logging.info("autoApproveGoldenDiff parameter is True; auto-approving prod promotion.")
            return True

        ti = context.get("ti")
        golden_res = ti.xcom_pull(task_ids="verify_golden_tests") if ti else None

        # Auto-approve if golden check was skipped, not run, or had no diffs
        if not golden_res or golden_res.get("status") != "SUCCESS" or not golden_res.get("hasDiff"):
            logging.info(
                "HumanApprovalSensor: No golden diffs detected (or gate skipped). Auto-approving prod promotion."
            )
            return True

        from import_automation_workflow import resolve_workflow_context
        try:
            cfg = resolve_workflow_context(context)
        except Exception:
            cfg = {}
        job_id = self.job_id or cfg.get("jobId", "")
        import_name = self.import_name or cfg.get("importName", "")
        short_import = import_name.split(":")[-1] if import_name else ""

        pr_url = golden_res.get("prUrl", "")
        log_url = golden_res.get("logUrl", "")
        build_id = golden_res.get("buildId", "")

        # Check for rejection signals first
        reject_keys = [
            f"PROD_REJECT_{job_id}",
            f"PROD_REJECT_{import_name}",
            f"PROD_REJECT_{short_import}",
        ]
        for rk in reject_keys:
            if not rk.strip():
                continue
            try:
                r_val = Variable.get(rk, default_var="")
                if isinstance(r_val, str) and r_val.strip().lower() in ("true", "1", "yes"):
                    msg = f"Prod promotion for '{import_name}' (job: {job_id}) was REJECTED via Airflow Variable '{rk}'."
                    logging.error(msg)
                    raise AirflowFailException(msg)
            except AirflowFailException:
                raise
            except Exception:
                pass

        # Check for approval signals
        approve_keys = [
            f"PROD_APPROVE_{job_id}",
            f"PROD_APPROVE_{import_name}",
            f"PROD_APPROVE_{short_import}",
            "PROD_APPROVE_ALL",
        ]
        for ak in approve_keys:
            if not ak.strip():
                continue
            try:
                a_val = Variable.get(ak, default_var="")
                if isinstance(a_val, str) and a_val.strip().lower() in ("true", "1", "yes"):
                    logging.info(
                        "Prod promotion for '%s' (job: %s) APPROVED via Airflow Variable '%s'.",
                        import_name, job_id, ak
                    )
                    return True
            except Exception:
                pass

        # Diff detected and awaiting human approval
        logging.info(
            "\n"
            "================================================================================\n"
            "  PAUSED FOR HUMAN APPROVAL: STAGING GOLDEN DIFF DETECTED\n"
            "================================================================================\n"
            "  Import:    %s\n"
            "  Job ID:    %s\n"
            "  Build ID:  %s\n"
            "  PR URL:    %s\n"
            "  Build Log: %s\n"
            "--------------------------------------------------------------------------------\n"
            "  To APPROVE prod promotion:\n"
            "    1. In Airflow UI, select task 'await_human_approval' and click 'Mark Success', OR\n"
            "    2. Set Airflow Variable 'PROD_APPROVE_%s' = 'true'\n"
            "\n"
            "  To REJECT prod promotion:\n"
            "    1. In Airflow UI, select task 'await_human_approval' and click 'Mark Failed', OR\n"
            "    2. Set Airflow Variable 'PROD_REJECT_%s' = 'true'\n"
            "================================================================================\n",
            import_name, job_id, build_id, pr_url, log_url, job_id, job_id
        )
        return False

    def execute(self, context: dict[str, Any]) -> dict[str, Any]:
        super().execute(context)
        ti = context.get("ti")
        golden_res = ti.xcom_pull(task_ids="verify_golden_tests") if ti else {}
        return {
            "status": "APPROVED",
            "hasDiff": bool(golden_res.get("hasDiff", False)),
            "prUrl": golden_res.get("prUrl", ""),
            "approvedAt": datetime.now(timezone.utc).isoformat(),
        }
