# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""EurostatNUTS1 codes -> Region names.

NOTE: Some names are missing.
"""

NUTS1_CODES_NAMES = {
    'nuts/DEF': 'Schleswig-Holstein',
    'nuts/UKD': 'North West',
    'nuts/UKF': 'East Midlands',
    'nuts/UKH': 'East of England',
    'nuts/UKG': 'West Midlands',
    'nuts/FR3': None,
    'nuts/TRC': 'Güneydogu Anadolu',
    'nuts/BG4': 'Югозападна И Южна Централна България',
    'nuts/PT2': 'Região Autónoma dos Açores',
    'nuts/NL2': 'Oost-Nederland',
    'nuts/NL3': 'West-Nederland',
    'nuts/PL2': 'Makroregion Południowy',
    'nuts/PT3': 'Região Autónoma da Madeira',
    'nuts/SE1': 'Östra Sverige',
    'nuts/PL8': 'Makroregion Wschodni',
    'nuts/TR3': 'Ege',
    'nuts/TR5': 'Bati Anadolu',
    'nuts/RO1': 'Macroregiunea Unu',
    'nuts/PL4': 'Makroregion Północno-Zachodni',
    'nuts/ITG': 'Isole',
    'nuts/TRA': 'Kuzeydogu Anadolu',
    'nuts/NO0': 'Norge',
    'nuts/ITI': 'Centro',
    'nuts/SE2': 'Södra Sverige',
    'nuts/CH0': 'Schweiz/Suisse/Svizzera',
    'nuts/UKC': 'North East',
    'nuts/ES2': 'Noreste',
    'nuts/TR7': 'Orta Anadolu',
    'nuts/FRG': 'Pays de la Loire',
    'nuts/EL6': 'Κεντρικη Ελλαδα',
    'nuts/PL9': 'Makroregion Województwo Mazowieckie',
    'nuts/AT2': 'Südösterreich',
    'nuts/ES6': 'Sur',
    'nuts/FRY': 'Rup Fr - Régions Ultrapériphériques Françaises',
    'nuts/UKJ': 'South East',
    'nuts/BG3': 'Северна И Югоизточна България',
    'nuts/HU1': 'Közép-Magyarország',
    'nuts/EE0': 'Eesti',
    'nuts/RO4': 'Macroregiunea Patru',
    'nuts/ES5': 'Este',
    'nuts/CZ0': 'Česká Republika',
    'nuts/ITF': 'Sud',
    'nuts/TRB': 'Ortadogu Anadolu',
    'nuts/TR8': 'Bati Karadeniz',
    'nuts/ES4': 'Centro',
    'nuts/TR9': 'Dogu Karadeniz',
    'nuts/FRB': 'Centre - Val de Loire',
    'nuts/SE3': 'Norra Sverige',
    'nuts/DK0': 'Danmark',
    'nuts/RO2': 'Macroregiunea Doi',
    'nuts/EL4': 'Nησια Αιγαιου, Kρητη',
    'nuts/EL5': 'Βορεια Ελλαδα',
    'nuts/FRH': 'Bretagne',
    'nuts/NL4': 'Zuid-Nederland',
    'nuts/RS2': 'Србија - југ ',
    'nuts/FI2': 'Åland',
    'nuts/EL3': 'Attikη',
    'nuts/HU2': 'Dunántúl',
    'nuts/ITC': 'Nord-Ovest',
    'nuts/PL6': 'Makroregion Północny',
    'nuts/ME0': 'Црна Гора',
    'nuts/FRM': 'Corse',
    'nuts/AT1': 'Ostösterreich',
    'nuts/ES1': 'Noroeste',
    'nuts/HR0': 'Hrvatska',
    'nuts/SI0': 'Slovenija',
    'nuts/PL7': 'Makroregion Centralny',
    'nuts/ITH': 'Nord-Est',
    'nuts/LV0': 'Latvija',
    'nuts/AL0': 'Shqipëria',
    'nuts/LI0': 'Liechtenstein',
    'nuts/MK0': 'Severna Makedonija',
    'nuts/TR1': 'Istanbul',
    'nuts/RO3': 'Macroregiunea Trei',
    'nuts/UKE': 'Yorkshire and the Humber',
    'nuts/SK0': 'Slovensko',
    'nuts/PT1': 'Continente',
    'nuts/HU3': 'Alföld és Észak',
    'nuts/LU0': 'Luxembourg',
    'nuts/MT0': 'Malta',
    'nuts/TR6': 'Akdeniz',
    'nuts/TR2': 'Bati Marmara',
    'nuts/RS1': 'Србија - север ',
    'nuts/FRL': 'Provence-Alpes-Côte d’Azur',
    'nuts/TR4': 'Dogu Marmara',
    'nuts/IE0': 'Ireland',
    'nuts/LT0': 'Lietuva',
    'nuts/IS0': 'Ísland',
    'nuts/FI1': 'Manner-Suomi',
    'nuts/UKK': 'South West',
    'nuts/AT3': 'Westösterreich',
    'nuts/PL5': 'Makroregion Południowo-Zachodni',
    'nuts/CY0': 'Κυπρος',
    'nuts/FR8': None,
    'nuts/PL3': None,
    'nuts/ITZ': None,
    'nuts/HUZ': None,
    'nuts/PTZ': None,
    'nuts/PLZ': None,
    'nuts/MTZ': None,
    'nuts/BEZ': None,
    'nuts/ATZ': None,
    'nuts/SEZ': None,
    'nuts/ELZ': None,
    'nuts/LUZ': None,
    'nuts/UKZ': None,
    'nuts/IEZ': None,
    'nuts/SKZ': None,
    'nuts/ITD': None,
    'nuts/LTZ': None,
    'nuts/ROZ': None,
    'nuts/FR7': None,
    'nuts/NLZ': None,
    'nuts/SIZ': None,
    'nuts/LVZ': None,
    'nuts/FR9': None,
    'nuts/ESZ': None,
    'nuts/FR5': None,
    'nuts/PL1': None,
    'nuts/DKZ': None,
    'nuts/CZZ': None,
    'nuts/FR4': None,
    'nuts/FIZ': None,
    'nuts/EL1': None,
    'nuts/CYZ': None,
    'nuts/ITE': None,
    'nuts/EEZ': None,
    'nuts/DEZ': None,
    'nuts/FR2': None,
    'nuts/FRA': None,
    'nuts/EL2': None,
    'nuts/BGZ': None,
    'nuts/FR6': None,
    'nuts/FRZ': None,
    'nuts/FRC': 'Bourgogne-Franche-Comté',
    'nuts/FRD': 'Normandie',
    'nuts/FRF': 'Alsace-Champagne-Ardenne-Lorraine',
    'nuts/FR1': 'Ile-de-France',
    'nuts/FRJ': 'Languedoc-Roussillon-Midi-Pyrénées',
    'nuts/FRE': 'Hauts-de-France',
    'nuts/FRI': 'Aquitaine-Limousin-Poitou-Charentes',
    'nuts/FRK': 'Auvergne-Rhône-Alpes',
    'nuts/DE7': 'Hesse',
    'nuts/DE8': 'Mecklenburg-Vorpommern',
    'nuts/DEB': 'Rheinland-Pfalz',
    'nuts/DEG': 'Free State of Thuringia',
    'nuts/DED': 'Sachsen',
    'nuts/DEA': 'Nordrhein-Westfalen',
    'nuts/DE2': 'Bavaria',
    'nuts/DE9': 'Lower Saxony',
    'nuts/DEC': 'Saarland',
    'nuts/DE1': 'Baden-Württemberg',
    'nuts/DE5': 'Bremen',
    'nuts/DEE': 'Sachsen-Anhalt',
    'nuts/DE4': 'Brandenburg',
    'nuts/DE3': 'Berlin',
    'nuts/UKL': 'Wales',
    'nuts/UKM': 'Scotland',
    'nuts/UKN': 'Northern Ireland',
    'nuts/UKI': 'Greater London',
    'nuts/ES3': 'Community of Madrid',
    'nuts/ES7': 'Canarias',
    'nuts/BE3': 'Région Wallonne',
    'nuts/BE1': 'Brussels Capital',
    'nuts/BE2': 'Flanders',
    'nuts/NL1': 'Noord-Nederland'
}
