{
    # US State codes to dcids.
    "AL": "dcid:geoId/01",
    "AK": "dcid:geoId/02",
    "AZ": "dcid:geoId/04",
    "AR": "dcid:geoId/05",
    "CA": "dcid:geoId/06",
    "CO": "dcid:geoId/08",
    "CT": "dcid:geoId/09",
    "DE": "dcid:geoId/10",
    "DC": "dcid:geoId/11",
    "FL": "dcid:geoId/12",
    "GA": "dcid:geoId/13",
    "HI": "dcid:geoId/15",
    "ID": "dcid:geoId/16",
    "IL": "dcid:geoId/17",
    "IN": "dcid:geoId/18",
    "IA": "dcid:geoId/19",
    "KS": "dcid:geoId/20",
    "KY": "dcid:geoId/21",
    "LA": "dcid:geoId/22",
    "ME": "dcid:geoId/23",
    "MD": "dcid:geoId/24",
    "MA": "dcid:geoId/25",
    "MI": "dcid:geoId/26",
    "MN": "dcid:geoId/27",
    "MS": "dcid:geoId/28",
    "MO": "dcid:geoId/29",
    "MT": "dcid:geoId/30",
    "NE": "dcid:geoId/31",
    "NV": "dcid:geoId/32",
    "NH": "dcid:geoId/33",
    "NJ": "dcid:geoId/34",
    "NM": "dcid:geoId/35",
    "NY": "dcid:geoId/36",
    "NC": "dcid:geoId/37",
    "ND": "dcid:geoId/38",
    "OH": "dcid:geoId/39",
    "OK": "dcid:geoId/40",
    "OR": "dcid:geoId/41",
    "PA": "dcid:geoId/42",
    "RI": "dcid:geoId/44",
    "SC": "dcid:geoId/45",
    "SD": "dcid:geoId/46",
    "TN": "dcid:geoId/47",
    "TX": "dcid:geoId/48",
    "UT": "dcid:geoId/49",
    "VT": "dcid:geoId/50",
    "VA": "dcid:geoId/51",
    "WA": "dcid:geoId/53",
    "WV": "dcid:geoId/54",
    "WI": "dcid:geoId/55",
    "WY": "dcid:geoId/56",
    "AS": "dcid:geoId/60",
    "GU": "dcid:geoId/66",
    "MP": "dcid:geoId/69",
    "PR": "dcid:geoId/72",
    "UM": "dcid:geoId/74",
    "VI": "dcid:geoId/78",

    # US State names to dcids.
    "alabama": "dcid:geoId/01",
    "alaska": "dcid:geoId/02",
    "arizona": "dcid:geoId/04",
    "arkansas": "dcid:geoId/05",
    "california": "dcid:geoId/06",
    "colorado": "dcid:geoId/08",
    "connecticut": "dcid:geoId/09",
    "delaware": "dcid:geoId/10",
    "district of columbia": "dcid:geoId/11",
    "florida": "dcid:geoId/12",
    "georgia": "dcid:geoId/13",
    "guam": "dcid:geoId/66",
    "hawaii": "dcid:geoId/15",
    "idaho": "dcid:geoId/16",
    "illinois": "dcid:geoId/17",
    "indiana": "dcid:geoId/18",
    "iowa": "dcid:geoId/19",
    "kansas": "dcid:geoId/20",
    "kentucky": "dcid:geoId/21",
    "louisiana": "dcid:geoId/22",
    "maine": "dcid:geoId/23",
    "maryland": "dcid:geoId/24",
    "massachusetts": "dcid:geoId/25",
    "michigan": "dcid:geoId/26",
    "minnesota": "dcid:geoId/27",
    "mississippi": "dcid:geoId/28",
    "missouri": "dcid:geoId/29",
    "montana": "dcid:geoId/30",
    "nebraska": "dcid:geoId/31",
    "nevada": "dcid:geoId/32",
    "new hampshire": "dcid:geoId/33",
    "new jersey": "dcid:geoId/34",
    "new mexico": "dcid:geoId/35",
    "new york": "dcid:geoId/36",
    "north carolina": "dcid:geoId/37",
    "north dakota": "dcid:geoId/38",
    "ohio": "dcid:geoId/39",
    "oklahoma": "dcid:geoId/40",
    "oregon": "dcid:geoId/41",
    "puerto rico": "dcid:geoId/72",
    "pennsylvania": "dcid:geoId/42",
    "rhode island": "dcid:geoId/44",
    "south carolina": "dcid:geoId/45",
    "south dakota": "dcid:geoId/46",
    "tennessee": "dcid:geoId/47",
    "texas": "dcid:geoId/48",
    "utah": "dcid:geoId/49",
    "vermont": "dcid:geoId/50",
    "virginia": "dcid:geoId/51",
    "washington": "dcid:geoId/53",
    "west virginia": "dcid:geoId/54",
    "wisconsin": "dcid:geoId/55",
    "wyoming": "dcid:geoId/56",
}
