# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import unittest
import pandas as pd
from pandas.testing import assert_frame_equal
from process import IndiaAirQualityDataLoader

module_dir = os.path.dirname(__file__)


class TestProcess(unittest.TestCase):
  """
  Test Class to compare expected output in test/ directory to the
  output generated by india_cpcb.process.IndiaAirQualityDataLoader class
  """

  def test_process(self):
    loader = IndiaAirQualityDataLoader()
    in_df = loader.get_feed(os.path.join(module_dir, "test", "data.xml"))
    sites_file = os.path.join(module_dir, "test", "sites.csv")
    lgd_file = os.path.join(module_dir, "test", "lgd.csv")
    site_df = loader.generate_sites(in_df, sites_file, lgd_file)
    result = loader.process_data(in_df, site_df)

    expected_data = pd.read_csv(os.path.join(module_dir, "test", "data.csv"))
    assert_frame_equal(result, expected_data)

if __name__ == "__main__":
  unittest.main()
