# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Maps of different contaminants and contaminatedThings to their respective schema dcids."""

### Map for contaminants to dcids where the key is a title cased name that appears in the dataset to their respective dcids
_CHEM_MAP = {
    "Methane": "Methane",
    "Carbonate": "Carbonate",
    "Nitrate": "Nitrate",
    "Sulfate": "Sulfate",
    "Dioxosilane": "Dioxosilane",
    "Hydrogen": "Hydrogen",
    "Helium": "Helium",
    "Lithium": "Lithium",
    "Beryllium": "Beryllium",
    "Boron": "Boron",
    "Carbon": "Carbon",
    "Nitrogen": "Nitrogen",
    "Oxygen": "Oxygen",
    "Fluorine": "Fluorine",
    "Neon": "Neon",
    "Sodium": "Sodium",
    "Magnesium": "Magnesium",
    "Aluminum": "Aluminum",
    "Silicon": "Silicon",
    "Phosphorus": "Phosphorus",
    "Sulfur": "Sulfur",
    "Chlorine": "Chlorine",
    "Argon": "Argon",
    "Potassium": "Potassium",
    "Calcium": "Calcium",
    "Scandium": "Scandium",
    "Titanium": "Titanium",
    "Vanadium": "Vanadium",
    "Chromium": "Chromium",
    "Manganese": "Manganese",
    "Iron": "Iron",
    "Cobalt": "Cobalt",
    "Nickel": "Nickel",
    "Copper": "Copper",
    "Zinc": "Zinc",
    "Gallium": "Gallium",
    "Germanium": "Germanium",
    "Arsenic": "Arsenic",
    "Selenium": "Selenium",
    "Bromine": "Bromine",
    "Krypton": "Krypton",
    "Rubidium": "Rubidium",
    "Strontium": "Strontium",
    "Yttrium": "Yttrium",
    "Zirconium": "Zirconium",
    "Niobium": "Niobium",
    "Molybdenum": "Molybdenum",
    "Technetium": "Technetium",
    "Ruthenium": "Ruthenium",
    "Rhodium": "Rhodium",
    "Palladium": "Palladium",
    "Silver": "Silver",
    "Cadmium": "Cadmium",
    "Indium": "Indium",
    "Tin": "Tin",
    "Antimony": "Antimony",
    "Tellurium": "Tellurium",
    "Iodine": "Iodine",
    "Xenon": "Xenon",
    "Cesium": "Cesium",
    "Barium": "Barium",
    "Lanthanum": "Lanthanum",
    "Cerium": "Cerium",
    "Praseodymium": "Praseodymium",
    "Neodymium": "Neodymium",
    "Promethium": "Promethium",
    "Samarium": "Samarium",
    "Europium": "Europium",
    "Gadolinium": "Gadolinium",
    "Terbium": "Terbium",
    "Dysprosium": "Dysprosium",
    "Holmium": "Holmium",
    "Erbium": "Erbium",
    "Thulium": "Thulium",
    "Ytterbium": "Ytterbium",
    "Lutetium": "Lutetium",
    "Hafnium": "Hafnium",
    "Tantalum": "Tantalum",
    "Tungsten": "Tungsten",
    "Rhenium": "Rhenium",
    "Osmium": "Osmium",
    "Iridium": "Iridium",
    "Platinum": "Platinum",
    "Gold": "Gold",
    "Mercury": "Mercury",
    "Thallium": "Thallium",
    "Lead": "Lead",
    "Bismuth": "Bismuth",
    "Polonium": "Polonium",
    "Astatine": "Astatine",
    "Radon": "Radon",
    "Francium": "Francium",
    "Radium": "Radium",
    "Actinium": "Actinium",
    "Thorium": "Thorium",
    "Protactinium": "Protactinium",
    "Uranium": "Uranium",
    "Neptunium": "Neptunium",
    "Plutonium": "Plutonium",
    "Americium": "Americium",
    "Curium": "Curium",
    "Berkelium": "Berkelium",
    "Californium": "Californium",
    "Einsteinium": "Einsteinium",
    "Fermium": "Fermium",
    "Mendelevium": "Mendelevium",
    "Nobelium": "Nobelium",
    "Lawrencium": "Lawrencium",
    "Rutherfordium": "Rutherfordium",
    "Dubnium": "Dubnium",
    "Seaborgium": "Seaborgium",
    "Bohrium": "Bohrium",
    "Hassium": "Hassium",
    "Meitnerium": "Meitnerium",
    "Darmstadtium": "Darmstadtium",
    "Roentgenium": "Roentgenium",
    "Copernicium": "Copernicium",
    "Nihonium": "Nihonium",
    "Flerovium": "Flerovium",
    "Moscovium": "Moscovium",
    "Livermorium": "Livermorium",
    "Tennessine": "Tennessine"
}

### Map for the different contaminated media to their respective dcids
_CONTAMINATED_THING_DCID_MAP = {
    'Groundwater': "GroundWater",
    'Soil': "Soil",
    'Sediment': "Sediment",
    'Solid Waste': "SolidWaste",
    'Surface Water': "SurfaceWater",
    'Debris': "Debris",
    'Buildings/Structures': "BuildingOrStructures",
    'Leachate': "Leachate",
    'Sludge': "Sludge",
    'Free-phase NAPL': "FreePhaseNAPL",
    'Liquid Waste': "LiquidWaste",
    'Soil Gas': "SoilGas",
    'Other': "EPA_OtherContaminatedThing",
    'Landfill Gas': "LandfillGas",
    'Air': "Atmosphere",
    'Fish Tissue': "FishTissue",
    'Residuals': "Residuals"
}
