#!/bin/bash
set -e

SCRIPT_PATH=$(realpath "$(dirname "$0")")

python3 $SCRIPT_PATH/../../../tools/statvar_importer/stat_var_processor.py --input_data=$SCRIPT_PATH/input_files/employment_by_classification_of_economic_activities_region_gender_and_agegroup.csv --pv_map=$SCRIPT_PATH/employment_by_classification_of_economic_activities_region_gender_and_agegroup_pvmap.csv --config_file=$SCRIPT_PATH/metadata.csv --output_path=$SCRIPT_PATH/output_files/employment_by_classification_of_economic_activities_region_gender_and_agegroup_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --places_resolved_csv=$SCRIPT_PATH/places_resolved.csv || { echo "Error: Processing employment_by_classification_of_economic_activities_region_gender_and_agegroup failed!"; exit 1; }

python3 $SCRIPT_PATH/../../../tools/statvar_importer/stat_var_processor.py --input_data=$SCRIPT_PATH/input_files/employment_by_occupation_by_region_gender_and_agegroup.csv --pv_map=$SCRIPT_PATH/employment_by_occupation_by_region_gender_and_agegroup_pvmap.csv --config_file=$SCRIPT_PATH/employment_by_occupation_by_region_gender_and_agegroup_metadata.csv --output_path=$SCRIPT_PATH/output_files/employment_by_occupation_by_region_gender_and_agegroup_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --places_resolved_csv=$SCRIPT_PATH/places_resolved.csv || { echo "Error: Processing employment_by_occupation_by_region_gender_and_agegroup failed!"; exit 1; }

python3 $SCRIPT_PATH/../../../tools/statvar_importer/stat_var_processor.py --input_data=$SCRIPT_PATH/input_files/employment_to_population_ratio_by_region_gender_and_agegroup.csv --pv_map=$SCRIPT_PATH/employment_to_population_ratio_by_region_gender_and_agegroup_pvmap.csv --config_file=$SCRIPT_PATH/employment_to_population_ratio_by_region_gender_and_agegroup_metadata.csv --output_path=$SCRIPT_PATH/output_files/employment_to_population_ratio_by_region_gender_and_agegroup_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --places_resolved_csv=$SCRIPT_PATH/places_resolved.csv || { echo "Error: Processing employment_to_population_ratio_by_region_gender_and_agegroup failed!"; exit 1; }

python3 $SCRIPT_PATH/../../../tools/statvar_importer/stat_var_processor.py --input_data=$SCRIPT_PATH/input_files/labour_force_by_region_gender_and_agegroup.csv --pv_map=$SCRIPT_PATH/labour_force_by_region_gender_and_agegroup_pvmap.csv --config_file=$SCRIPT_PATH/metadata.csv --output_path=$SCRIPT_PATH/output_files/labour_force_by_region_gender_and_agegroup_output --places_resolved_csv=$SCRIPT_PATH/places_resolved.csv --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf || { echo "Error: Processing labour_force_by_region_gender_and_agegroup failed!"; exit 1; }

python3 $SCRIPT_PATH/../../../tools/statvar_importer/stat_var_processor.py --input_data=$SCRIPT_PATH/input_files/labour_underutilization_by_region_gender_and_agegroup.csv --pv_map=$SCRIPT_PATH/labour_underutilization_by_region_gender_and_agegroup_pvmap.csv --config_file=$SCRIPT_PATH/metadata.csv --output_path=$SCRIPT_PATH/output_files/labour_underutilization_by_region_gender_and_agegroup_output --places_resolved_csv=$SCRIPT_PATH/places_resolved.csv --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf || { echo "Error: Processing labour_under_utilization_by_region_gender_and_agegroup failed!"; exit 1; }

python3 $SCRIPT_PATH/../../../tools/statvar_importer/stat_var_processor.py --input_data=$SCRIPT_PATH/input_files/registered_unemployed_by_education_level_region_gender_month.csv --pv_map=$SCRIPT_PATH/registered_unemployed_by_education_level_region_gender_month_pvmap.csv --config_file=$SCRIPT_PATH/metadata.csv --output_path=$SCRIPT_PATH/output_files/registered_unemployed_by_education_level_region_gender_month_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --places_resolved_csv=$SCRIPT_PATH/places_resolved.csv || { echo "Error: Processing registered_unemployed_by_education_level_region_gender_month failed!"; exit 1; }

echo "All processing steps completed successfully."
exit 0
