import unittest
import os
import sys
# Import everything from your main script
from education_enrollment_preprocess_gen_tmcf import *

MODULE_DIR = os.path.dirname(__file__)
sys.path.insert(0, MODULE_DIR)

TEST_DATASET_DIR = os.path.join(MODULE_DIR, "test_data", "sample_input")
EXPECTED_FILES_DIR = os.path.join(MODULE_DIR, "test_data", "sample_output")

class TestProcess(unittest.TestCase):

    def setUp(self):
        """
        Setup runs before every test. 
        It processes the sample input and saves it to a temporary test file.
        """
        self.input_path = os.path.join(TEST_DATASET_DIR, 'sample_data.tsv')
        self.actual_csv_path = os.path.join(EXPECTED_FILES_DIR, "test_output.csv")
        self.expected_csv_path = os.path.join(EXPECTED_FILES_DIR, "Eurostats_NUTS2_Enrollment.csv")

        # 1. Transform wide to long
        df = translate_wide_to_long(self.input_path)
        
        # 2. Apply filtering (Must match the main script logic)
        df = df[
            (df['unit'] == 'PC') & 
            (df['age'].isin(['Y18-64', 'Y25-64']))
        ]
        
        # 3. Generate the CSV
        preprocess(df, self.actual_csv_path)

    def test_create_csv(self):
        """
        Compare the generated CSV against the expected CSV.
        """
        # Read Expected Data
        with open(self.expected_csv_path, encoding="utf-8") as f:
            expected_csv_data = f.read().strip()

        # Read Actual Data (Generated by setUp)
        with open(self.actual_csv_path, encoding="utf-8-sig") as f:
            actual_csv_data = f.read().strip()

        # Assertion
        self.assertEqual(expected_csv_data, actual_csv_data)
if __name__ == "__main__":
    unittest.main()