_dcid_map = {
    'dcs:Count_JobPosting_NAICSJOLTS_000000_Adjusted':
        'dcs:dc/ek7gq6ylyjwn8',
    'dcs:Count_JobPosting_NAICSJOLTS_000000_Unadjusted':
        'dcs:dc/30rxf2zkfexbf',
    'dcs:Count_JobPosting_NAICS10_Adjusted':
        'dcs:Count_JobPosting_NAICSTotalAllIndustries_Adjusted',
    'dcs:Count_JobPosting_NAICS10_Unadjusted':
        'dcs:Count_JobPosting_NAICSTotalAllIndustries_Unadjusted',
    'dcs:Count_JobPosting_NAICSJOLTS_110099_Adjusted':
        'dcs:dc/dtp1j5zqvcccc',
    'dcs:Count_JobPosting_NAICSJOLTS_110099_Unadjusted':
        'dcs:dc/wp8cckcnx8xm2',
    'dcs:Count_JobPosting_NAICS23_Adjusted':
        'dcs:Count_JobPosting_NAICSConstruction_Adjusted',
    'dcs:Count_JobPosting_NAICS23_Unadjusted':
        'dcs:Count_JobPosting_NAICSConstruction_Unadjusted',
    'dcs:Count_JobPosting_NAICSJOLTS_300000_Adjusted':
        'dcs:dc/c8rcs7p2lxtmc',
    'dcs:Count_JobPosting_NAICSJOLTS_300000_Unadjusted':
        'dcs:dc/vkpfhkbyrpmdf',
    'dcs:Count_JobPosting_NAICSJOLTS_320000_Adjusted':
        'dcs:dc/d0yc8nnyhs7jb',
    'dcs:Count_JobPosting_NAICSJOLTS_320000_Unadjusted':
        'dcs:dc/01h322br38tc4',
    'dcs:Count_JobPosting_NAICSJOLTS_340000_Adjusted':
        'dcs:dc/nss2f8esebgh1',
    'dcs:Count_JobPosting_NAICSJOLTS_340000_Unadjusted':
        'dcs:dc/bpwdptf6111bg',
    'dcs:Count_JobPosting_NAICSJOLTS_400000_Adjusted':
        'dcs:dc/5cz584gnzv8dh',
    'dcs:Count_JobPosting_NAICSJOLTS_400000_Unadjusted':
        'dcs:dc/rt5nf3xjjfy12',
    'dcs:Count_JobPosting_NAICS42_Adjusted':
        'dcs:Count_JobPosting_NAICSWholesaleTrade_Adjusted',
    'dcs:Count_JobPosting_NAICS42_Unadjusted':
        'dcs:Count_JobPosting_NAICSWholesaleTrade_Unadjusted',
    'dcs:Count_JobPosting_NAICS44_Adjusted':
        'dcs:Count_JobPosting_NAICSRetailTrade_Adjusted',
    'dcs:Count_JobPosting_NAICS44_Unadjusted':
        'dcs:Count_JobPosting_NAICSRetailTrade_Unadjusted',
    'dcs:Count_JobPosting_NAICSJOLTS_480099_Adjusted':
        'dcs:dc/1ezw091537gm3',
    'dcs:Count_JobPosting_NAICSJOLTS_480099_Unadjusted':
        'dcs:dc/4gdq2b1cms3gf',
    'dcs:Count_JobPosting_NAICS51_Adjusted':
        'dcs:Count_JobPosting_NAICSInformation_Adjusted',
    'dcs:Count_JobPosting_NAICS51_Unadjusted':
        'dcs:Count_JobPosting_NAICSInformation_Unadjusted',
    'dcs:Count_JobPosting_NAICSJOLTS_510099_Adjusted':
        'dcs:dc/rqr5n4gthnej',
    'dcs:Count_JobPosting_NAICSJOLTS_510099_Unadjusted':
        'dcs:dc/c940w58tlt358',
    'dcs:Count_JobPosting_NAICS52_Adjusted':
        'dcs:Count_JobPosting_NAICSFinanceInsurance_Adjusted',
    'dcs:Count_JobPosting_NAICS52_Unadjusted':
        'dcs:Count_JobPosting_NAICSFinanceInsurance_Unadjusted',
    'dcs:Count_JobPosting_NAICS53_Adjusted':
        'dcs:Count_JobPosting_NAICSRealEstateRentalLeasing_Adjusted',
    'dcs:Count_JobPosting_NAICS53_Unadjusted':
        'dcs:Count_JobPosting_NAICSRealEstateRentalLeasing_Unadjusted',
    'dcs:Count_JobPosting_NAICSJOLTS_540099_Adjusted':
        'dcs:dc/51t0gkfryfrx8',
    'dcs:Count_JobPosting_NAICSJOLTS_540099_Unadjusted':
        'dcs:dc/nm9xrhz74d5lb',
    'dcs:Count_JobPosting_NAICSJOLTS_600000_Adjusted':
        'dcs:dc/3jpp0hc5h7xm7',
    'dcs:Count_JobPosting_NAICSJOLTS_600000_Unadjusted':
        'dcs:dc/nl0v1ydksdyfg',
    'dcs:Count_JobPosting_NAICS61_Adjusted':
        'dcs:Count_JobPosting_NAICSEducationalServices_Adjusted',
    'dcs:Count_JobPosting_NAICS61_Unadjusted':
        'dcs:Count_JobPosting_NAICSEducationalServices_Unadjusted',
    'dcs:Count_JobPosting_NAICS62_Adjusted':
        'dcs:Count_JobPosting_NAICSHealthCareSocialAssistance_Adjusted',
    'dcs:Count_JobPosting_NAICS62_Unadjusted':
        'dcs:Count_JobPosting_NAICSHealthCareSocialAssistance_Unadjusted',
    'dcs:Count_JobPosting_NAICSJOLTS_700000_Adjusted':
        'dcs:dc/4evxdg8gcqz6d',
    'dcs:Count_JobPosting_NAICSJOLTS_700000_Unadjusted':
        'dcs:dc/vmlfl3gw1whlc',
    'dcs:Count_JobPosting_NAICS71_Adjusted':
        'dcs:Count_JobPosting_NAICSArtsEntertainmentRecreation_Adjusted',
    'dcs:Count_JobPosting_NAICS71_Unadjusted':
        'dcs:Count_JobPosting_NAICSArtsEntertainmentRecreation_Unadjusted',
    'dcs:Count_JobPosting_NAICS72_Adjusted':
        'dcs:Count_JobPosting_NAICSAccommodationFoodServices_Adjusted',
    'dcs:Count_JobPosting_NAICS72_Unadjusted':
        'dcs:Count_JobPosting_NAICSAccommodationFoodServices_Unadjusted',
    'dcs:Count_JobPosting_NAICS81_Adjusted':
        'dcs:Count_JobPosting_NAICSOtherServices_Adjusted',
    'dcs:Count_JobPosting_NAICS81_Unadjusted':
        'dcs:Count_JobPosting_NAICSOtherServices_Unadjusted',
    'dcs:Count_JobPosting_NAICSJOLTS_900000_Adjusted':
        'dcs:dc/dh0dv0wd6zlt6',
    'dcs:Count_JobPosting_NAICSJOLTS_900000_Unadjusted':
        'dcs:dc/tzrhzpylrlnt9',
    'dcs:Count_JobPosting_NAICSJOLTS_910000_Adjusted':
        'dcs:dc/zfpwsc9xb57zc',
    'dcs:Count_JobPosting_NAICSJOLTS_910000_Unadjusted':
        'dcs:dc/0nzdwncybc8j',
    'dcs:Count_JobPosting_NAICS92_Adjusted':
        'dcs:Count_JobPosting_NAICSPublicAdministration_Adjusted',
    'dcs:Count_JobPosting_NAICS92_Unadjusted':
        'dcs:Count_JobPosting_NAICSPublicAdministration_Unadjusted',
    'dcs:Count_JobPosting_NAICSJOLTS_923000_Adjusted':
        'dcs:dc/xw5ybx88r89q4',
    'dcs:Count_JobPosting_NAICSJOLTS_923000_Unadjusted':
        'dcs:dc/vphll4dfp4tk6',
    'dcs:Count_JobPosting_NAICSJOLTS_929000_Adjusted':
        'dcs:dc/hy3xj0zkhx0mb',
    'dcs:Count_JobPosting_NAICSJOLTS_929000_Unadjusted':
        'dcs:dc/gh8789np3hq29',
    'dcs:Count_Worker_Hire_NAICSJOLTS_000000_Adjusted':
        'dcs:dc/tq6l9rmwbrv71',
    'dcs:Count_Worker_Hire_NAICSJOLTS_000000_Unadjusted':
        'dcs:dc/bfgd2kclqq2hb',
    'dcs:Count_Worker_Hire_NAICS10_Adjusted':
        'dcs:Count_Worker_Hire_NAICSTotalAllIndustries_Adjusted',
    'dcs:Count_Worker_Hire_NAICS10_Unadjusted':
        'dcs:Count_Worker_Hire_NAICSTotalAllIndustries_Unadjusted',
    'dcs:Count_Worker_Hire_NAICSJOLTS_110099_Adjusted':
        'dcs:dc/h7ts06vdxn8q8',
    'dcs:Count_Worker_Hire_NAICSJOLTS_110099_Unadjusted':
        'dcs:dc/t6ckwd6c8j2w6',
    'dcs:Count_Worker_Hire_NAICS23_Adjusted':
        'dcs:Count_Worker_Hire_NAICSConstruction_Adjusted',
    'dcs:Count_Worker_Hire_NAICS23_Unadjusted':
        'dcs:Count_Worker_Hire_NAICSConstruction_Unadjusted',
    'dcs:Count_Worker_Hire_NAICSJOLTS_300000_Adjusted':
        'dcs:dc/x8dr1g4htkyg8',
    'dcs:Count_Worker_Hire_NAICSJOLTS_300000_Unadjusted':
        'dcs:dc/2hfmh1sq8t8f4',
    'dcs:Count_Worker_Hire_NAICSJOLTS_320000_Adjusted':
        'dcs:dc/dwtwtq3g5x44b',
    'dcs:Count_Worker_Hire_NAICSJOLTS_320000_Unadjusted':
        'dcs:dc/fzr2v1yff7b9h',
    'dcs:Count_Worker_Hire_NAICSJOLTS_340000_Adjusted':
        'dcs:dc/eyp8h09nnnwkc',
    'dcs:Count_Worker_Hire_NAICSJOLTS_340000_Unadjusted':
        'dcs:dc/x1sh09g13fkk3',
    'dcs:Count_Worker_Hire_NAICSJOLTS_400000_Adjusted':
        'dcs:dc/mph2vzg6f70v',
    'dcs:Count_Worker_Hire_NAICSJOLTS_400000_Unadjusted':
        'dcs:dc/xyqhbb27lrbgb',
    'dcs:Count_Worker_Hire_NAICS42_Adjusted':
        'dcs:Count_Worker_Hire_NAICSWholesaleTrade_Adjusted',
    'dcs:Count_Worker_Hire_NAICS42_Unadjusted':
        'dcs:Count_Worker_Hire_NAICSWholesaleTrade_Unadjusted',
    'dcs:Count_Worker_Hire_NAICS44_Adjusted':
        'dcs:Count_Worker_Hire_NAICSRetailTrade_Adjusted',
    'dcs:Count_Worker_Hire_NAICS44_Unadjusted':
        'dcs:Count_Worker_Hire_NAICSRetailTrade_Unadjusted',
    'dcs:Count_Worker_Hire_NAICSJOLTS_480099_Adjusted':
        'dcs:dc/m7pwzzwkqpsb7',
    'dcs:Count_Worker_Hire_NAICSJOLTS_480099_Unadjusted':
        'dcs:dc/89l7rgg1rrll5',
    'dcs:Count_Worker_Hire_NAICS51_Adjusted':
        'dcs:Count_Worker_Hire_NAICSInformation_Adjusted',
    'dcs:Count_Worker_Hire_NAICS51_Unadjusted':
        'dcs:Count_Worker_Hire_NAICSInformation_Unadjusted',
    'dcs:Count_Worker_Hire_NAICSJOLTS_510099_Adjusted':
        'dcs:dc/jp0950j9w4rt6',
    'dcs:Count_Worker_Hire_NAICSJOLTS_510099_Unadjusted':
        'dcs:dc/mxbc4zxxdp165',
    'dcs:Count_Worker_Hire_NAICS52_Adjusted':
        'dcs:Count_Worker_Hire_NAICSFinanceInsurance_Adjusted',
    'dcs:Count_Worker_Hire_NAICS52_Unadjusted':
        'dcs:Count_Worker_Hire_NAICSFinanceInsurance_Unadjusted',
    'dcs:Count_Worker_Hire_NAICS53_Adjusted':
        'dcs:Count_Worker_Hire_NAICSRealEstateRentalLeasing_Adjusted',
    'dcs:Count_Worker_Hire_NAICS53_Unadjusted':
        'dcs:Count_Worker_Hire_NAICSRealEstateRentalLeasing_Unadjusted',
    'dcs:Count_Worker_Hire_NAICSJOLTS_540099_Adjusted':
        'dcs:dc/m2ngj8d5ly4cb',
    'dcs:Count_Worker_Hire_NAICSJOLTS_540099_Unadjusted':
        'dcs:dc/jqnypr99llkdh',
    'dcs:Count_Worker_Hire_NAICSJOLTS_600000_Adjusted':
        'dcs:dc/s257ebg00btp5',
    'dcs:Count_Worker_Hire_NAICSJOLTS_600000_Unadjusted':
        'dcs:dc/byrn0vcwfn9gg',
    'dcs:Count_Worker_Hire_NAICS61_Adjusted':
        'dcs:Count_Worker_Hire_NAICSEducationalServices_Adjusted',
    'dcs:Count_Worker_Hire_NAICS61_Unadjusted':
        'dcs:Count_Worker_Hire_NAICSEducationalServices_Unadjusted',
    'dcs:Count_Worker_Hire_NAICS62_Adjusted':
        'dcs:Count_Worker_Hire_NAICSHealthCareSocialAssistance_Adjusted',
    'dcs:Count_Worker_Hire_NAICS62_Unadjusted':
        'dcs:Count_Worker_Hire_NAICSHealthCareSocialAssistance_Unadjusted',
    'dcs:Count_Worker_Hire_NAICSJOLTS_700000_Adjusted':
        'dcs:dc/h9ttmz5re79f3',
    'dcs:Count_Worker_Hire_NAICSJOLTS_700000_Unadjusted':
        'dcs:dc/296j7xdfqe293',
    'dcs:Count_Worker_Hire_NAICS71_Adjusted':
        'dcs:Count_Worker_Hire_NAICSArtsEntertainmentRecreation_Adjusted',
    'dcs:Count_Worker_Hire_NAICS71_Unadjusted':
        'dcs:Count_Worker_Hire_NAICSArtsEntertainmentRecreation_Unadjusted',
    'dcs:Count_Worker_Hire_NAICS72_Adjusted':
        'dcs:Count_Worker_Hire_NAICSAccommodationFoodServices_Adjusted',
    'dcs:Count_Worker_Hire_NAICS72_Unadjusted':
        'dcs:Count_Worker_Hire_NAICSAccommodationFoodServices_Unadjusted',
    'dcs:Count_Worker_Hire_NAICS81_Adjusted':
        'dcs:Count_Worker_Hire_NAICSOtherServices_Adjusted',
    'dcs:Count_Worker_Hire_NAICS81_Unadjusted':
        'dcs:Count_Worker_Hire_NAICSOtherServices_Unadjusted',
    'dcs:Count_Worker_Hire_NAICSJOLTS_900000_Adjusted':
        'dcs:dc/e581kq907h9j2',
    'dcs:Count_Worker_Hire_NAICSJOLTS_900000_Unadjusted':
        'dcs:dc/q8ry6ry1g5wjh',
    'dcs:Count_Worker_Hire_NAICSJOLTS_910000_Adjusted':
        'dcs:dc/w87kkgeq7mmv9',
    'dcs:Count_Worker_Hire_NAICSJOLTS_910000_Unadjusted':
        'dcs:dc/300weyjd58gnd',
    'dcs:Count_Worker_Hire_NAICS92_Adjusted':
        'dcs:Count_Worker_Hire_NAICSPublicAdministration_Adjusted',
    'dcs:Count_Worker_Hire_NAICS92_Unadjusted':
        'dcs:Count_Worker_Hire_NAICSPublicAdministration_Unadjusted',
    'dcs:Count_Worker_Hire_NAICSJOLTS_923000_Adjusted':
        'dcs:dc/xfzhg4hhtxvhg',
    'dcs:Count_Worker_Hire_NAICSJOLTS_923000_Unadjusted':
        'dcs:dc/52wsdvxp1xzpc',
    'dcs:Count_Worker_Hire_NAICSJOLTS_929000_Adjusted':
        'dcs:dc/zre77fpzme029',
    'dcs:Count_Worker_Hire_NAICSJOLTS_929000_Unadjusted':
        'dcs:dc/t0q4x9ww70d7d',
    'dcs:Count_Worker_Separation_NAICSJOLTS_000000_Adjusted':
        'dcs:dc/1sv6tr4wyp51f',
    'dcs:Count_Worker_Separation_NAICSJOLTS_000000_Unadjusted':
        'dcs:dc/m0w182psvwn03',
    'dcs:Count_Worker_Separation_NAICS10_Adjusted':
        'dcs:Count_Worker_Separation_NAICSTotalAllIndustries_Adjusted',
    'dcs:Count_Worker_Separation_NAICS10_Unadjusted':
        'dcs:Count_Worker_Separation_NAICSTotalAllIndustries_Unadjusted',
    'dcs:Count_Worker_Separation_NAICSJOLTS_110099_Adjusted':
        'dcs:dc/8nfjemp5yqh0d',
    'dcs:Count_Worker_Separation_NAICSJOLTS_110099_Unadjusted':
        'dcs:dc/x39lmxjrjcb',
    'dcs:Count_Worker_Separation_NAICS23_Adjusted':
        'dcs:Count_Worker_Separation_NAICSConstruction_Adjusted',
    'dcs:Count_Worker_Separation_NAICS23_Unadjusted':
        'dcs:Count_Worker_Separation_NAICSConstruction_Unadjusted',
    'dcs:Count_Worker_Separation_NAICSJOLTS_300000_Adjusted':
        'dcs:dc/8hlwxsmtxsx08',
    'dcs:Count_Worker_Separation_NAICSJOLTS_300000_Unadjusted':
        'dcs:dc/hc1j2ljz6kyg4',
    'dcs:Count_Worker_Separation_NAICSJOLTS_320000_Adjusted':
        'dcs:dc/w88v1ptpm6znh',
    'dcs:Count_Worker_Separation_NAICSJOLTS_320000_Unadjusted':
        'dcs:dc/s22rj8gcbr3f6',
    'dcs:Count_Worker_Separation_NAICSJOLTS_340000_Adjusted':
        'dcs:dc/wmgpbffcdfwc9',
    'dcs:Count_Worker_Separation_NAICSJOLTS_340000_Unadjusted':
        'dcs:dc/bfz6x00fr2ep9',
    'dcs:Count_Worker_Separation_NAICSJOLTS_400000_Adjusted':
        'dcs:dc/g93g7qbm6vslh',
    'dcs:Count_Worker_Separation_NAICSJOLTS_400000_Unadjusted':
        'dcs:dc/q9fj2md2xdqnf',
    'dcs:Count_Worker_Separation_NAICS42_Adjusted':
        'dcs:Count_Worker_Separation_NAICSWholesaleTrade_Adjusted',
    'dcs:Count_Worker_Separation_NAICS42_Unadjusted':
        'dcs:Count_Worker_Separation_NAICSWholesaleTrade_Unadjusted',
    'dcs:Count_Worker_Separation_NAICS44_Adjusted':
        'dcs:Count_Worker_Separation_NAICSRetailTrade_Adjusted',
    'dcs:Count_Worker_Separation_NAICS44_Unadjusted':
        'dcs:Count_Worker_Separation_NAICSRetailTrade_Unadjusted',
    'dcs:Count_Worker_Separation_NAICSJOLTS_480099_Adjusted':
        'dcs:dc/6247s8558p4q4',
    'dcs:Count_Worker_Separation_NAICSJOLTS_480099_Unadjusted':
        'dcs:dc/csm0r29we8c2g',
    'dcs:Count_Worker_Separation_NAICS51_Adjusted':
        'dcs:Count_Worker_Separation_NAICSInformation_Adjusted',
    'dcs:Count_Worker_Separation_NAICS51_Unadjusted':
        'dcs:Count_Worker_Separation_NAICSInformation_Unadjusted',
    'dcs:Count_Worker_Separation_NAICSJOLTS_510099_Adjusted':
        'dcs:dc/sbt4mlmhh5x1f',
    'dcs:Count_Worker_Separation_NAICSJOLTS_510099_Unadjusted':
        'dcs:dc/70fghvv84s2p6',
    'dcs:Count_Worker_Separation_NAICS52_Adjusted':
        'dcs:Count_Worker_Separation_NAICSFinanceInsurance_Adjusted',
    'dcs:Count_Worker_Separation_NAICS52_Unadjusted':
        'dcs:Count_Worker_Separation_NAICSFinanceInsurance_Unadjusted',
    'dcs:Count_Worker_Separation_NAICS53_Adjusted':
        'dcs:Count_Worker_Separation_NAICSRealEstateRentalLeasing_Adjusted',
    'dcs:Count_Worker_Separation_NAICS53_Unadjusted':
        'dcs:Count_Worker_Separation_NAICSRealEstateRentalLeasing_Unadjusted',
    'dcs:Count_Worker_Separation_NAICSJOLTS_540099_Adjusted':
        'dcs:dc/ew7155r4ysmec',
    'dcs:Count_Worker_Separation_NAICSJOLTS_540099_Unadjusted':
        'dcs:dc/cnbzyv6pb1h4c',
    'dcs:Count_Worker_Separation_NAICSJOLTS_600000_Adjusted':
        'dcs:dc/kw4g4zwezz7h6',
    'dcs:Count_Worker_Separation_NAICSJOLTS_600000_Unadjusted':
        'dcs:dc/4neh5hdbg5lh1',
    'dcs:Count_Worker_Separation_NAICS61_Adjusted':
        'dcs:Count_Worker_Separation_NAICSEducationalServices_Adjusted',
    'dcs:Count_Worker_Separation_NAICS61_Unadjusted':
        'dcs:Count_Worker_Separation_NAICSEducationalServices_Unadjusted',
    'dcs:Count_Worker_Separation_NAICS62_Adjusted':
        'dcs:Count_Worker_Separation_NAICSHealthCareSocialAssistance_Adjusted',
    'dcs:Count_Worker_Separation_NAICS62_Unadjusted':
        'dcs:Count_Worker_Separation_NAICSHealthCareSocialAssistance_Unadjusted',
    'dcs:Count_Worker_Separation_NAICSJOLTS_700000_Adjusted':
        'dcs:dc/dcbege7vbmnlf',
    'dcs:Count_Worker_Separation_NAICSJOLTS_700000_Unadjusted':
        'dcs:dc/39l9dkn9l1lpb',
    'dcs:Count_Worker_Separation_NAICS71_Adjusted':
        'dcs:Count_Worker_Separation_NAICSArtsEntertainmentRecreation_Adjusted',
    'dcs:Count_Worker_Separation_NAICS71_Unadjusted':
        'dcs:Count_Worker_Separation_NAICSArtsEntertainmentRecreation_Unadjusted',
    'dcs:Count_Worker_Separation_NAICS72_Adjusted':
        'dcs:Count_Worker_Separation_NAICSAccommodationFoodServices_Adjusted',
    'dcs:Count_Worker_Separation_NAICS72_Unadjusted':
        'dcs:Count_Worker_Separation_NAICSAccommodationFoodServices_Unadjusted',
    'dcs:Count_Worker_Separation_NAICS81_Adjusted':
        'dcs:Count_Worker_Separation_NAICSOtherServices_Adjusted',
    'dcs:Count_Worker_Separation_NAICS81_Unadjusted':
        'dcs:Count_Worker_Separation_NAICSOtherServices_Unadjusted',
    'dcs:Count_Worker_Separation_NAICSJOLTS_900000_Adjusted':
        'dcs:dc/871wlj36sn5b4',
    'dcs:Count_Worker_Separation_NAICSJOLTS_900000_Unadjusted':
        'dcs:dc/4nrecf5y8yrd5',
    'dcs:Count_Worker_Separation_NAICSJOLTS_910000_Adjusted':
        'dcs:dc/xzy9ssjshx7wf',
    'dcs:Count_Worker_Separation_NAICSJOLTS_910000_Unadjusted':
        'dcs:dc/yfhwzxxt04l56',
    'dcs:Count_Worker_Separation_NAICS92_Adjusted':
        'dcs:Count_Worker_Separation_NAICSPublicAdministration_Adjusted',
    'dcs:Count_Worker_Separation_NAICS92_Unadjusted':
        'dcs:Count_Worker_Separation_NAICSPublicAdministration_Unadjusted',
    'dcs:Count_Worker_Separation_NAICSJOLTS_923000_Adjusted':
        'dcs:dc/pprrjpjtj4gb4',
    'dcs:Count_Worker_Separation_NAICSJOLTS_923000_Unadjusted':
        'dcs:dc/hzxt8v6eq1214',
    'dcs:Count_Worker_Separation_NAICSJOLTS_929000_Adjusted':
        'dcs:dc/b0dthet6fb2kc',
    'dcs:Count_Worker_Separation_NAICSJOLTS_929000_Unadjusted':
        'dcs:dc/177zj3zevcwk9',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_000000_Adjusted':
        'dcs:dc/p18hmxm2d3sj4',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_000000_Unadjusted':
        'dcs:dc/ckehkd9th1mfh',
    'dcs:Count_Worker_VoluntarySeparation_NAICS10_Adjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSTotalAllIndustries_Adjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICS10_Unadjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSTotalAllIndustries_Unadjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_110099_Adjusted':
        'dcs:dc/rm1gek937g0w',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_110099_Unadjusted':
        'dcs:dc/9rz93yn17vcxf',
    'dcs:Count_Worker_VoluntarySeparation_NAICS23_Adjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSConstruction_Adjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICS23_Unadjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSConstruction_Unadjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_300000_Adjusted':
        'dcs:dc/3v0x1nz99djcg',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_300000_Unadjusted':
        'dcs:dc/ww1estl3syqyc',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_320000_Adjusted':
        'dcs:dc/5syffrnqhh4s1',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_320000_Unadjusted':
        'dcs:dc/6wcg2gb583g06',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_340000_Adjusted':
        'dcs:dc/8s3ppvzv919j3',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_340000_Unadjusted':
        'dcs:dc/m7ygqfwvcw5s5',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_400000_Adjusted':
        'dcs:dc/6b6m0mdfrlw1b',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_400000_Unadjusted':
        'dcs:dc/tnfcg1bpxcncd',
    'dcs:Count_Worker_VoluntarySeparation_NAICS42_Adjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSWholesaleTrade_Adjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICS42_Unadjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSWholesaleTrade_Unadjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICS44_Adjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSRetailTrade_Adjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICS44_Unadjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSRetailTrade_Unadjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_480099_Adjusted':
        'dcs:dc/6gx0hj3yk35kf',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_480099_Unadjusted':
        'dcs:dc/x31bde1hvnrb8',
    'dcs:Count_Worker_VoluntarySeparation_NAICS51_Adjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSInformation_Adjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICS51_Unadjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSInformation_Unadjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_510099_Adjusted':
        'dcs:dc/lz3pqnz5m95th',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_510099_Unadjusted':
        'dcs:dc/eqser28904mn8',
    'dcs:Count_Worker_VoluntarySeparation_NAICS52_Adjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSFinanceInsurance_Adjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICS52_Unadjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSFinanceInsurance_Unadjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICS53_Adjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSRealEstateRentalLeasing_Adjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICS53_Unadjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSRealEstateRentalLeasing_Unadjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_540099_Adjusted':
        'dcs:dc/npw2js6m1t0nh',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_540099_Unadjusted':
        'dcs:dc/9s923nr78cnsd',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_600000_Adjusted':
        'dcs:dc/tz9jcmtsxeggg',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_600000_Unadjusted':
        'dcs:dc/f9gbh1vbqbc32',
    'dcs:Count_Worker_VoluntarySeparation_NAICS61_Adjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSEducationalServices_Adjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICS61_Unadjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSEducationalServices_Unadjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICS62_Adjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSHealthCareSocialAssistance_Adjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICS62_Unadjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSHealthCareSocialAssistance_Unadjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_700000_Adjusted':
        'dcs:dc/fdm897cx6d016',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_700000_Unadjusted':
        'dcs:dc/5n9h3rj4f5rw5',
    'dcs:Count_Worker_VoluntarySeparation_NAICS71_Adjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSArtsEntertainmentRecreation_Adjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICS71_Unadjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSArtsEntertainmentRecreation_Unadjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICS72_Adjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSAccommodationFoodServices_Adjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICS72_Unadjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSAccommodationFoodServices_Unadjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICS81_Adjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSOtherServices_Adjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICS81_Unadjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSOtherServices_Unadjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_900000_Adjusted':
        'dcs:dc/vz130wfqm5k1f',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_900000_Unadjusted':
        'dcs:dc/knnl36czn70qf',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_910000_Adjusted':
        'dcs:dc/jtfmzjn190zb7',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_910000_Unadjusted':
        'dcs:dc/v5wr2m9s63q77',
    'dcs:Count_Worker_VoluntarySeparation_NAICS92_Adjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSPublicAdministration_Adjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICS92_Unadjusted':
        'dcs:Count_Worker_VoluntarySeparation_NAICSPublicAdministration_Unadjusted',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_923000_Adjusted':
        'dcs:dc/jkq5x0yml5nkb',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_923000_Unadjusted':
        'dcs:dc/yt93yq0kmcw01',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_929000_Adjusted':
        'dcs:dc/25httt4l9wdn2',
    'dcs:Count_Worker_VoluntarySeparation_NAICSJOLTS_929000_Unadjusted':
        'dcs:dc/w64n5dj6yqw62',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_000000_Adjusted':
        'dcs:dc/65psm7c8z7nv',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_000000_Unadjusted':
        'dcs:dc/5s7x0e64xn4tf',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS10_Adjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSTotalAllIndustries_Adjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS10_Unadjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSTotalAllIndustries_Unadjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_110099_Adjusted':
        'dcs:dc/vl9vt8hr76eeb',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_110099_Unadjusted':
        'dcs:dc/bvgtvc8dl1zz1',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS23_Adjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSConstruction_Adjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS23_Unadjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSConstruction_Unadjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_300000_Adjusted':
        'dcs:dc/k9er0x8cn8s26',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_300000_Unadjusted':
        'dcs:dc/y1dd8s96drq53',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_320000_Adjusted':
        'dcs:dc/hntf9whsdhwk8',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_320000_Unadjusted':
        'dcs:dc/td9mndke15n3f',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_340000_Adjusted':
        'dcs:dc/9clf6el5nv99c',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_340000_Unadjusted':
        'dcs:dc/kgrbkqph5rs53',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_400000_Adjusted':
        'dcs:dc/63n9d2e9sg5c5',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_400000_Unadjusted':
        'dcs:dc/mfqhzwv3cbykb',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS42_Adjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSWholesaleTrade_Adjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS42_Unadjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSWholesaleTrade_Unadjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS44_Adjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSRetailTrade_Adjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS44_Unadjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSRetailTrade_Unadjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_480099_Adjusted':
        'dcs:dc/jjct6j0cgc4h6',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_480099_Unadjusted':
        'dcs:dc/cq0vc4jk0542d',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS51_Adjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSInformation_Adjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS51_Unadjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSInformation_Unadjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_510099_Adjusted':
        'dcs:dc/cwsk4g52exnr9',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_510099_Unadjusted':
        'dcs:dc/x1st4jjq8qq5g',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS52_Adjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSFinanceInsurance_Adjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS52_Unadjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSFinanceInsurance_Unadjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS53_Adjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSRealEstateRentalLeasing_Adjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS53_Unadjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSRealEstateRentalLeasing_Unadjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_540099_Adjusted':
        'dcs:dc/xlh94y01hzjm3',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_540099_Unadjusted':
        'dcs:dc/8e8zsm1dm58h4',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_600000_Adjusted':
        'dcs:dc/rtcmf95wflxd9',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_600000_Unadjusted':
        'dcs:dc/b77d97hbyf923',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS61_Adjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSEducationalServices_Adjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS61_Unadjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSEducationalServices_Unadjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS62_Adjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSHealthCareSocialAssistance_Adjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS62_Unadjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSHealthCareSocialAssistance_Unadjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_700000_Adjusted':
        'dcs:dc/yp7rfd8j5dl2f',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_700000_Unadjusted':
        'dcs:dc/8gh37bm0sqjs9',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS71_Adjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSArtsEntertainmentRecreation_Adjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS71_Unadjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSArtsEntertainmentRecreation_Unadjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS72_Adjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSAccommodationFoodServices_Adjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS72_Unadjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSAccommodationFoodServices_Unadjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS81_Adjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSOtherServices_Adjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS81_Unadjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSOtherServices_Unadjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_900000_Adjusted':
        'dcs:dc/ez8mmnet718yh',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_900000_Unadjusted':
        'dcs:dc/h1me8gkbykc0b',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_910000_Adjusted':
        'dcs:dc/r2twx21lqtve9',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_910000_Unadjusted':
        'dcs:dc/6p03jdt47drk3',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS92_Adjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSPublicAdministration_Adjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICS92_Unadjusted':
        'dcs:Count_Worker_InvoluntarySeparation_NAICSPublicAdministration_Unadjusted',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_923000_Adjusted':
        'dcs:dc/6jwj9vtd0qtqg',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_923000_Unadjusted':
        'dcs:dc/e7k8s29jzrsff',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_929000_Adjusted':
        'dcs:dc/rxxgtx494t704',
    'dcs:Count_Worker_InvoluntarySeparation_NAICSJOLTS_929000_Unadjusted':
        'dcs:dc/ccy6f7pmr5cv9',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_000000_Adjusted':
        'dcs:dc/f1yrh54sfkhyb',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_000000_Unadjusted':
        'dcs:dc/5c560y5q8wlw9',
    'dcs:Count_Worker_OtherSeparation_NAICS10_Adjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSTotalAllIndustries_Adjusted',
    'dcs:Count_Worker_OtherSeparation_NAICS10_Unadjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSTotalAllIndustries_Unadjusted',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_110099_Adjusted':
        'dcs:dc/0hc95js8j5ztc',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_110099_Unadjusted':
        'dcs:dc/k9vd8z28ybqqf',
    'dcs:Count_Worker_OtherSeparation_NAICS23_Adjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSConstruction_Adjusted',
    'dcs:Count_Worker_OtherSeparation_NAICS23_Unadjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSConstruction_Unadjusted',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_300000_Adjusted':
        'dcs:dc/tlwdqrmg4ztzg',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_300000_Unadjusted':
        'dcs:dc/xmgxl9nqc0yf4',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_320000_Adjusted':
        'dcs:dc/nlwvrvtws5262',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_320000_Unadjusted':
        'dcs:dc/qenc9x1pg7wyh',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_340000_Adjusted':
        'dcs:dc/h9d1bpzjqvngc',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_340000_Unadjusted':
        'dcs:dc/s8l011erqcc67',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_400000_Adjusted':
        'dcs:dc/jgvnb3wkwh5xh',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_400000_Unadjusted':
        'dcs:dc/kvg4t0b4933b',
    'dcs:Count_Worker_OtherSeparation_NAICS42_Adjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSWholesaleTrade_Adjusted',
    'dcs:Count_Worker_OtherSeparation_NAICS42_Unadjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSWholesaleTrade_Unadjusted',
    'dcs:Count_Worker_OtherSeparation_NAICS44_Adjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSRetailTrade_Adjusted',
    'dcs:Count_Worker_OtherSeparation_NAICS44_Unadjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSRetailTrade_Unadjusted',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_480099_Adjusted':
        'dcs:dc/lwe5qqsxps4kh',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_480099_Unadjusted':
        'dcs:dc/vnhc36svjxkg7',
    'dcs:Count_Worker_OtherSeparation_NAICS51_Adjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSInformation_Adjusted',
    'dcs:Count_Worker_OtherSeparation_NAICS51_Unadjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSInformation_Unadjusted',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_510099_Adjusted':
        'dcs:dc/ew37qh0g26d9b',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_510099_Unadjusted':
        'dcs:dc/31l3he04l9ykc',
    'dcs:Count_Worker_OtherSeparation_NAICS52_Adjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSFinanceInsurance_Adjusted',
    'dcs:Count_Worker_OtherSeparation_NAICS52_Unadjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSFinanceInsurance_Unadjusted',
    'dcs:Count_Worker_OtherSeparation_NAICS53_Adjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSRealEstateRentalLeasing_Adjusted',
    'dcs:Count_Worker_OtherSeparation_NAICS53_Unadjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSRealEstateRentalLeasing_Unadjusted',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_540099_Adjusted':
        'dcs:dc/l72wcfgffchec',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_540099_Unadjusted':
        'dcs:dc/wgn9xjcwvlt3c',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_600000_Adjusted':
        'dcs:dc/z4nnqncltmf1f',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_600000_Unadjusted':
        'dcs:dc/psdnx4yc73phc',
    'dcs:Count_Worker_OtherSeparation_NAICS61_Adjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSEducationalServices_Adjusted',
    'dcs:Count_Worker_OtherSeparation_NAICS61_Unadjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSEducationalServices_Unadjusted',
    'dcs:Count_Worker_OtherSeparation_NAICS62_Adjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSHealthCareSocialAssistance_Adjusted',
    'dcs:Count_Worker_OtherSeparation_NAICS62_Unadjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSHealthCareSocialAssistance_Unadjusted',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_700000_Adjusted':
        'dcs:dc/ptf4g66sr1gdh',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_700000_Unadjusted':
        'dcs:dc/g6eq21pjhbh9f',
    'dcs:Count_Worker_OtherSeparation_NAICS71_Adjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSArtsEntertainmentRecreation_Adjusted',
    'dcs:Count_Worker_OtherSeparation_NAICS71_Unadjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSArtsEntertainmentRecreation_Unadjusted',
    'dcs:Count_Worker_OtherSeparation_NAICS72_Adjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSAccommodationFoodServices_Adjusted',
    'dcs:Count_Worker_OtherSeparation_NAICS72_Unadjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSAccommodationFoodServices_Unadjusted',
    'dcs:Count_Worker_OtherSeparation_NAICS81_Adjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSOtherServices_Adjusted',
    'dcs:Count_Worker_OtherSeparation_NAICS81_Unadjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSOtherServices_Unadjusted',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_900000_Adjusted':
        'dcs:dc/z0zgdmlnv3rjf',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_900000_Unadjusted':
        'dcs:dc/dhwv6jqezlje3',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_910000_Adjusted':
        'dcs:dc/7pmmv7b82t6vf',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_910000_Unadjusted':
        'dcs:dc/2h9ymbyfdppe',
    'dcs:Count_Worker_OtherSeparation_NAICS92_Adjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSPublicAdministration_Adjusted',
    'dcs:Count_Worker_OtherSeparation_NAICS92_Unadjusted':
        'dcs:Count_Worker_OtherSeparation_NAICSPublicAdministration_Unadjusted',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_923000_Adjusted':
        'dcs:dc/tel2dqr3h05d8',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_923000_Unadjusted':
        'dcs:dc/zxeg647ygtpn3',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_929000_Adjusted':
        'dcs:dc/6dpj1hqlb3s34',
    'dcs:Count_Worker_OtherSeparation_NAICSJOLTS_929000_Unadjusted':
        'dcs:dc/z6xd1lb3yd0q2'
}
