# This is a radio button selection and the key words are as per the website
SCHOOL = ["PublicSchool"]

# Default columns selected for the data export.
DEFAULT_COLUMNS_SELECTED = ["staticName", "defaultName"]

# List of columns specifically for Public Schools data export.
PUBLIC_COLUMNS = [
    "State Name [Public School]", "State Abbr [Public School]",
    "School Name [Public School]", "School ID - NCES Assigned [Public School]",
    "Agency Name [Public School]", "Agency ID - NCES Assigned [Public School]",
    "County Number [Public School]", "ANSI/FIPS State Code [Public School]",
    "Location Address 1 [Public School]", "Location City [Public School]",
    "Location ZIP [Public School]", "Location ZIP4 [Public School]",
    "Phone Number [Public School]",
    "National School Lunch Program [Public School]",
    "Magnet School [Public School]", "State School ID [Public School]",
    "School Type [Public School]", "Title I School Status [Public School]",
    "Charter School [Public School]", "Locale [Public School]",
    "Latitude [Public School]", "Longitude [Public School]",
    "Lowest Grade Offered [Public School]",
    "Highest Grade Offered [Public School]",
    "School Level (SY 2017-18 onward) [Public School]",
    "School Level [Public School]",
    "Total Students, All Grades (Excludes AE) [Public School]",
    "Total Students, All Grades (Includes AE) [Public School]",
    "Free Lunch Eligible [Public School]",
    "Direct Certification [Public School]",
    "Reduced-price Lunch Eligible Students [Public School]",
    "Free and Reduced Lunch Students [Public School]",
    "Grades 1-8 Students [Public School]",
    "Grades 9-12 Students [Public School]",
    "Prekindergarten Students [Public School]",
    "Kindergarten Students [Public School]", "Grade 1 Students [Public School]",
    "Grade 2 Students [Public School]", "Grade 3 Students [Public School]",
    "Grade 4 Students [Public School]", "Grade 5 Students [Public School]",
    "Grade 6 Students [Public School]", "Grade 7 Students [Public School]",
    "Grade 8 Students [Public School]", "Grade 9 Students [Public School]",
    "Grade 10 Students [Public School]", "Grade 11 Students [Public School]",
    "Grade 12 Students [Public School]", "Grade 13 Students [Public School]",
    "Ungraded Students [Public School]",
    "Adult Education Students [Public School]", "Male Students [Public School]",
    "Female Students [Public School]",
    "American Indian/Alaska Native Students [Public School]",
    "Asian or Asian/Pacific Islander Students [Public School]",
    "Hispanic Students [Public School]",
    "Black or African American Students [Public School]",
    "White Students [Public School]",
    "Nat. Hawaiian or Other Pacific Isl. Students [Public School]",
    "Two or More Races Students [Public School]",
    "Total Race/Ethnicity [Public School]",
    "American Indian/Alaska Native - male [Public School]",
    "American Indian/Alaska Native - female [Public School]",
    "Asian or Asian/Pacific Islander - male [Public School]",
    "Asian or Asian/Pacific Islander - female [Public School]",
    "Hispanic - female [Public School]", "Hispanic - male [Public School]",
    "Black or African American - male [Public School]",
    "Black or African American - female [Public School]",
    "White - male [Public School]", "White - female [Public School]",
    "Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Two or More Races - male [Public School]",
    "Two or More Races - female [Public School]",
    "Prekindergarten Students - male [Public School]",
    "Prekindergarten Students - female [Public School]",
    "Kindergarten Students - male [Public School]",
    "Kindergarten Students - female [Public School]",
    "Grade 1 Students - male [Public School]",
    "Grade 1 Students - female [Public School]",
    "Grade 2 Students - male [Public School]",
    "Grade 2 Students - female [Public School]",
    "Grade 3 Students - male [Public School]",
    "Grade 3 Students - female [Public School]",
    "Grade 4 Students - male [Public School]",
    "Grade 4 Students - female [Public School]",
    "Grade 5 Students - male [Public School]",
    "Grade 5 Students - female [Public School]",
    "Grade 6 Students - male [Public School]",
    "Grade 6 Students - female [Public School]",
    "Grade 7 Students - male [Public School]",
    "Grade 7 Students - female [Public School]",
    "Grade 8 Students - male [Public School]",
    "Grade 8 Students - female [Public School]",
    "Grade 9 Students - male [Public School]",
    "Grade 9 Students - female [Public School]",
    "Grade 10 Students - male [Public School]",
    "Grade 10 Students - female [Public School]",
    "Grade 11 Students - male [Public School]",
    "Grade 11 Students - female [Public School]",
    "Grade 12 Students - male [Public School]",
    "Grade 12 Students - female [Public School]",
    "Grade 13 Students - male [Public School]",
    "Grade 13 Students - female [Public School]",
    "Ungraded Students - male [Public School]",
    "Ungraded Students - female [Public School]",
    "Adult Education Students - male [Public School]",
    "Adult Education Students - female [Public School]",
    "Prekindergarten Students - American Indian/Alaska Native [Public School]",
    "Prekindergarten Students - Asian or Asian/Pacific Islander [Public School]",
    "Prekindergarten Students - Hispanic [Public School]",
    "Prekindergarten Students - Black or African American [Public School]",
    "Prekindergarten Students - White [Public School]",
    "Prekindergarten Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Prekindergarten Students, Two or More Races [Public School]",
    "Kindergarten Students - American Indian/Alaska Native [Public School]",
    "Kindergarten Students - Asian or Asian/Pacific Islander [Public School]",
    "Kindergarten Students - Hispanic [Public School]",
    "Kindergarten Students - Black or African American [Public School]",
    "Kindergarten Students, White [Public School]",
    "Kindergarten Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Kindergarten Students, Two or More Races [Public School]",
    "Grade 1 Students - American Indian/Alaska Native [Public School]",
    "Grade 1 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 1 Students - Hispanic [Public School]",
    "Grade 1 Students - Black or African American [Public School]",
    "Grade 1 Students - White [Public School]",
    "Grade 1 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 1 Students - Two or More Races [Public School]",
    "Grade 2 Students - American Indian/Alaska Native [Public School]",
    "Grade 2 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 2 Students - Hispanic [Public School]",
    "Grade 2 Students - Black or African American [Public School]",
    "Grade 2 Students - White [Public School]",
    "Grade 2 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 2 Students - Two or More Races [Public School]",
    "Grade 3 Students - American Indian/Alaska Native [Public School]",
    "Grade 3 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 3 Students - Hispanic [Public School]",
    "Grade 3 Students - Black or African American [Public School]",
    "Grade 3 Students - White [Public School]",
    "Grade 3 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 3 Students - Two or More Races [Public School]",
    "Grade 4 Students - American Indian/Alaska Native [Public School]",
    "Grade 4 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 4 Students - Hispanic [Public School]",
    "Grade 4 Students - Black or African American [Public School]",
    "Grade 4 Students - White [Public School]",
    "Grade 4 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 4 Students - Two or More Races [Public School]",
    "Grade 5 Students - American Indian/Alaska Native [Public School]",
    "Grade 5 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 5 Students - Hispanic [Public School]",
    "Grade 5 Students - Black or African American [Public School]",
    "Grade 5 Students - White [Public School]",
    "Grade 5 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 5 Students - Two or More Races [Public School]",
    "Grade 6 Students - American Indian/Alaska Native [Public School]",
    "Grade 6 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 6 Students - Hispanic [Public School]",
    "Grade 6 Students - Black or African American [Public School]",
    "Grade 6 Students - White [Public School]",
    "Grade 6 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 6 Students - Two or More Races [Public School]",
    "Grade 7 Students - American Indian/Alaska Native [Public School]",
    "Grade 7 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 7 Students - Hispanic [Public School]",
    "Grade 7 Students - Black or African American [Public School]",
    "Grade 7 Students - White [Public School]",
    "Grade 7 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 7 Students - Two or More Races [Public School]",
    "Grade 8 Students - American Indian/Alaska Native [Public School]",
    "Grade 8 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 8 Students - Hispanic [Public School]",
    "Grade 8 Students - Black or African American [Public School]",
    "Grade 8 Students - White [Public School]",
    "Grade 8 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 8 Students - Two or More Races [Public School]",
    "Grade 9 Students - American Indian/Alaska Native [Public School]",
    "Grade 9 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 9 Students - Hispanic [Public School]",
    "Grade 9 Students - Black or African American [Public School]",
    "Grade 9 Students - White [Public School]",
    "Grade 9 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 9 Students - Two or More Races [Public School]",
    "Grade 10 Students - American Indian/Alaska Native [Public School]",
    "Grade 10 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 10 Students - Hispanic [Public School]",
    "Grade 10 Students - Black or African American [Public School]",
    "Grade 10 Students - White [Public School]",
    "Grade 10 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 10 Students - Two or More Races [Public School]",
    "Grade 11 Students - American Indian/Alaska Native [Public School]",
    "Grade 11 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 11 Students - Hispanic [Public School]",
    "Grade 11 Students - Black or African American [Public School]",
    "Grade 11 Students - White [Public School]",
    "Grade 11 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 11 Students - Two or More Races [Public School]",
    "Grade 12 Students - American Indian/Alaska Native [Public School]",
    "Grade 12 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 12 Students - Hispanic [Public School]",
    "Grade 12 Students - Black or African American [Public School]",
    "Grade 12 Students - White [Public School]",
    "Grade 12 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 12 Students - Two or More Races [Public School]",
    "Grade 13 Students - American Indian/Alaska Native [Public School]",
    "Grade 13 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 13 Students - Hispanic [Public School]",
    "Grade 13 Students - Black or African American [Public School]",
    "Grade 13 Students - White [Public School]",
    "Grade 13 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 13 Students - Two or More Races [Public School]",
    "Ungraded Students - American Indian/Alaska Native [Public School]",
    "Ungraded Students - Asian or Asian/Pacific Islander [Public School]",
    "Ungraded Students - Hispanic [Public School]",
    "Ungraded Students - Black or African American [Public School]",
    "Ungraded Students - White [Public School]",
    "Ungraded Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Ungraded Students - Two or More Races [Public School]",
    "Adult Education Students - American Indian/Alaska Native [Public School]",
    "Adult Education Students - Asian or Asian/Pacific Islander [Public School]",
    "Adult Education Students - Hispanic [Public School]",
    "Adult Education Students - Black or African American [Public School]",
    "Adult Education Students - White [Public School]",
    "Adult Education - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Adult Education Students - Two or More Races [Public School]",
    "Prekindergarten Students - American Indian/Alaska Native - male [Public School]",
    "Prekindergarten Students - American Indian/Alaska Native - female [Public School]",
    "Prekindergarten Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Prekindergarten Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Prekindergarten Students - Hispanic - male [Public School]",
    "Prekindergarten Students - Hispanic - female [Public School]",
    "Prekindergarten Students - Black or African American - male [Public School]",
    "Prekindergarten Students - Black or African American - female [Public School]",
    "Prekindergarten Students - White - male [Public School]",
    "Prekindergarten Students - White - female [Public School]",
    "Prekindergarten Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Prekindergarten Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Prekindergarten Students - Two or More Races - male [Public School]",
    "Prekindergarten Students - Two or More Races - female [Public School]",
    "Kindergarten Students - American Indian/Alaska Native - male [Public School]",
    "Kindergarten Students - American Indian/Alaska Native - female [Public School]",
    "Kindergarten Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Kindergarten Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Kindergarten Students - Hispanic - male [Public School]",
    "Kindergarten Students - Hispanic - female [Public School]",
    "Kindergarten Students - Black or African American - male [Public School]",
    "Kindergarten Students - Black or African American - female [Public School]",
    "Kindergarten Students - White - male [Public School]",
    "Kindergarten Students - White - female [Public School]",
    "Kindergarten Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Kindergarten Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Kindergarten Students - Two or More Races - male [Public School]",
    "Kindergarten Students - Two or More Races - female [Public School]",
    "Grade 1 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 1 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 1 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 1 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 1 Students - Hispanic - male [Public School]",
    "Grade 1 Students - Hispanic - female [Public School]",
    "Grade 1 Students - Black or African American - male [Public School]",
    "Grade 1 Students - Black or African American - female [Public School]",
    "Grade 1 Students - White - male [Public School]",
    "Grade 1 Students - White - female [Public School]",
    "Grade 1 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 1 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 1 Students - Two or More Races - male [Public School]",
    "Grade 1 Students - Two or More Races - female [Public School]",
    "Grade 2 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 2 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 2 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 2 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 2 Students - Hispanic - male [Public School]",
    "Grade 2 Students - Hispanic - female [Public School]",
    "Grade 2 Students - Black or African American - male [Public School]",
    "Grade 2 Students - Black or African American - female [Public School]",
    "Grade 2 Students - White - male [Public School]",
    "Grade 2 Students - White - female [Public School]",
    "Grade 2 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 2 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 2 Students - Two or More Races - male [Public School]",
    "Grade 2 Students - Two or More Races - female [Public School]",
    "Grade 3 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 3 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 3 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 3 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 3 Students - Hispanic - male [Public School]",
    "Grade 3 Students - Hispanic - female [Public School]",
    "Grade 3 Students - Black or African American - male [Public School]",
    "Grade 3 Students - Black or African American - female [Public School]",
    "Grade 3 Students - White - male [Public School]",
    "Grade 3 Students - White - female [Public School]",
    "Grade 3 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 3 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 3 Students - Two or More Races - male [Public School]",
    "Grade 3 Students - Two or More Races - female [Public School]",
    "Grade 4 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 4 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 4 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 4 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 4 Students - Hispanic - male [Public School]",
    "Grade 4 Students - Hispanic - female [Public School]",
    "Grade 4 Students - Black or African American - male [Public School]",
    "Grade 4 Students - Black or African American - female [Public School]",
    "Grade 4 Students - White - male [Public School]",
    "Grade 4 Students - White - female [Public School]",
    "Grade 4 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 4 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 4 Students - Two or More Races - male [Public School]",
    "Grade 4 Students - Two or More Races - female [Public School]",
    "Grade 5 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 5 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 5 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 5 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 5 Students - Hispanic - male [Public School]",
    "Grade 5 Students - Hispanic - female [Public School]",
    "Grade 5 Students - Black or African American - male [Public School]",
    "Grade 5 Students - Black or African American - female [Public School]",
    "Grade 5 Students - White - male [Public School]",
    "Grade 5 Students - White - female [Public School]",
    "Grade 5 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 5 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 5 Students - Two or More Races - male [Public School]",
    "Grade 5 Students - Two or More Races - female [Public School]",
    "Grade 6 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 6 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 6 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 6 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 6 Students - Hispanic - male [Public School]",
    "Grade 6 Students - Hispanic - female [Public School]",
    "Grade 6 Students - Black or African American - male [Public School]",
    "Grade 6 Students - Black or African American - female [Public School]",
    "Grade 6 Students - White - male [Public School]",
    "Grade 6 Students - White - female [Public School]",
    "Grade 6 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 6 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 6 Students- Two or More Races - male [Public School]",
    "Grade 6 Students - Two or More Races - female [Public School]",
    "Grade 7 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 7 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 7 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 7 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 7 Students - Hispanic - male [Public School]",
    "Grade 7 Students - Hispanic - female [Public School]",
    "Grade 7 Students - Black or African American - male [Public School]",
    "Grade 7 Students - Black or African American - female [Public School]",
    "Grade 7 Students - White - male [Public School]",
    "Grade 7 Students - White - female [Public School]",
    "Grade 7 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 7 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 7 Students - Two or More Races - male [Public School]",
    "Grade 7 Students - Two or More Races - female [Public School]",
    "Grade 8 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 8 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 8 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 8 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 8 Students- Hispanic - male [Public School]",
    "Grade 8 Students - Hispanic - female [Public School]",
    "Grade 8 Students - Black or African American - male [Public School]",
    "Grade 8 Students - Black or African American - female [Public School]",
    "Grade 8 Students - White - male [Public School]",
    "Grade 8 Students - White - female [Public School]",
    "Grade 8 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 8 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 8 Students - Two or More Races - male [Public School]",
    "Grade 8 Students - Two or More Races - female [Public School]",
    "Grade 9 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 9 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 9 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 9 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 9 Students - Hispanic - male [Public School]",
    "Grade 9 Students - Hispanic - female [Public School]",
    "Grade 9 Students - Black or African American - male [Public School]",
    "Grade 9 Students - Black or African American - female [Public School]",
    "Grade 9 Students - White - male [Public School]",
    "Grade 9 Students - White - female [Public School]",
    "Grade 9 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 9 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 9 Students - Two or More Races - male [Public School]",
    "Grade 9 Students - Two or More Races - female [Public School]",
    "Grade 10 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 10 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 10 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 10 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 10 Students - Hispanic - male [Public School]",
    "Grade 10 Students - Hispanic - female [Public School]",
    "Grade 10 Students - Black or African American - male [Public School]",
    "Grade 10 Students - Black or African American - female [Public School]",
    "Grade 10 Students - White - male [Public School]",
    "Grade 10 Students - White - female [Public School]",
    "Grade 10 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 10 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 10 Students - Two or More Races - male [Public School]",
    "Grade 10 Students - Two or More Races - female [Public School]",
    "Grade 11 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 11 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 11 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 11 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 11 Students - Hispanic - male [Public School]",
    "Grade 11 Students - Hispanic - female [Public School]",
    "Grade 11 Students - Black or African American - male [Public School]",
    "Grade 11 Students - Black or African American - female [Public School]",
    "Grade 11 Students - White - male [Public School]",
    "Grade 11 Students - White - female [Public School]",
    "Grade 11 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 11 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 11 Students - Two or More Races - male [Public School]",
    "Grade 11 Students - Two or More Races - female [Public School]",
    "Grade 12 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 12 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 12 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 12 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 12 Students - Hispanic - male [Public School]",
    "Grade 12 Students - Hispanic - female [Public School]",
    "Grade 12 Students - Black or African American - male [Public School]",
    "Grade 12 Students - Black or African American - female [Public School]",
    "Grade 12 Students - White - male [Public School]",
    "Grade 12 Students - White - female [Public School]",
    "Grade 12 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 12 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 12 Students - Two or More Races - male [Public School]",
    "Grade 12 Students - Two or More Races - female [Public School]",
    "Grade 13 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 13 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 13 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 13 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 13 Students - Hispanic - male [Public School]",
    "Grade 13 Students - Hispanic - female [Public School]",
    "Grade 13 Students - Black or African American - male [Public School]",
    "Grade 13 Students - Black or African American - female [Public School]",
    "Grade 13 Students - White - male [Public School]",
    "Grade 13 Students - White - female [Public School]",
    "Grade 13 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 13 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 13 Students - Two or More Races - male [Public School]",
    "Grade 13 Students - Two or More Races - female [Public School]",
    "Ungraded Students - American Indian/Alaska Native - male [Public School]",
    "Ungraded Students - American Indian/Alaska Native - female [Public School]",
    "Ungraded Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Ungraded Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Ungraded Students - Hispanic - male [Public School]",
    "Ungraded Students - Hispanic - female [Public School]",
    "Ungraded Students - Black or African American - male [Public School]",
    "Ungraded Students - Black or African American - female [Public School]",
    "Ungraded Students - White - male [Public School]",
    "Ungraded Students - White - female [Public School]",
    "Ungraded Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Ungraded Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Ungraded Students - Two or More Races - male [Public School]",
    "Ungraded Students - Two or More Races - female [Public School]",
    "Adult Education Students - American Indian/Alaska Native - male [Public School]",
    "Adult Education Students - American Indian/Alaska Native - female [Public School]",
    "Adult Education Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Adult Education Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Adult Education Students - Hispanic - male [Public School]",
    "Adult Education Students - Hispanic - female [Public School]",
    "Adult Education Students - Black or African American - male [Public School]",
    "Adult Education Students - Black or African American - female [Public School]",
    "Adult Education Students - White - male [Public School]",
    "Adult Education Students - White - female [Public School]",
    "Adult Education Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Adult Education Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Adult Education Students - Two or More Races - male [Public School]",
    "Adult Education Students - Two or More Races - female [Public School]",
    "Full-Time Equivalent (FTE) Teachers [Public School]",
    "Pupil/Teacher Ratio [Public School]"
]

KEY_COLUMNS_PUBLIC = ["13392"]
KEY_COLUMNS_PRIVATE = ["13391"]
KEY_COLUMNS_DISTRICT = ["13393"]
