# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is a radio button selection and the key words are as per the website
SCHOOL = ["PublicSchool"]
# Default columns selected for the data export.
DEFAULT_COLUMNS_SELECTED = ["staticName", "defaultName"]

# List of columns specifically for Public Schools data export.
PRIVATE_COLUMNS = [
    "State Name [Private School]", "ANSI/FIPS State Code [Private School]",
    "Private School Name [Private School]",
    "School ID - NCES Assigned [Private School]",
    "County Name [Private School]", "ANSI/FIPS County Code [Private School]",
    "Phone Number [Private School]", "Physical Address [Private School]",
    "City [Private School]", "ZIP [Private School]", "ZIP + 4 [Private School]",
    "Lowest Grade Taught [Private School]",
    "Highest Grade Taught [Private School]", "Coeducational [Private School]",
    "School Type [Private School]", "School Level [Private School]",
    "School's Religious Affiliation or Orientation [Private School]",
    "School Community Type [Private School]",
    "Total Students (Ungraded & PK-12) [Private School]",
    "Total Students (Ungraded & K-12) [Private School]",
    "Prekindergarten and Kindergarten Students [Private School]",
    "Grades 1-8 Students [Private School]",
    "Grades 9-12 Students [Private School]",
    "Prekindergarten Students [Private School]",
    "Kindergarten Students [Private School]",
    "Grade 1 Students [Private School]", "Grade 2 Students [Private School]",
    "Grade 3 Students [Private School]", "Grade 4 Students [Private School]",
    "Grade 5 Students [Private School]", "Grade 6 Students [Private School]",
    "Grade 7 Students [Private School]", "Grade 8 Students [Private School]",
    "Grade 9 Students [Private School]", "Grade 10 Students [Private School]",
    "Grade 11 Students [Private School]", "Grade 12 Students [Private School]",
    "Ungraded Students [Private School]",
    "Pupil/Teacher Ratio [Private School]",
    "Full-Time Equivalent (FTE) Teachers [Private School]",
    "American Indian/Alaska Native Students [Private School]",
    "Percentage of American Indian/Alaska Native Students [Private School]",
    "Asian or Asian/Pacific Islander Students [Private School]",
    "Percentage of Asian or Asian/Pacific Islander Students [Private School]",
    "Hispanic Students [Private School]",
    "Percentage of Hispanic Students [Private School]",
    "Black or African American Students [Private School]",
    "Percentage of Black Students [Private School]",
    "White Students [Private School]",
    "Percentage of White Students [Private School]",
    "Nat. Hawaiian or Other Pacific Isl. Students [Private School]",
    "Percentage of Nat. Hawaiian or Other Pacific Isl. Students [Private School]",
    "Two or More Races Students [Private School]",
    "Percentage of Two or More Races Students [Private School]",
    "State Abbr [Private School]", "Religious Orientation [Private School]"
]

PUBLIC_COLUMNS = [
    "State Name [Public School]", "State Abbr [Public School]",
    "School Name [Public School]",
    "School ID (12-digit) - NCES Assigned [Public School]",
    "Agency Name [Public School]", "Agency ID - NCES Assigned [Public School]",
    "County Number [Public School]", "ANSI/FIPS State Code [Public School]",
    "Location Address 1 [Public School]", "Location City [Public School]",
    "Location ZIP [Public School]", "Location ZIP4 [Public School]",
    "Phone Number [Public School]",
    "National School Lunch Program [Public School]",
    "Magnet School [Public School]", "State School ID [Public School]",
    "School Type [Public School]", "Title I School Status [Public School]",
    "Charter School [Public School]", "Locale [Public School]",
    "Latitude [Public School]", "Longitude [Public School]",
    "Lowest Grade Offered [Public School]",
    "Highest Grade Offered [Public School]",
    "School Level (SY 2017-18 onward) [Public School]",
    "School Level [Public School]",
    "Total Students, All Grades (Excludes AE) [Public School]",
    "Total Students, All Grades (Includes AE) [Public School]",
    "Free Lunch Eligible [Public School]",
    "Direct Certification [Public School]",
    "Reduced-price Lunch Eligible Students [Public School]",
    "Free and Reduced Lunch Students [Public School]",
    "Grades 1-8 Students [Public School]",
    "Grades 9-12 Students [Public School]",
    "Prekindergarten Students [Public School]",
    "Kindergarten Students [Public School]", "Grade 1 Students [Public School]",
    "Grade 2 Students [Public School]", "Grade 3 Students [Public School]",
    "Grade 4 Students [Public School]", "Grade 5 Students [Public School]",
    "Grade 6 Students [Public School]", "Grade 7 Students [Public School]",
    "Grade 8 Students [Public School]", "Grade 9 Students [Public School]",
    "Grade 10 Students [Public School]", "Grade 11 Students [Public School]",
    "Grade 12 Students [Public School]", "Grade 13 Students [Public School]",
    "Ungraded Students [Public School]",
    "Adult Education Students [Public School]", "Male Students [Public School]",
    "Female Students [Public School]",
    "American Indian/Alaska Native Students [Public School]",
    "Asian or Asian/Pacific Islander Students [Public School]",
    "Hispanic Students [Public School]",
    "Black or African American Students [Public School]",
    "White Students [Public School]",
    "Nat. Hawaiian or Other Pacific Isl. Students [Public School]",
    "Two or More Races Students [Public School]",
    "Total Race/Ethnicity [Public School]",
    "American Indian/Alaska Native - male [Public School]",
    "American Indian/Alaska Native - female [Public School]",
    "Asian or Asian/Pacific Islander - male [Public School]",
    "Asian or Asian/Pacific Islander - female [Public School]",
    "Hispanic - female [Public School]", "Hispanic - male [Public School]",
    "Black or African American - male [Public School]",
    "Black or African American - female [Public School]",
    "White - male [Public School]", "White - female [Public School]",
    "Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Two or More Races - male [Public School]",
    "Two or More Races - female [Public School]",
    "Prekindergarten Students - male [Public School]",
    "Prekindergarten Students - female [Public School]",
    "Kindergarten Students - male [Public School]",
    "Kindergarten Students - female [Public School]",
    "Grade 1 Students - male [Public School]",
    "Grade 1 Students - female [Public School]",
    "Grade 2 Students - male [Public School]",
    "Grade 2 Students - female [Public School]",
    "Grade 3 Students - male [Public School]",
    "Grade 3 Students - female [Public School]",
    "Grade 4 Students - male [Public School]",
    "Grade 4 Students - female [Public School]",
    "Grade 5 Students - male [Public School]",
    "Grade 5 Students - female [Public School]",
    "Grade 6 Students - male [Public School]",
    "Grade 6 Students - female [Public School]",
    "Grade 7 Students - male [Public School]",
    "Grade 7 Students - female [Public School]",
    "Grade 8 Students - male [Public School]",
    "Grade 8 Students - female [Public School]",
    "Grade 9 Students - male [Public School]",
    "Grade 9 Students - female [Public School]",
    "Grade 10 Students - male [Public School]",
    "Grade 10 Students - female [Public School]",
    "Grade 11 Students - male [Public School]",
    "Grade 11 Students - female [Public School]",
    "Grade 12 Students - male [Public School]",
    "Grade 12 Students - female [Public School]",
    "Grade 13 Students - male [Public School]",
    "Grade 13 Students - female [Public School]",
    "Ungraded Students - male [Public School]",
    "Ungraded Students - female [Public School]",
    "Adult Education Students - male [Public School]",
    "Adult Education Students - female [Public School]",
    "Prekindergarten Students - American Indian/Alaska Native [Public School]",
    "Prekindergarten Students - Asian or Asian/Pacific Islander [Public School]",
    "Prekindergarten Students - Hispanic [Public School]",
    "Prekindergarten Students - Black or African American [Public School]",
    "Prekindergarten Students - White [Public School]",
    "Prekindergarten Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Prekindergarten Students, Two or More Races [Public School]",
    "Kindergarten Students - American Indian/Alaska Native [Public School]",
    "Kindergarten Students - Asian or Asian/Pacific Islander [Public School]",
    "Kindergarten Students - Hispanic [Public School]",
    "Kindergarten Students - Black or African American [Public School]",
    "Kindergarten Students, White [Public School]",
    "Kindergarten Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Kindergarten Students, Two or More Races [Public School]",
    "Grade 1 Students - American Indian/Alaska Native [Public School]",
    "Grade 1 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 1 Students - Hispanic [Public School]",
    "Grade 1 Students - Black or African American [Public School]",
    "Grade 1 Students - White [Public School]",
    "Grade 1 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 1 Students - Two or More Races [Public School]",
    "Grade 2 Students - American Indian/Alaska Native [Public School]",
    "Grade 2 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 2 Students - Hispanic [Public School]",
    "Grade 2 Students - Black or African American [Public School]",
    "Grade 2 Students - White [Public School]",
    "Grade 2 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 2 Students - Two or More Races [Public School]",
    "Grade 3 Students - American Indian/Alaska Native [Public School]",
    "Grade 3 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 3 Students - Hispanic [Public School]",
    "Grade 3 Students - Black or African American [Public School]",
    "Grade 3 Students - White [Public School]",
    "Grade 3 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 3 Students - Two or More Races [Public School]",
    "Grade 4 Students - American Indian/Alaska Native [Public School]",
    "Grade 4 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 4 Students - Hispanic [Public School]",
    "Grade 4 Students - Black or African American [Public School]",
    "Grade 4 Students - White [Public School]",
    "Grade 4 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 4 Students - Two or More Races [Public School]",
    "Grade 5 Students - American Indian/Alaska Native [Public School]",
    "Grade 5 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 5 Students - Hispanic [Public School]",
    "Grade 5 Students - Black or African American [Public School]",
    "Grade 5 Students - White [Public School]",
    "Grade 5 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 5 Students - Two or More Races [Public School]",
    "Grade 6 Students - American Indian/Alaska Native [Public School]",
    "Grade 6 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 6 Students - Hispanic [Public School]",
    "Grade 6 Students - Black or African American [Public School]",
    "Grade 6 Students - White [Public School]",
    "Grade 6 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 6 Students - Two or More Races [Public School]",
    "Grade 7 Students - American Indian/Alaska Native [Public School]",
    "Grade 7 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 7 Students - Hispanic [Public School]",
    "Grade 7 Students - Black or African American [Public School]",
    "Grade 7 Students - White [Public School]",
    "Grade 7 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 7 Students - Two or More Races [Public School]",
    "Grade 8 Students - American Indian/Alaska Native [Public School]",
    "Grade 8 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 8 Students - Hispanic [Public School]",
    "Grade 8 Students - Black or African American [Public School]",
    "Grade 8 Students - White [Public School]",
    "Grade 8 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 8 Students - Two or More Races [Public School]",
    "Grade 9 Students - American Indian/Alaska Native [Public School]",
    "Grade 9 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 9 Students - Hispanic [Public School]",
    "Grade 9 Students - Black or African American [Public School]",
    "Grade 9 Students - White [Public School]",
    "Grade 9 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 9 Students - Two or More Races [Public School]",
    "Grade 10 Students - American Indian/Alaska Native [Public School]",
    "Grade 10 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 10 Students - Hispanic [Public School]",
    "Grade 10 Students - Black or African American [Public School]",
    "Grade 10 Students - White [Public School]",
    "Grade 10 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 10 Students - Two or More Races [Public School]",
    "Grade 11 Students - American Indian/Alaska Native [Public School]",
    "Grade 11 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 11 Students - Hispanic [Public School]",
    "Grade 11 Students - Black or African American [Public School]",
    "Grade 11 Students - White [Public School]",
    "Grade 11 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 11 Students - Two or More Races [Public School]",
    "Grade 12 Students - American Indian/Alaska Native [Public School]",
    "Grade 12 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 12 Students - Hispanic [Public School]",
    "Grade 12 Students - Black or African American [Public School]",
    "Grade 12 Students - White [Public School]",
    "Grade 12 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 12 Students - Two or More Races [Public School]",
    "Grade 13 Students - American Indian/Alaska Native [Public School]",
    "Grade 13 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 13 Students - Hispanic [Public School]",
    "Grade 13 Students - Black or African American [Public School]",
    "Grade 13 Students - White [Public School]",
    "Grade 13 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 13 Students - Two or More Races [Public School]",
    "Ungraded Students - American Indian/Alaska Native [Public School]",
    "Ungraded Students - Asian or Asian/Pacific Islander [Public School]",
    "Ungraded Students - Hispanic [Public School]",
    "Ungraded Students - Black or African American [Public School]",
    "Ungraded Students - White [Public School]",
    "Ungraded Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Ungraded Students - Two or More Races [Public School]",
    "Adult Education Students - American Indian/Alaska Native [Public School]",
    "Adult Education Students - Asian or Asian/Pacific Islander [Public School]",
    "Adult Education Students - Hispanic [Public School]",
    "Adult Education Students - Black or African American [Public School]",
    "Adult Education Students - White [Public School]",
    "Adult Education - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Adult Education Students - Two or More Races [Public School]",
    "Prekindergarten Students - American Indian/Alaska Native - male [Public School]",
    "Prekindergarten Students - American Indian/Alaska Native - female [Public School]",
    "Prekindergarten Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Prekindergarten Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Prekindergarten Students - Hispanic - male [Public School]",
    "Prekindergarten Students - Hispanic - female [Public School]",
    "Prekindergarten Students - Black or African American - male [Public School]",
    "Prekindergarten Students - Black or African American - female [Public School]",
    "Prekindergarten Students - White - male [Public School]",
    "Prekindergarten Students - White - female [Public School]",
    "Prekindergarten Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Prekindergarten Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Prekindergarten Students - Two or More Races - male [Public School]",
    "Prekindergarten Students - Two or More Races - female [Public School]",
    "Kindergarten Students - American Indian/Alaska Native - male [Public School]",
    "Kindergarten Students - American Indian/Alaska Native - female [Public School]",
    "Kindergarten Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Kindergarten Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Kindergarten Students - Hispanic - male [Public School]",
    "Kindergarten Students - Hispanic - female [Public School]",
    "Kindergarten Students - Black or African American - male [Public School]",
    "Kindergarten Students - Black or African American - female [Public School]",
    "Kindergarten Students - White - male [Public School]",
    "Kindergarten Students - White - female [Public School]",
    "Kindergarten Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Kindergarten Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Kindergarten Students - Two or More Races - male [Public School]",
    "Kindergarten Students - Two or More Races - female [Public School]",
    "Grade 1 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 1 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 1 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 1 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 1 Students - Hispanic - male [Public School]",
    "Grade 1 Students - Hispanic - female [Public School]",
    "Grade 1 Students - Black or African American - male [Public School]",
    "Grade 1 Students - Black or African American - female [Public School]",
    "Grade 1 Students - White - male [Public School]",
    "Grade 1 Students - White - female [Public School]",
    "Grade 1 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 1 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 1 Students - Two or More Races - male [Public School]",
    "Grade 1 Students - Two or More Races - female [Public School]",
    "Grade 2 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 2 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 2 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 2 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 2 Students - Hispanic - male [Public School]",
    "Grade 2 Students - Hispanic - female [Public School]",
    "Grade 2 Students - Black or African American - male [Public School]",
    "Grade 2 Students - Black or African American - female [Public School]",
    "Grade 2 Students - White - male [Public School]",
    "Grade 2 Students - White - female [Public School]",
    "Grade 2 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 2 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 2 Students - Two or More Races - male [Public School]",
    "Grade 2 Students - Two or More Races - female [Public School]",
    "Grade 3 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 3 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 3 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 3 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 3 Students - Hispanic - male [Public School]",
    "Grade 3 Students - Hispanic - female [Public School]",
    "Grade 3 Students - Black or African American - male [Public School]",
    "Grade 3 Students - Black or African American - female [Public School]",
    "Grade 3 Students - White - male [Public School]",
    "Grade 3 Students - White - female [Public School]",
    "Grade 3 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 3 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 3 Students - Two or More Races - male [Public School]",
    "Grade 3 Students - Two or More Races - female [Public School]",
    "Grade 4 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 4 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 4 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 4 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 4 Students - Hispanic - male [Public School]",
    "Grade 4 Students - Hispanic - female [Public School]",
    "Grade 4 Students - Black or African American - male [Public School]",
    "Grade 4 Students - Black or African American - female [Public School]",
    "Grade 4 Students - White - male [Public School]",
    "Grade 4 Students - White - female [Public School]",
    "Grade 4 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 4 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 4 Students - Two or More Races - male [Public School]",
    "Grade 4 Students - Two or More Races - female [Public School]",
    "Grade 5 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 5 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 5 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 5 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 5 Students - Hispanic - male [Public School]",
    "Grade 5 Students - Hispanic - female [Public School]",
    "Grade 5 Students - Black or African American - male [Public School]",
    "Grade 5 Students - Black or African American - female [Public School]",
    "Grade 5 Students - White - male [Public School]",
    "Grade 5 Students - White - female [Public School]",
    "Grade 5 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 5 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 5 Students - Two or More Races - male [Public School]",
    "Grade 5 Students - Two or More Races - female [Public School]",
    "Grade 6 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 6 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 6 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 6 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 6 Students - Hispanic - male [Public School]",
    "Grade 6 Students - Hispanic - female [Public School]",
    "Grade 6 Students - Black or African American - male [Public School]",
    "Grade 6 Students - Black or African American - female [Public School]",
    "Grade 6 Students - White - male [Public School]",
    "Grade 6 Students - White - female [Public School]",
    "Grade 6 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 6 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 6 Students- Two or More Races - male [Public School]",
    "Grade 6 Students - Two or More Races - female [Public School]",
    "Grade 7 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 7 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 7 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 7 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 7 Students - Hispanic - male [Public School]",
    "Grade 7 Students - Hispanic - female [Public School]",
    "Grade 7 Students - Black or African American - male [Public School]",
    "Grade 7 Students - Black or African American - female [Public School]",
    "Grade 7 Students - White - male [Public School]",
    "Grade 7 Students - White - female [Public School]",
    "Grade 7 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 7 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 7 Students - Two or More Races - male [Public School]",
    "Grade 7 Students - Two or More Races - female [Public School]",
    "Grade 8 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 8 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 8 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 8 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 8 Students- Hispanic - male [Public School]",
    "Grade 8 Students - Hispanic - female [Public School]",
    "Grade 8 Students - Black or African American - male [Public School]",
    "Grade 8 Students - Black or African American - female [Public School]",
    "Grade 8 Students - White - male [Public School]",
    "Grade 8 Students - White - female [Public School]",
    "Grade 8 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 8 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 8 Students - Two or More Races - male [Public School]",
    "Grade 8 Students - Two or More Races - female [Public School]",
    "Grade 9 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 9 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 9 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 9 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 9 Students - Hispanic - male [Public School]",
    "Grade 9 Students - Hispanic - female [Public School]",
    "Grade 9 Students - Black or African American - male [Public School]",
    "Grade 9 Students - Black or African American - female [Public School]",
    "Grade 9 Students - White - male [Public School]",
    "Grade 9 Students - White - female [Public School]",
    "Grade 9 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 9 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 9 Students - Two or More Races - male [Public School]",
    "Grade 9 Students - Two or More Races - female [Public School]",
    "Grade 10 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 10 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 10 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 10 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 10 Students - Hispanic - male [Public School]",
    "Grade 10 Students - Hispanic - female [Public School]",
    "Grade 10 Students - Black or African American - male [Public School]",
    "Grade 10 Students - Black or African American - female [Public School]",
    "Grade 10 Students - White - male [Public School]",
    "Grade 10 Students - White - female [Public School]",
    "Grade 10 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 10 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 10 Students - Two or More Races - male [Public School]",
    "Grade 10 Students - Two or More Races - female [Public School]",
    "Grade 11 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 11 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 11 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 11 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 11 Students - Hispanic - male [Public School]",
    "Grade 11 Students - Hispanic - female [Public School]",
    "Grade 11 Students - Black or African American - male [Public School]",
    "Grade 11 Students - Black or African American - female [Public School]",
    "Grade 11 Students - White - male [Public School]",
    "Grade 11 Students - White - female [Public School]",
    "Grade 11 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 11 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 11 Students - Two or More Races - male [Public School]",
    "Grade 11 Students - Two or More Races - female [Public School]",
    "Grade 12 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 12 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 12 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 12 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 12 Students - Hispanic - male [Public School]",
    "Grade 12 Students - Hispanic - female [Public School]",
    "Grade 12 Students - Black or African American - male [Public School]",
    "Grade 12 Students - Black or African American - female [Public School]",
    "Grade 12 Students - White - male [Public School]",
    "Grade 12 Students - White - female [Public School]",
    "Grade 12 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 12 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 12 Students - Two or More Races - male [Public School]",
    "Grade 12 Students - Two or More Races - female [Public School]",
    "Grade 13 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 13 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 13 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 13 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 13 Students - Hispanic - male [Public School]",
    "Grade 13 Students - Hispanic - female [Public School]",
    "Grade 13 Students - Black or African American - male [Public School]",
    "Grade 13 Students - Black or African American - female [Public School]",
    "Grade 13 Students - White - male [Public School]",
    "Grade 13 Students - White - female [Public School]",
    "Grade 13 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 13 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 13 Students - Two or More Races - male [Public School]",
    "Grade 13 Students - Two or More Races - female [Public School]",
    "Ungraded Students - American Indian/Alaska Native - male [Public School]",
    "Ungraded Students - American Indian/Alaska Native - female [Public School]",
    "Ungraded Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Ungraded Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Ungraded Students - Hispanic - male [Public School]",
    "Ungraded Students - Hispanic - female [Public School]",
    "Ungraded Students - Black or African American - male [Public School]",
    "Ungraded Students - Black or African American - female [Public School]",
    "Ungraded Students - White - male [Public School]",
    "Ungraded Students - White - female [Public School]",
    "Ungraded Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Ungraded Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Ungraded Students - Two or More Races - male [Public School]",
    "Ungraded Students - Two or More Races - female [Public School]",
    "Adult Education Students - American Indian/Alaska Native - male [Public School]",
    "Adult Education Students - American Indian/Alaska Native - female [Public School]",
    "Adult Education Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Adult Education Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Adult Education Students - Hispanic - male [Public School]",
    "Adult Education Students - Hispanic - female [Public School]",
    "Adult Education Students - Black or African American - male [Public School]",
    "Adult Education Students - Black or African American - female [Public School]",
    "Adult Education Students - White - male [Public School]",
    "Adult Education Students - White - female [Public School]",
    "Adult Education Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Adult Education Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Adult Education Students - Two or More Races - male [Public School]",
    "Adult Education Students - Two or More Races - female [Public School]",
    "Full-Time Equivalent (FTE) Teachers [Public School]",
    "Pupil/Teacher Ratio [Public School]"
]

DISTRICT_COLUMNS = [
    "State Abbr [District]", "Agency Name [District]",
    "Agency ID - NCES Assigned [District]", "County Number [District]",
    "ANSI/FIPS State Code [District]", "Location Address 1 [District]",
    "Location ZIP [District]", "Location City [District]",
    "Location ZIP4 [District]", "Lowest Grade Offered [District]",
    "Highest Grade Offered [District]", "Locale [District]",
    "State Agency ID [District]", "Latitude [District]", "Longitude [District]",
    "Phone Number [District]",
    "Total Students, All Grades (Excludes AE) [District]",
    "Total Students, All Grades (Includes AE) [District]",
    "Grades 1-8 Students [District]", "Grades 9-12 Students [District]",
    "Prekindergarten Students [District]", "Kindergarten Students [District]",
    "Grade 1 Students [District]", "Grade 2 Students [District]",
    "Grade 3 Students [District]", "Grade 4 Students [District]",
    "Grade 5 Students [District]", "Grade 6 Students [District]",
    "Grade 7 Students [District]", "Grade 8 Students [District]",
    "Grade 9 Students [District]", "Grade 10 Students [District]",
    "Grade 11 Students [District]", "Grade 12 Students [District]",
    "Grade 13 Students [District]", "Ungraded Students [District]",
    "Adult Education Students [District]", "Male Students [District]",
    "Female Students [District]",
    "American Indian/Alaska Native Students [District]",
    "Asian or Asian/Pacific Islander Students [District]",
    "Hispanic Students [District]",
    "Black or African American Students [District]",
    "White Students [District]",
    "Nat. Hawaiian or Other Pacific Isl. Students [District]",
    "Two or More Races Students [District]", "Total Race/Ethnicity [District]",
    "American Indian/Alaska Native - male [District]",
    "American Indian/Alaska Native - female [District]",
    "Asian or Asian/Pacific Islander - male [District]",
    "Asian or Asian/Pacific Islander - female [District]",
    "Hispanic - male [District]", "Hispanic - female [District]",
    "Black or African American - male [District]",
    "Black or African American - female [District]", "White - male [District]",
    "White - female [District]",
    "Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Two or More Races - male [District]",
    "Two or More Races - female [District]",
    "Prekindergarten Students - male [District]",
    "Prekindergarten Students - female [District]",
    "Kindergarten Students - male [District]",
    "Kindergarten Students - female [District]",
    "Grade 1 Students - male [District]",
    "Grade 1 Students - female [District]",
    "Grade 2 Students - male [District]",
    "Grade 2 Students - female [District]",
    "Grade 3 Students - male [District]",
    "Grade 3 Students - female [District]",
    "Grade 4 Students - male [District]",
    "Grade 4 Students - female [District]",
    "Grade 5 Students - male [District]",
    "Grade 5 Students - female [District]",
    "Grade 6 Students - male [District]",
    "Grade 6 Students - female [District]",
    "Grade 7 Students - male [District]",
    "Grade 7 Students - female [District]",
    "Grade 8 Students - male [District]",
    "Grade 8 Students - female [District]",
    "Grade 9 Students - male [District]",
    "Grade 9 Students - female [District]",
    "Grade 10 Students - male [District]",
    "Grade 10 Students - female [District]",
    "Grade 11 Students - male [District]",
    "Grade 11 Students - female [District]",
    "Grade 12 Students - male [District]",
    "Grade 12 Students - female [District]",
    "Grade 13 Students - male [District]",
    "Grade 13 Students - female [District]",
    "Ungraded Students - male [District]",
    "Ungraded Students - female [District]",
    "Adult Education Students - male [District]",
    "Adult Education Students - female [District]",
    "Prekindergarten Students - American Indian/Alaska Native [District]",
    "Prekindergarten Students - Asian or Asian/Pacific Islander [District]",
    "Prekindergarten Students - Hispanic [District]",
    "Prekindergarten Students - Black or African American [District]",
    "Prekindergarten Students - White [District]",
    "Prekindergarten Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Prekindergarten Students, Two or More Races [District]",
    "Kindergarten Students - American Indian/Alaska Native [District]",
    "Kindergarten Students - Asian or Asian/Pacific Islander [District]",
    "Kindergarten Students - Hispanic [District]",
    "Kindergarten Students - Black or African American [District]",
    "Kindergarten Students, White [District]",
    "Kindergarten Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Kindergarten Students, Two or More Races [District]",
    "Grade 1 Students - American Indian/Alaska Native [District]",
    "Grade 1 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 1 Students - Hispanic [District]",
    "Grade 1 Students - Black or African American [District]",
    "Grade 1 Students - White [District]",
    "Grade 1 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 1 Students - Two or More Races [District]",
    "Grade 2 Students - American Indian/Alaska Native [District]",
    "Grade 2 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 2 Students - Hispanic [District]",
    "Grade 2 Students - Black or African American [District]",
    "Grade 2 Students - White [District]",
    "Grade 2 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 2 Students - Two or More Races [District]",
    "Grade 3 Students - American Indian/Alaska Native [District]",
    "Grade 3 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 3 Students - Hispanic [District]",
    "Grade 3 Students - Black or African American [District]",
    "Grade 3 Students - White [District]",
    "Grade 3 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 3 Students - Two or More Races [District]",
    "Grade 4 Students - American Indian/Alaska Native [District]",
    "Grade 4 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 4 Students - Hispanic [District]",
    "Grade 4 Students - Black or African American [District]",
    "Grade 4 Students - White [District]",
    "Grade 4 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 4 Students - Two or More Races [District]",
    "Grade 5 Students - American Indian/Alaska Native [District]",
    "Grade 5 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 5 Students - Hispanic [District]",
    "Grade 5 Students - Black or African American [District]",
    "Grade 5 Students - White [District]",
    "Grade 5 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 5 Students - Two or More Races [District]",
    "Grade 6 Students - American Indian/Alaska Native [District]",
    "Grade 6 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 6 Students - Hispanic [District]",
    "Grade 6 Students - Black or African American [District]",
    "Grade 6 Students - White [District]",
    "Grade 6 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 6 Students - Two or More Races [District]",
    "Grade 7 Students - American Indian/Alaska Native [District]",
    "Grade 7 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 7 Students - Hispanic [District]",
    "Grade 7 Students - Black or African American [District]",
    "Grade 7 Students - White [District]",
    "Grade 7 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 7 Students - Two or More Races [District]",
    "Grade 8 Students - American Indian/Alaska Native [District]",
    "Grade 8 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 8 Students - Hispanic [District]",
    "Grade 8 Students - Black or African American [District]",
    "Grade 8 Students - White [District]",
    "Grade 8 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 8 Students - Two or More Races [District]",
    "Grade 9 Students - American Indian/Alaska Native [District]",
    "Grade 9 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 9 Students - Hispanic [District]",
    "Grade 9 Students - Black or African American [District]",
    "Grade 9 Students - White [District]",
    "Grade 9 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 9 Students - Two or More Races [District]",
    "Grade 10 Students - American Indian/Alaska Native [District]",
    "Grade 10 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 10 Students - Hispanic [District]",
    "Grade 10 Students - Black or African American [District]",
    "Grade 10 Students - White [District]",
    "Grade 10 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 10 Students - Two or More Races [District]",
    "Grade 11 Students - American Indian/Alaska Native [District]",
    "Grade 11 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 11 Students - Hispanic [District]",
    "Grade 11 Students - Black or African American [District]",
    "Grade 11 Students - White [District]",
    "Grade 11 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 11 Students - Two or More Races [District]",
    "Grade 12 Students - American Indian/Alaska Native [District]",
    "Grade 12 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 12 Students - Hispanic [District]",
    "Grade 12 Students - Black or African American [District]",
    "Grade 12 Students - White [District]",
    "Grade 12 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 12 Students - Two or More Races [District]",
    "Grade 13 Students - American Indian/Alaska Native [District]",
    "Grade 13 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 13 Students - Hispanic [District]",
    "Grade 13 Students - Black or African American [District]",
    "Grade 13 Students - White [District]",
    "Grade 13 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 13 Students - Two or More Races [District]",
    "Ungraded Students - American Indian/Alaska Native [District]",
    "Ungraded Students - Asian or Asian/Pacific Islander [District]",
    "Ungraded Students - Hispanic [District]",
    "Ungraded Students - Black or African American [District]",
    "Ungraded Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Ungraded Students - White [District]",
    "Ungraded Students - Two or More Races [District]",
    "Adult Education Students - American Indian/Alaska Native [District]",
    "Adult Education Students - Asian or Asian/Pacific Islander [District]",
    "Adult Education Students - Hispanic [District]",
    "Adult Education Students - Black or African American [District]",
    "Adult Education Students - White [District]",
    "Adult Education - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Adult Education Students - Two or More Races [District]",
    "Prekindergarten Students - American Indian/Alaska Native - male [District]",
    "Prekindergarten Students - American Indian/Alaska Native - female [District]",
    "Prekindergarten Students - Asian or Asian/Pacific Islander - male [District]",
    "Prekindergarten Students - Asian or Asian/Pacific Islander - female [District]",
    "Prekindergarten Students - Hispanic - male [District]",
    "Prekindergarten Students - Hispanic - female [District]",
    "Prekindergarten Students - Black or African American - male [District]",
    "Prekindergarten Students - Black or African American - female [District]",
    "Prekindergarten Students - White - male [District]",
    "Prekindergarten Students - White - female [District]",
    "Prekindergarten Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Prekindergarten Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Prekindergarten Students - Two or More Races - male [District]",
    "Prekindergarten Students - Two or More Races - female [District]",
    "Kindergarten Students - American Indian/Alaska Native - male [District]",
    "Kindergarten Students - American Indian/Alaska Native - female [District]",
    "Kindergarten Students - Asian or Asian/Pacific Islander - male [District]",
    "Kindergarten Students - Asian or Asian/Pacific Islander - female [District]",
    "Kindergarten Students - Hispanic - male [District]",
    "Kindergarten Students - Hispanic - female [District]",
    "Kindergarten Students - Black or African American - male [District]",
    "Kindergarten Students - Black or African American - female [District]",
    "Kindergarten Students - White - male [District]",
    "Kindergarten Students - White - female [District]",
    "Kindergarten Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Kindergarten Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Kindergarten Students - Two or More Races - male [District]",
    "Kindergarten Students - Two or More Races - female [District]",
    "Grade 1 Students - American Indian/Alaska Native - male [District]",
    "Grade 1 Students - American Indian/Alaska Native - female [District]",
    "Grade 1 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 1 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 1 Students - Hispanic - male [District]",
    "Grade 1 Students - Hispanic - female [District]",
    "Grade 1 Students - Black or African American - male [District]",
    "Grade 1 Students - Black or African American - female [District]",
    "Grade 1 Students - White - male [District]",
    "Grade 1 Students - White - female [District]",
    "Grade 1 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 1 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 1 Students - Two or More Races - male [District]",
    "Grade 1 Students - Two or More Races - female [District]",
    "Grade 2 Students - American Indian/Alaska Native - male [District]",
    "Grade 2 Students - American Indian/Alaska Native - female [District]",
    "Grade 2 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 2 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 2 Students - Hispanic - male [District]",
    "Grade 2 Students - Hispanic - female [District]",
    "Grade 2 Students - Black or African American - male [District]",
    "Grade 2 Students - Black or African American - female [District]",
    "Grade 2 Students - White - male [District]",
    "Grade 2 Students - White - female [District]",
    "Grade 2 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 2 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 2 Students - Two or More Races - male [District]",
    "Grade 2 Students - Two or More Races - female [District]",
    "Grade 3 Students - American Indian/Alaska Native - male [District]",
    "Grade 3 Students - American Indian/Alaska Native - female [District]",
    "Grade 3 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 3 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 3 Students - Hispanic - male [District]",
    "Grade 3 Students - Hispanic - female [District]",
    "Grade 3 Students - Black or African American - male [District]",
    "Grade 3 Students - Black or African American - female [District]",
    "Grade 3 Students - White - male [District]",
    "Grade 3 Students - White - female [District]",
    "Grade 3 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 3 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 3 Students - Two or More Races - male [District]",
    "Grade 3 Students - Two or More Races - female [District]",
    "Grade 4 Students - American Indian/Alaska Native - male [District]",
    "Grade 4 Students - American Indian/Alaska Native - female [District]",
    "Grade 4 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 4 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 4 Students - Hispanic - male [District]",
    "Grade 4 Students - Hispanic - female [District]",
    "Grade 4 Students - Black or African American - male [District]",
    "Grade 4 Students - Black or African American - female [District]",
    "Grade 4 Students - White - male [District]",
    "Grade 4 Students - White - female [District]",
    "Grade 4 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 4 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 4 Students - Two or More Races - male [District]",
    "Grade 4 Students - Two or More Races - female [District]",
    "Grade 5 Students - American Indian/Alaska Native - male [District]",
    "Grade 5 Students - American Indian/Alaska Native - female [District]",
    "Grade 5 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 5 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 5 Students - Hispanic - male [District]",
    "Grade 5 Students - Hispanic - female [District]",
    "Grade 5 Students - Black or African American - male [District]",
    "Grade 5 Students - Black or African American - female [District]",
    "Grade 5 Students - White - male [District]",
    "Grade 5 Students - White - female [District]",
    "Grade 5 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 5 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 5 Students - Two or More Races - male [District]",
    "Grade 5 Students - Two or More Races - female [District]",
    "Grade 6 Students - American Indian/Alaska Native - male [District]",
    "Grade 6 Students - American Indian/Alaska Native - female [District]",
    "Grade 6 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 6 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 6 Students - Hispanic - male [District]",
    "Grade 6 Students - Hispanic - female [District]",
    "Grade 6 Students - Black or African American - male [District]",
    "Grade 6 Students - Black or African American - female [District]",
    "Grade 6 Students - White - male [District]",
    "Grade 6 Students - White - female [District]",
    "Grade 6 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 6 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 6 Students- Two or More Races - male [District]",
    "Grade 6 Students - Two or More Races - female [District]",
    "Grade 7 Students - American Indian/Alaska Native - male [District]",
    "Grade 7 Students - American Indian/Alaska Native - female [District]",
    "Grade 7 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 7 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 7 Students - Hispanic - male [District]",
    "Grade 7 Students - Hispanic - female [District]",
    "Grade 7 Students - Black or African American - male [District]",
    "Grade 7 Students - Black or African American - female [District]",
    "Grade 7 Students - White - male [District]",
    "Grade 7 Students - White - female [District]",
    "Grade 7 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 7 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 7 Students - Two or More Races - male [District]",
    "Grade 7 Students - Two or More Races - female [District]",
    "Grade 8 Students - American Indian/Alaska Native - male [District]",
    "Grade 8 Students - American Indian/Alaska Native - female [District]",
    "Grade 8 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 8 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 8 Students- Hispanic - male [District]",
    "Grade 8 Students - Hispanic - female [District]",
    "Grade 8 Students - Black or African American - male [District]",
    "Grade 8 Students - Black or African American - female [District]",
    "Grade 8 Students - White - male [District]",
    "Grade 8 Students - White - female [District]",
    "Grade 8 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 8 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 8 Students - Two or More Races - male [District]",
    "Grade 8 Students - Two or More Races - female [District]",
    "Grade 9 Students - American Indian/Alaska Native - male [District]",
    "Grade 9 Students - American Indian/Alaska Native - female [District]",
    "Grade 9 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 9 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 9 Students - Hispanic - male [District]",
    "Grade 9 Students - Hispanic - female [District]",
    "Grade 9 Students - Black or African American - male [District]",
    "Grade 9 Students - Black or African American - female [District]",
    "Grade 9 Students - White - male [District]",
    "Grade 9 Students - White - female [District]",
    "Grade 9 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 9 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 9 Students - Two or More Races - male [District]",
    "Grade 9 Students - Two or More Races - female [District]",
    "Grade 10 Students - American Indian/Alaska Native - male [District]",
    "Grade 10 Students - American Indian/Alaska Native - female [District]",
    "Grade 10 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 10 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 10 Students - Hispanic - male [District]",
    "Grade 10 Students - Hispanic - female [District]",
    "Grade 10 Students - Black or African American - male [District]",
    "Grade 10 Students - Black or African American - female [District]",
    "Grade 10 Students - White - male [District]",
    "Grade 10 Students - White - female [District]",
    "Grade 10 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 10 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 10 Students - Two or More Races - male [District]",
    "Grade 10 Students - Two or More Races - female [District]",
    "Grade 11 Students - American Indian/Alaska Native - male [District]",
    "Grade 11 Students - American Indian/Alaska Native - female [District]",
    "Grade 11 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 11 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 11 Students - Hispanic - male [District]",
    "Grade 11 Students - Hispanic - female [District]",
    "Grade 11 Students - Black or African American - male [District]",
    "Grade 11 Students - Black or African American - female [District]",
    "Grade 11 Students - White - male [District]",
    "Grade 11 Students - White - female [District]",
    "Grade 11 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 11 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 11 Students - Two or More Races - male [District]",
    "Grade 11 Students - Two or More Races - female [District]",
    "Grade 12 Students - American Indian/Alaska Native - male [District]",
    "Grade 12 Students - American Indian/Alaska Native - female [District]",
    "Grade 12 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 12 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 12 Students - Hispanic - male [District]",
    "Grade 12 Students - Hispanic - female [District]",
    "Grade 12 Students - Black or African American - male [District]",
    "Grade 12 Students - Black or African American - female [District]",
    "Grade 12 Students - White - male [District]",
    "Grade 12 Students - White - female [District]",
    "Grade 12 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 12 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 12 Students - Two or More Races - male [District]",
    "Grade 12 Students - Two or More Races - female [District]",
    "Grade 13 Students - American Indian/Alaska Native - male [District]",
    "Grade 13 Students - American Indian/Alaska Native - female [District]",
    "Grade 13 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 13 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 13 Students - Hispanic - male [District]",
    "Grade 13 Students - Hispanic - female [District]",
    "Grade 13 Students - Black or African American - male [District]",
    "Grade 13 Students - Black or African American - female [District]",
    "Grade 13 Students - White - male [District]",
    "Grade 13 Students - White - female [District]",
    "Grade 13 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 13 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 13 Students - Two or More Races - male [District]",
    "Grade 13 Students - Two or More Races - female [District]",
    "Ungraded Students - American Indian/Alaska Native - male [District]",
    "Ungraded Students - American Indian/Alaska Native - female [District]",
    "Ungraded Students - Asian or Asian/Pacific Islander - male [District]",
    "Ungraded Students - Asian or Asian/Pacific Islander - female [District]",
    "Ungraded Students - Hispanic - male [District]",
    "Ungraded Students - Hispanic - female [District]",
    "Ungraded Students - Black or African American - male [District]",
    "Ungraded Students - Black or African American - female [District]",
    "Ungraded Students - White - male [District]",
    "Ungraded Students - White - female [District]",
    "Ungraded Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Ungraded Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Ungraded Students - Two or More Races - male [District]",
    "Ungraded Students - Two or More Races - female [District]",
    "Adult Education Students - American Indian/Alaska Native - male [District]",
    "Adult Education Students - American Indian/Alaska Native - female [District]",
    "Adult Education Students - Asian or Asian/Pacific Islander - male [District]",
    "Adult Education Students - Asian or Asian/Pacific Islander - female [District]",
    "Adult Education Students - Hispanic - male [District]",
    "Adult Education Students - Hispanic - female [District]",
    "Adult Education Students - Black or African American - male [District]",
    "Adult Education Students - Black or African American - female [District]",
    "Adult Education Students - White - male [District]",
    "Adult Education Students - White - female [District]",
    "Adult Education Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Adult Education Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Adult Education Students - Two or More Races - male [District]",
    "Adult Education Students - Two or More Races - female [District]",
    "Full-Time Equivalent (FTE) Teachers [District]",
    "Pupil/Teacher Ratio [District]", "Prekindergarten Teachers [District]",
    "Kindergarten Teachers [District]", "Elementary Teachers [District]",
    "Secondary Teachers [District]", "Ungraded Teachers [District]",
    "Total Staff [District]", "Paraprofessionals/Instructional Aides [District]",
    "Instructional Coordinators [District]",
    "Elementary School Counselor [District]",
    "Secondary School Counselor [District]",
    "Other Guidance Counselors [District]",
    "Total Guidance Counselors [District]",
    "Librarians/media specialists [District]", "Media Support Staff [District]",
    "LEA Administrators [District]",
    "LEA Administrative Support Staff [District]",
    "School Administrators [District]",
    "School Administrative Support Staff [District]",
    "Student Support Services Staff (w/o Psychology) [District]",
    "School Psychologist [District]", "Other Support Services Staff [District]",
    "Student Support Services Staff [District]"
]

KEY_COLUMNS_PUBLIC = ["13392"]
KEY_COLUMNS_PRIVATE = ["13391"]
KEY_COLUMNS_DISTRICT = ["13393"]
