# This is a radio button selection and the key words are as per the website
SCHOOL = ["PublicSchool"]
DISTRICT_2017 = ['9560', '32651', '13393', '32618', '16661', '32628', '32629', '32631', '32632', '32622', '32645', '32642', '32643', '32619', '32635', '32636', '32603', '33079', '32664', '32665', '32666', '32667', '32668', '32669', '32670', '32671', '32672', '32673', '32674', '32675', '32676', '32677', '32678', '32679', '33077', '32615', '33078', '32662', '32663', '33025', '33026', '33027', '33028', '33029', '33030', '33031', '33032', '33033', '33034', '33035', '33036', '33037', '33038', '33039', '33040', '33041', '33042', '33043', '33044', '33045', '33046', '32680', '32681', '32682', '32683', '32684', '32685', '32686', '32687', '32688', '32689', '32690', '32691', '32692', '32693', '32694', '32695', '32696', '32697', '32698', '32699', '32700', '32701', '32702', '32703', '32704', '32705', '32706', '32707', '36149', '36150', '32708', '32709', '36151', '36152', '32710', '32711', '32712', '32713', '32714', '32715', '32716', '32717', '32718', '32719', '32720', '32721', '32722', '32723', '32724', '32725', '32726', '32727', '32728', '32729', '32730', '32731', '32732', '32733', '32734', '32735', '32736', '32737', '32738', '32739', '32740', '32741', '32742', '32743', '32744', '32745', '32746', '32747', '32748', '32749', '32750', '32751', '32752', '32753', '32754', '32755', '32756', '32757', '32758', '32759', '32760', '32761', '32762', '32763', '32764', '32765', '32766', '32767', '32768', '32769', '32770', '32771', '32772', '32773', '32774', '32775', '32776', '32777', '32778', '32779', '32780', '32781', '32782', '32783', '32784', '32785', '32786', '32787', '32788', '32789', '32790', '32791', '32792', '32793', '32794', '32795', '32796', '32797', '32798', '32799', '32800', '32801', '32802', '32803', '32804', '32805', '32806', '32807', '36153', '36154', '36155', '36156', '36157', '36158', '32808', '32809', '32810', '32811', '32813', '32812', '32814', '36160', '36161', '36162', '36163', '36164', '36165', '36166', '36159', '32815', '32816', '32817', '32818', '32819', '32820', '32821', '32822', '32823', '32824', '32825', '32826', '32827', '32828', '32829', '32830', '32831', '32832', '32833', '32834', '32835', '32836', '32837', '32838', '32839', '32840', '32841', '32842', '32843', '32844', '32845', '32846', '32847', '32848', '32849', '32850', '32851', '32852', '32853', '32854', '32855', '32856', '32857', '32858', '32859', '32860', '32861', '32862', '32863', '32864', '32865', '32866', '32867', '32868', '32869', '32870', '32871', '32872', '32873', '32874', '32875', '32876', '32877', '32878', '32879', '32880', '32881', '32882', '32883', '32884', '32885', '32886', '32887', '32888', '32889', '32890', '32891', '32892', '32893', '32894', '32895', '32896', '32897', '32898', '32899', '32900', '32901', '32902', '32903', '32904', '32905', '32906', '32907', '32908', '32909', '32910', '32911', '32912', '32913', '32914', '32915', '32916', '32917', '32918', '32919', '32920', '32921', '32922', '32923', '32924', '32925', '32926', '32927', '32928', '32929', '32930', '32931', '32932', '32933', '32934', '32935', '32936', '32937', '32938', '32939', '32940', '32941', '32942', '32943', '32944', '32945', '32946', '32947', '32948', '32949', '32950', '32951', '32952', '32953', '32954', '32955', '32956', '32957', '32958', '32959', '32960', '32961', '32962', '32963', '32964', '32965', '32966', '32967', '32968', '32969', '32970', '32971', '32972', '32973', '32974', '32975', '32976', '32977', '32978', '32979', '32980', '32981', '32982', '32983', '32984', '32985', '32986', '32987', '32988', '32989', '32990', '32991', '32992', '32993', '32994', '32995', '32996', '32997', '32998', '32999', '33000', '33001', '33002', '33003', '33004', '33005', '33006', '33007', '33008', '33009', '33010', '36167', '36168', '36169', '36170', '36171', '36172', '36173', '36174', '36175', '36176', '36177', '36178', '36179', '36180', '33011', '33012', '33013', '33014', '33015', '33016', '33017', '33018', '33019', '33020', '33021', '33022', '33023', '33024', '36181', '36182', '36183', '36184', '36185', '36186', '36187', '36188', '36189', '36190', '36191', '36192', '36193', '36194', '32614', '32641', '32605', '32597', '32596', '32610', '32616', '32634', '32593', '32594', '32595', '32609', '32654', '32613', '32601', '32602', '32598', '32599', '32607', '32608', '32612', '32604'] 
PUBLIC_2017 = ['33535', '13403', '33081', '13392', '33085', '15188', '33402', '16662', '33316', '33317', '33319', '33320', '33310', '33321', '33082', '33086', '33405', '33531', '33399', '33400', '33114', '33538', '33309', '33084', '33083', '33106', '33552', '33090', '33558', '33109', '33111', '33409', '33410', '33107', '33105', '33092', '33093', '33094', '33095', '33096', '33097', '33098', '33099', '33100', '33101', '33102', '33103', '33550', '33112', '33551', '33397', '33398', '33087', '33088', '33104', '33089', '33113', '33462', '33414', '33110', '33268', '33269', '33270', '33271', '33273', '33274', '33275', '33276', '33277', '33493', '33494', '33445', '33446', '33281', '33282', '33308', '33283', '33284', '33285', '33286', '33287', '33288', '33289', '33290', '33291', '33292', '33293', '33294', '33295', '33296', '33297', '33298', '33299', '33300', '33301', '33302', '33303', '33304', '33305', '33306', '33307', '36032', '36033', '33279', '33280', '36016', '36017', '33322', '33323', '33324', '33325', '33326', '33495', '33447', '33327', '33328', '33329', '33330', '33331', '33496', '33448', '33332', '33333', '33334', '33335', '33336', '33497', '33449', '33337', '33338', '33339', '33340', '33341', '33498', '33450', '33342', '33343', '33344', '33345', '33346', '33499', '33451', '33347', '33348', '33349', '33350', '33351', '33500', '33452', '33352', '33353', '33354', '33355', '33356', '33501', '33453', '33357', '33358', '33359', '33360', '33361', '33502', '33454', '33362', '33363', '33364', '33365', '33366', '33503', '33455', '33367', '33368', '33369', '33370', '33371', '33504', '33456', '33372', '33373', '33374', '33375', '33376', '33505', '33457', '33377', '33378', '33379', '33380', '33381', '33506', '33458', '33382', '33383', '33384', '33385', '33386', '33507', '33459', '33387', '33388', '33389', '33390', '33391', '33508', '33460', '36018', '36019', '36020', '36021', '36022', '36023', '36024', '33392', '33393', '33394', '33395', '33396', '33509', '33461', '36025', '36026', '36027', '36028', '36029', '36030', '36031', '33118', '33119', '33120', '33121', '33122', '33123', '33124', '33125', '33126', '33127', '33463', '33464', '33415', '33416', '33128', '33129', '33130', '33131', '33132', '33133', '33134', '33135', '33136', '33137', '33465', '33466', '33417', '33418', '33138', '33139', '33140', '33141', '33142', '33143', '33144', '33145', '33146', '33147', '33467', '33468', '33419', '33420', '33148', '33149', '33150', '33151', '33152', '33153', '33154', '33155', '33156', '33157', '33469', '33470', '33421', '33422', '33158', '33159', '33160', '33161', '33162', '33163', '33164', '33165', '33166', '33167', '33471', '33472', '33423', '33424', '33168', '33169', '33170', '33171', '33172', '33173', '33174', '33175', '33176', '33177', '33473', '33474', '33425', '33426', '33178', '33179', '33180', '33181', '33182', '33183', '33184', '33185', '33186', '33187', '33475', '33476', '33427', '33428', '33188', '33189', '33190', '33191', '33192', '33193', '33194', '33195', '33196', '33197', '33477', '33478', '33429', '33430', '33198', '33199', '33200', '33201', '33202', '33203', '33204', '33205', '33206', '33207', '33479', '33480', '33431', '33432', '33208', '33209', '33210', '33211', '33212', '33213', '33214', '33215', '33216', '33217', '33481', '33482', '33433', '33434', '33218', '33219', '33220', '33221', '33222', '33223', '33224', '33225', '33226', '33227', '33483', '33484', '33435', '33436', '33228', '33229', '33230', '33231', '33232', '33233', '33234', '33235', '33236', '33237', '33485', '33486', '33437', '33438', '33238', '33239', '33240', '33241', '33242', '33243', '33244', '33245', '33246', '33247', '33487', '33488', '33439', '33440', '33248', '33249', '33250', '33251', '33252', '33253', '33254', '33255', '33256', '33257', '33489', '33490', '33441', '33442', '35885', '35886', '35887', '35888', '35889', '35890', '35891', '35892', '35893', '35894', '35895', '35896', '35897', '35898', '33258', '33259', '33260', '33261', '33262', '33263', '33264', '33265', '33266', '33267', '33491', '33492', '33443', '33444', '35899', '35900', '35901', '35902', '35903', '35904', '35905', '35906', '35907', '35908', '35909', '35910', '35911', '35912', '33091', '33108']

# Default columns selected for the data export.
DEFAULT_COLUMNS_SELECTED = ["staticName", "defaultName"]

# List of columns specifically for Public Schools data export.
PRIVATE_COLUMNS = [
    "State Name [Private School]", "ANSI/FIPS State Code [Private School]",
    "Private School Name [Private School]",
    "School ID - NCES Assigned [Private School]",
    "County Name [Private School]", "ANSI/FIPS County Code [Private School]",
    "Phone Number [Private School]", "Physical Address [Private School]",
    "City [Private School]", "ZIP [Private School]", "ZIP + 4 [Private School]",
    "Lowest Grade Taught [Private School]",
    "Highest Grade Taught [Private School]", "Coeducational [Private School]",
    "School Type [Private School]", "School Level [Private School]",
    "School's Religious Affiliation or Orientation [Private School]",
    "School Community Type [Private School]",
    "Total Students (Ungraded & PK-12) [Private School]",
    "Total Students (Ungraded & K-12) [Private School]",
    "Prekindergarten and Kindergarten Students [Private School]",
    "Grades 1-8 Students [Private School]",
    "Grades 9-12 Students [Private School]",
    "Prekindergarten Students [Private School]",
    "Kindergarten Students [Private School]",
    "Grade 1 Students [Private School]", "Grade 2 Students [Private School]",
    "Grade 3 Students [Private School]", "Grade 4 Students [Private School]",
    "Grade 5 Students [Private School]", "Grade 6 Students [Private School]",
    "Grade 7 Students [Private School]", "Grade 8 Students [Private School]",
    "Grade 9 Students [Private School]", "Grade 10 Students [Private School]",
    "Grade 11 Students [Private School]", "Grade 12 Students [Private School]",
    "Ungraded Students [Private School]",
    "Pupil/Teacher Ratio [Private School]",
    "Full-Time Equivalent (FTE) Teachers [Private School]",
    "American Indian/Alaska Native Students [Private School]",
    "Percentage of American Indian/Alaska Native Students [Private School]",
    "Asian or Asian/Pacific Islander Students [Private School]",
    "Percentage of Asian or Asian/Pacific Islander Students [Private School]",
    "Hispanic Students [Private School]",
    "Percentage of Hispanic Students [Private School]",
    "Black or African American Students [Private School]",
    "Percentage of Black Students [Private School]",
    "White Students [Private School]",
    "Percentage of White Students [Private School]",
    "Nat. Hawaiian or Other Pacific Isl. Students [Private School]",
    "Percentage of Nat. Hawaiian or Other Pacific Isl. Students [Private School]",
    "Two or More Races Students [Private School]",
    "Percentage of Two or More Races Students [Private School]",
    "State Abbr [Private School]", "Religious Orientation [Private School]"
]

PUBLIC_COLUMNS = [
    "State Name [Public School]", "State Abbr [Public School]",
    "School Name [Public School]", "School ID - NCES Assigned [Public School]",
    "Agency Name [Public School]", "Agency ID - NCES Assigned [Public School]",
    "County Number [Public School]", "ANSI/FIPS State Code [Public School]",
    "Location Address 1 [Public School]", "Location City [Public School]",
    "Location ZIP [Public School]", "Location ZIP4 [Public School]",
    "Phone Number [Public School]",
    "National School Lunch Program [Public School]",
    "Magnet School [Public School]", "State School ID [Public School]",
    "School Type [Public School]", "Title I School Status [Public School]",
    "Charter School [Public School]", "Locale [Public School]",
    "Latitude [Public School]", "Longitude [Public School]",
    "Lowest Grade Offered [Public School]",
    "Highest Grade Offered [Public School]",
    "School Level (SY 2017-18 onward) [Public School]",
    "School Level [Public School]",
    "Total Students, All Grades (Excludes AE) [Public School]",
    "Total Students, All Grades (Includes AE) [Public School]",
    "Free Lunch Eligible [Public School]",
    "Direct Certification [Public School]",
    "Reduced-price Lunch Eligible Students [Public School]",
    "Free and Reduced Lunch Students [Public School]",
    "Grades 1-8 Students [Public School]",
    "Grades 9-12 Students [Public School]",
    "Prekindergarten Students [Public School]",
    "Kindergarten Students [Public School]", "Grade 1 Students [Public School]",
    "Grade 2 Students [Public School]", "Grade 3 Students [Public School]",
    "Grade 4 Students [Public School]", "Grade 5 Students [Public School]",
    "Grade 6 Students [Public School]", "Grade 7 Students [Public School]",
    "Grade 8 Students [Public School]", "Grade 9 Students [Public School]",
    "Grade 10 Students [Public School]", "Grade 11 Students [Public School]",
    "Grade 12 Students [Public School]", "Grade 13 Students [Public School]",
    "Ungraded Students [Public School]",
    "Adult Education Students [Public School]", "Male Students [Public School]",
    "Female Students [Public School]",
    "American Indian/Alaska Native Students [Public School]",
    "Asian or Asian/Pacific Islander Students [Public School]",
    "Hispanic Students [Public School]",
    "Black or African American Students [Public School]",
    "White Students [Public School]",
    "Nat. Hawaiian or Other Pacific Isl. Students [Public School]",
    "Two or More Races Students [Public School]",
    "Total Race/Ethnicity [Public School]",
    "American Indian/Alaska Native - male [Public School]",
    "American Indian/Alaska Native - female [Public School]",
    "Asian or Asian/Pacific Islander - male [Public School]",
    "Asian or Asian/Pacific Islander - female [Public School]",
    "Hispanic - female [Public School]", "Hispanic - male [Public School]",
    "Black or African American - male [Public School]",
    "Black or African American - female [Public School]",
    "White - male [Public School]", "White - female [Public School]",
    "Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Two or More Races - male [Public School]",
    "Two or More Races - female [Public School]",
    "Prekindergarten Students - male [Public School]",
    "Prekindergarten Students - female [Public School]",
    "Kindergarten Students - male [Public School]",
    "Kindergarten Students - female [Public School]",
    "Grade 1 Students - male [Public School]",
    "Grade 1 Students - female [Public School]",
    "Grade 2 Students - male [Public School]",
    "Grade 2 Students - female [Public School]",
    "Grade 3 Students - male [Public School]",
    "Grade 3 Students - female [Public School]",
    "Grade 4 Students - male [Public School]",
    "Grade 4 Students - female [Public School]",
    "Grade 5 Students - male [Public School]",
    "Grade 5 Students - female [Public School]",
    "Grade 6 Students - male [Public School]",
    "Grade 6 Students - female [Public School]",
    "Grade 7 Students - male [Public School]",
    "Grade 7 Students - female [Public School]",
    "Grade 8 Students - male [Public School]",
    "Grade 8 Students - female [Public School]",
    "Grade 9 Students - male [Public School]",
    "Grade 9 Students - female [Public School]",
    "Grade 10 Students - male [Public School]",
    "Grade 10 Students - female [Public School]",
    "Grade 11 Students - male [Public School]",
    "Grade 11 Students - female [Public School]",
    "Grade 12 Students - male [Public School]",
    "Grade 12 Students - female [Public School]",
    "Grade 13 Students - male [Public School]",
    "Grade 13 Students - female [Public School]",
    "Ungraded Students - male [Public School]",
    "Ungraded Students - female [Public School]",
    "Adult Education Students - male [Public School]",
    "Adult Education Students - female [Public School]",
    "Prekindergarten Students - American Indian/Alaska Native [Public School]",
    "Prekindergarten Students - Asian or Asian/Pacific Islander [Public School]",
    "Prekindergarten Students - Hispanic [Public School]",
    "Prekindergarten Students - Black or African American [Public School]",
    "Prekindergarten Students - White [Public School]",
    "Prekindergarten Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Prekindergarten Students, Two or More Races [Public School]",
    "Kindergarten Students - American Indian/Alaska Native [Public School]",
    "Kindergarten Students - Asian or Asian/Pacific Islander [Public School]",
    "Kindergarten Students - Hispanic [Public School]",
    "Kindergarten Students - Black or African American [Public School]",
    "Kindergarten Students, White [Public School]",
    "Kindergarten Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Kindergarten Students, Two or More Races [Public School]",
    "Grade 1 Students - American Indian/Alaska Native [Public School]",
    "Grade 1 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 1 Students - Hispanic [Public School]",
    "Grade 1 Students - Black or African American [Public School]",
    "Grade 1 Students - White [Public School]",
    "Grade 1 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 1 Students - Two or More Races [Public School]",
    "Grade 2 Students - American Indian/Alaska Native [Public School]",
    "Grade 2 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 2 Students - Hispanic [Public School]",
    "Grade 2 Students - Black or African American [Public School]",
    "Grade 2 Students - White [Public School]",
    "Grade 2 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 2 Students - Two or More Races [Public School]",
    "Grade 3 Students - American Indian/Alaska Native [Public School]",
    "Grade 3 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 3 Students - Hispanic [Public School]",
    "Grade 3 Students - Black or African American [Public School]",
    "Grade 3 Students - White [Public School]",
    "Grade 3 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 3 Students - Two or More Races [Public School]",
    "Grade 4 Students - American Indian/Alaska Native [Public School]",
    "Grade 4 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 4 Students - Hispanic [Public School]",
    "Grade 4 Students - Black or African American [Public School]",
    "Grade 4 Students - White [Public School]",
    "Grade 4 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 4 Students - Two or More Races [Public School]",
    "Grade 5 Students - American Indian/Alaska Native [Public School]",
    "Grade 5 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 5 Students - Hispanic [Public School]",
    "Grade 5 Students - Black or African American [Public School]",
    "Grade 5 Students - White [Public School]",
    "Grade 5 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 5 Students - Two or More Races [Public School]",
    "Grade 6 Students - American Indian/Alaska Native [Public School]",
    "Grade 6 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 6 Students - Hispanic [Public School]",
    "Grade 6 Students - Black or African American [Public School]",
    "Grade 6 Students - White [Public School]",
    "Grade 6 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 6 Students - Two or More Races [Public School]",
    "Grade 7 Students - American Indian/Alaska Native [Public School]",
    "Grade 7 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 7 Students - Hispanic [Public School]",
    "Grade 7 Students - Black or African American [Public School]",
    "Grade 7 Students - White [Public School]",
    "Grade 7 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 7 Students - Two or More Races [Public School]",
    "Grade 8 Students - American Indian/Alaska Native [Public School]",
    "Grade 8 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 8 Students - Hispanic [Public School]",
    "Grade 8 Students - Black or African American [Public School]",
    "Grade 8 Students - White [Public School]",
    "Grade 8 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 8 Students - Two or More Races [Public School]",
    "Grade 9 Students - American Indian/Alaska Native [Public School]",
    "Grade 9 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 9 Students - Hispanic [Public School]",
    "Grade 9 Students - Black or African American [Public School]",
    "Grade 9 Students - White [Public School]",
    "Grade 9 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 9 Students - Two or More Races [Public School]",
    "Grade 10 Students - American Indian/Alaska Native [Public School]",
    "Grade 10 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 10 Students - Hispanic [Public School]",
    "Grade 10 Students - Black or African American [Public School]",
    "Grade 10 Students - White [Public School]",
    "Grade 10 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 10 Students - Two or More Races [Public School]",
    "Grade 11 Students - American Indian/Alaska Native [Public School]",
    "Grade 11 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 11 Students - Hispanic [Public School]",
    "Grade 11 Students - Black or African American [Public School]",
    "Grade 11 Students - White [Public School]",
    "Grade 11 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 11 Students - Two or More Races [Public School]",
    "Grade 12 Students - American Indian/Alaska Native [Public School]",
    "Grade 12 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 12 Students - Hispanic [Public School]",
    "Grade 12 Students - Black or African American [Public School]",
    "Grade 12 Students - White [Public School]",
    "Grade 12 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 12 Students - Two or More Races [Public School]",
    "Grade 13 Students - American Indian/Alaska Native [Public School]",
    "Grade 13 Students - Asian or Asian/Pacific Islander [Public School]",
    "Grade 13 Students - Hispanic [Public School]",
    "Grade 13 Students - Black or African American [Public School]",
    "Grade 13 Students - White [Public School]",
    "Grade 13 Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Grade 13 Students - Two or More Races [Public School]",
    "Ungraded Students - American Indian/Alaska Native [Public School]",
    "Ungraded Students - Asian or Asian/Pacific Islander [Public School]",
    "Ungraded Students - Hispanic [Public School]",
    "Ungraded Students - Black or African American [Public School]",
    "Ungraded Students - White [Public School]",
    "Ungraded Students - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Ungraded Students - Two or More Races [Public School]",
    "Adult Education Students - American Indian/Alaska Native [Public School]",
    "Adult Education Students - Asian or Asian/Pacific Islander [Public School]",
    "Adult Education Students - Hispanic [Public School]",
    "Adult Education Students - Black or African American [Public School]",
    "Adult Education Students - White [Public School]",
    "Adult Education - Nat. Hawaiian or Other Pacific Isl. [Public School]",
    "Adult Education Students - Two or More Races [Public School]",
    "Prekindergarten Students - American Indian/Alaska Native - male [Public School]",
    "Prekindergarten Students - American Indian/Alaska Native - female [Public School]",
    "Prekindergarten Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Prekindergarten Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Prekindergarten Students - Hispanic - male [Public School]",
    "Prekindergarten Students - Hispanic - female [Public School]",
    "Prekindergarten Students - Black or African American - male [Public School]",
    "Prekindergarten Students - Black or African American - female [Public School]",
    "Prekindergarten Students - White - male [Public School]",
    "Prekindergarten Students - White - female [Public School]",
    "Prekindergarten Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Prekindergarten Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Prekindergarten Students - Two or More Races - male [Public School]",
    "Prekindergarten Students - Two or More Races - female [Public School]",
    "Kindergarten Students - American Indian/Alaska Native - male [Public School]",
    "Kindergarten Students - American Indian/Alaska Native - female [Public School]",
    "Kindergarten Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Kindergarten Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Kindergarten Students - Hispanic - male [Public School]",
    "Kindergarten Students - Hispanic - female [Public School]",
    "Kindergarten Students - Black or African American - male [Public School]",
    "Kindergarten Students - Black or African American - female [Public School]",
    "Kindergarten Students - White - male [Public School]",
    "Kindergarten Students - White - female [Public School]",
    "Kindergarten Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Kindergarten Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Kindergarten Students - Two or More Races - male [Public School]",
    "Kindergarten Students - Two or More Races - female [Public School]",
    "Grade 1 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 1 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 1 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 1 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 1 Students - Hispanic - male [Public School]",
    "Grade 1 Students - Hispanic - female [Public School]",
    "Grade 1 Students - Black or African American - male [Public School]",
    "Grade 1 Students - Black or African American - female [Public School]",
    "Grade 1 Students - White - male [Public School]",
    "Grade 1 Students - White - female [Public School]",
    "Grade 1 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 1 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 1 Students - Two or More Races - male [Public School]",
    "Grade 1 Students - Two or More Races - female [Public School]",
    "Grade 2 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 2 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 2 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 2 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 2 Students - Hispanic - male [Public School]",
    "Grade 2 Students - Hispanic - female [Public School]",
    "Grade 2 Students - Black or African American - male [Public School]",
    "Grade 2 Students - Black or African American - female [Public School]",
    "Grade 2 Students - White - male [Public School]",
    "Grade 2 Students - White - female [Public School]",
    "Grade 2 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 2 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 2 Students - Two or More Races - male [Public School]",
    "Grade 2 Students - Two or More Races - female [Public School]",
    "Grade 3 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 3 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 3 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 3 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 3 Students - Hispanic - male [Public School]",
    "Grade 3 Students - Hispanic - female [Public School]",
    "Grade 3 Students - Black or African American - male [Public School]",
    "Grade 3 Students - Black or African American - female [Public School]",
    "Grade 3 Students - White - male [Public School]",
    "Grade 3 Students - White - female [Public School]",
    "Grade 3 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 3 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 3 Students - Two or More Races - male [Public School]",
    "Grade 3 Students - Two or More Races - female [Public School]",
    "Grade 4 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 4 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 4 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 4 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 4 Students - Hispanic - male [Public School]",
    "Grade 4 Students - Hispanic - female [Public School]",
    "Grade 4 Students - Black or African American - male [Public School]",
    "Grade 4 Students - Black or African American - female [Public School]",
    "Grade 4 Students - White - male [Public School]",
    "Grade 4 Students - White - female [Public School]",
    "Grade 4 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 4 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 4 Students - Two or More Races - male [Public School]",
    "Grade 4 Students - Two or More Races - female [Public School]",
    "Grade 5 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 5 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 5 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 5 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 5 Students - Hispanic - male [Public School]",
    "Grade 5 Students - Hispanic - female [Public School]",
    "Grade 5 Students - Black or African American - male [Public School]",
    "Grade 5 Students - Black or African American - female [Public School]",
    "Grade 5 Students - White - male [Public School]",
    "Grade 5 Students - White - female [Public School]",
    "Grade 5 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 5 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 5 Students - Two or More Races - male [Public School]",
    "Grade 5 Students - Two or More Races - female [Public School]",
    "Grade 6 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 6 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 6 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 6 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 6 Students - Hispanic - male [Public School]",
    "Grade 6 Students - Hispanic - female [Public School]",
    "Grade 6 Students - Black or African American - male [Public School]",
    "Grade 6 Students - Black or African American - female [Public School]",
    "Grade 6 Students - White - male [Public School]",
    "Grade 6 Students - White - female [Public School]",
    "Grade 6 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 6 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 6 Students- Two or More Races - male [Public School]",
    "Grade 6 Students - Two or More Races - female [Public School]",
    "Grade 7 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 7 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 7 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 7 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 7 Students - Hispanic - male [Public School]",
    "Grade 7 Students - Hispanic - female [Public School]",
    "Grade 7 Students - Black or African American - male [Public School]",
    "Grade 7 Students - Black or African American - female [Public School]",
    "Grade 7 Students - White - male [Public School]",
    "Grade 7 Students - White - female [Public School]",
    "Grade 7 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 7 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 7 Students - Two or More Races - male [Public School]",
    "Grade 7 Students - Two or More Races - female [Public School]",
    "Grade 8 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 8 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 8 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 8 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 8 Students- Hispanic - male [Public School]",
    "Grade 8 Students - Hispanic - female [Public School]",
    "Grade 8 Students - Black or African American - male [Public School]",
    "Grade 8 Students - Black or African American - female [Public School]",
    "Grade 8 Students - White - male [Public School]",
    "Grade 8 Students - White - female [Public School]",
    "Grade 8 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 8 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 8 Students - Two or More Races - male [Public School]",
    "Grade 8 Students - Two or More Races - female [Public School]",
    "Grade 9 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 9 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 9 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 9 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 9 Students - Hispanic - male [Public School]",
    "Grade 9 Students - Hispanic - female [Public School]",
    "Grade 9 Students - Black or African American - male [Public School]",
    "Grade 9 Students - Black or African American - female [Public School]",
    "Grade 9 Students - White - male [Public School]",
    "Grade 9 Students - White - female [Public School]",
    "Grade 9 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 9 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 9 Students - Two or More Races - male [Public School]",
    "Grade 9 Students - Two or More Races - female [Public School]",
    "Grade 10 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 10 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 10 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 10 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 10 Students - Hispanic - male [Public School]",
    "Grade 10 Students - Hispanic - female [Public School]",
    "Grade 10 Students - Black or African American - male [Public School]",
    "Grade 10 Students - Black or African American - female [Public School]",
    "Grade 10 Students - White - male [Public School]",
    "Grade 10 Students - White - female [Public School]",
    "Grade 10 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 10 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 10 Students - Two or More Races - male [Public School]",
    "Grade 10 Students - Two or More Races - female [Public School]",
    "Grade 11 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 11 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 11 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 11 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 11 Students - Hispanic - male [Public School]",
    "Grade 11 Students - Hispanic - female [Public School]",
    "Grade 11 Students - Black or African American - male [Public School]",
    "Grade 11 Students - Black or African American - female [Public School]",
    "Grade 11 Students - White - male [Public School]",
    "Grade 11 Students - White - female [Public School]",
    "Grade 11 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 11 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 11 Students - Two or More Races - male [Public School]",
    "Grade 11 Students - Two or More Races - female [Public School]",
    "Grade 12 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 12 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 12 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 12 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 12 Students - Hispanic - male [Public School]",
    "Grade 12 Students - Hispanic - female [Public School]",
    "Grade 12 Students - Black or African American - male [Public School]",
    "Grade 12 Students - Black or African American - female [Public School]",
    "Grade 12 Students - White - male [Public School]",
    "Grade 12 Students - White - female [Public School]",
    "Grade 12 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 12 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 12 Students - Two or More Races - male [Public School]",
    "Grade 12 Students - Two or More Races - female [Public School]",
    "Grade 13 Students - American Indian/Alaska Native - male [Public School]",
    "Grade 13 Students - American Indian/Alaska Native - female [Public School]",
    "Grade 13 Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Grade 13 Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Grade 13 Students - Hispanic - male [Public School]",
    "Grade 13 Students - Hispanic - female [Public School]",
    "Grade 13 Students - Black or African American - male [Public School]",
    "Grade 13 Students - Black or African American - female [Public School]",
    "Grade 13 Students - White - male [Public School]",
    "Grade 13 Students - White - female [Public School]",
    "Grade 13 Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Grade 13 Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Grade 13 Students - Two or More Races - male [Public School]",
    "Grade 13 Students - Two or More Races - female [Public School]",
    "Ungraded Students - American Indian/Alaska Native - male [Public School]",
    "Ungraded Students - American Indian/Alaska Native - female [Public School]",
    "Ungraded Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Ungraded Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Ungraded Students - Hispanic - male [Public School]",
    "Ungraded Students - Hispanic - female [Public School]",
    "Ungraded Students - Black or African American - male [Public School]",
    "Ungraded Students - Black or African American - female [Public School]",
    "Ungraded Students - White - male [Public School]",
    "Ungraded Students - White - female [Public School]",
    "Ungraded Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Ungraded Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Ungraded Students - Two or More Races - male [Public School]",
    "Ungraded Students - Two or More Races - female [Public School]",
    "Adult Education Students - American Indian/Alaska Native - male [Public School]",
    "Adult Education Students - American Indian/Alaska Native - female [Public School]",
    "Adult Education Students - Asian or Asian/Pacific Islander - male [Public School]",
    "Adult Education Students - Asian or Asian/Pacific Islander - female [Public School]",
    "Adult Education Students - Hispanic - male [Public School]",
    "Adult Education Students - Hispanic - female [Public School]",
    "Adult Education Students - Black or African American - male [Public School]",
    "Adult Education Students - Black or African American - female [Public School]",
    "Adult Education Students - White - male [Public School]",
    "Adult Education Students - White - female [Public School]",
    "Adult Education Students - Nat. Hawaiian or Other Pacific Isl. - male [Public School]",
    "Adult Education Students - Nat. Hawaiian or Other Pacific Isl. - female [Public School]",
    "Adult Education Students - Two or More Races - male [Public School]",
    "Adult Education Students - Two or More Races - female [Public School]",
    "Full-Time Equivalent (FTE) Teachers [Public School]",
    "Pupil/Teacher Ratio [Public School]"
]

DISTRICT_COLUMNS = [
    "State Abbr [District]", "Agency Name [District]",
    "Agency ID - NCES Assigned [District]", "County Number [District]",
    "ANSI/FIPS State Code [District]", "Location Address 1 [District]",
    "Location ZIP [District]", "Location City [District]",
    "Location ZIP4 [District]", "Lowest Grade Offered [District]",
    "Highest Grade Offered [District]", "Locale [District]",
    "State Agency ID [District]", "Latitude [District]", "Longitude [District]",
    "Phone Number [District]",
    "Total Students, All Grades (Excludes AE) [District]",
    "Total Students, All Grades (Includes AE) [District]",
    "Grades 1-8 Students [District]", "Grades 9-12 Students [District]",
    "Prekindergarten Students [District]", "Kindergarten Students [District]",
    "Grade 1 Students [District]", "Grade 2 Students [District]",
    "Grade 3 Students [District]", "Grade 4 Students [District]",
    "Grade 5 Students [District]", "Grade 6 Students [District]",
    "Grade 7 Students [District]", "Grade 8 Students [District]",
    "Grade 9 Students [District]", "Grade 10 Students [District]",
    "Grade 11 Students [District]", "Grade 12 Students [District]",
    "Grade 13 Students [District]", "Ungraded Students [District]",
    "Adult Education Students [District]", "Male Students [District]",
    "Female Students [District]",
    "American Indian/Alaska Native Students [District]",
    "Asian or Asian/Pacific Islander Students [District]",
    "Hispanic Students [District]",
    "Black or African American Students [District]",
    "White Students [District]",
    "Nat. Hawaiian or Other Pacific Isl. Students [District]",
    "Two or More Races Students [District]", "Total Race/Ethnicity [District]",
    "American Indian/Alaska Native - male [District]",
    "American Indian/Alaska Native - female [District]",
    "Asian or Asian/Pacific Islander - male [District]",
    "Asian or Asian/Pacific Islander - female [District]",
    "Hispanic - male [District]", "Hispanic - female [District]",
    "Black or African American - male [District]",
    "Black or African American - female [District]", "White - male [District]",
    "White - female [District]",
    "Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Two or More Races - male [District]",
    "Two or More Races - female [District]",
    "Prekindergarten Students - male [District]",
    "Prekindergarten Students - female [District]",
    "Kindergarten Students - male [District]",
    "Kindergarten Students - female [District]",
    "Grade 1 Students - male [District]",
    "Grade 1 Students - female [District]",
    "Grade 2 Students - male [District]",
    "Grade 2 Students - female [District]",
    "Grade 3 Students - male [District]",
    "Grade 3 Students - female [District]",
    "Grade 4 Students - male [District]",
    "Grade 4 Students - female [District]",
    "Grade 5 Students - male [District]",
    "Grade 5 Students - female [District]",
    "Grade 6 Students - male [District]",
    "Grade 6 Students - female [District]",
    "Grade 7 Students - male [District]",
    "Grade 7 Students - female [District]",
    "Grade 8 Students - male [District]",
    "Grade 8 Students - female [District]",
    "Grade 9 Students - male [District]",
    "Grade 9 Students - female [District]",
    "Grade 10 Students - male [District]",
    "Grade 10 Students - female [District]",
    "Grade 11 Students - male [District]",
    "Grade 11 Students - female [District]",
    "Grade 12 Students - male [District]",
    "Grade 12 Students - female [District]",
    "Grade 13 Students - male [District]",
    "Grade 13 Students - female [District]",
    "Ungraded Students - male [District]",
    "Ungraded Students - female [District]",
    "Adult Education Students - male [District]",
    "Adult Education Students - female [District]",
    "Prekindergarten Students - American Indian/Alaska Native [District]",
    "Prekindergarten Students - Asian or Asian/Pacific Islander [District]",
    "Prekindergarten Students - Hispanic [District]",
    "Prekindergarten Students - Black or African American [District]",
    "Prekindergarten Students - White [District]",
    "Prekindergarten Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Prekindergarten Students, Two or More Races [District]",
    "Kindergarten Students - American Indian/Alaska Native [District]",
    "Kindergarten Students - Asian or Asian/Pacific Islander [District]",
    "Kindergarten Students - Hispanic [District]",
    "Kindergarten Students - Black or African American [District]",
    "Kindergarten Students, White [District]",
    "Kindergarten Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Kindergarten Students, Two or More Races [District]",
    "Grade 1 Students - American Indian/Alaska Native [District]",
    "Grade 1 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 1 Students - Hispanic [District]",
    "Grade 1 Students - Black or African American [District]",
    "Grade 1 Students - White [District]",
    "Grade 1 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 1 Students - Two or More Races [District]",
    "Grade 2 Students - American Indian/Alaska Native [District]",
    "Grade 2 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 2 Students - Hispanic [District]",
    "Grade 2 Students - Black or African American [District]",
    "Grade 2 Students - White [District]",
    "Grade 2 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 2 Students - Two or More Races [District]",
    "Grade 3 Students - American Indian/Alaska Native [District]",
    "Grade 3 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 3 Students - Hispanic [District]",
    "Grade 3 Students - Black or African American [District]",
    "Grade 3 Students - White [District]",
    "Grade 3 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 3 Students - Two or More Races [District]",
    "Grade 4 Students - American Indian/Alaska Native [District]",
    "Grade 4 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 4 Students - Hispanic [District]",
    "Grade 4 Students - Black or African American [District]",
    "Grade 4 Students - White [District]",
    "Grade 4 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 4 Students - Two or More Races [District]",
    "Grade 5 Students - American Indian/Alaska Native [District]",
    "Grade 5 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 5 Students - Hispanic [District]",
    "Grade 5 Students - Black or African American [District]",
    "Grade 5 Students - White [District]",
    "Grade 5 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 5 Students - Two or More Races [District]",
    "Grade 6 Students - American Indian/Alaska Native [District]",
    "Grade 6 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 6 Students - Hispanic [District]",
    "Grade 6 Students - Black or African American [District]",
    "Grade 6 Students - White [District]",
    "Grade 6 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 6 Students - Two or More Races [District]",
    "Grade 7 Students - American Indian/Alaska Native [District]",
    "Grade 7 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 7 Students - Hispanic [District]",
    "Grade 7 Students - Black or African American [District]",
    "Grade 7 Students - White [District]",
    "Grade 7 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 7 Students - Two or More Races [District]",
    "Grade 8 Students - American Indian/Alaska Native [District]",
    "Grade 8 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 8 Students - Hispanic [District]",
    "Grade 8 Students - Black or African American [District]",
    "Grade 8 Students - White [District]",
    "Grade 8 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 8 Students - Two or More Races [District]",
    "Grade 9 Students - American Indian/Alaska Native [District]",
    "Grade 9 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 9 Students - Hispanic [District]",
    "Grade 9 Students - Black or African American [District]",
    "Grade 9 Students - White [District]",
    "Grade 9 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 9 Students - Two or More Races [District]",
    "Grade 10 Students - American Indian/Alaska Native [District]",
    "Grade 10 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 10 Students - Hispanic [District]",
    "Grade 10 Students - Black or African American [District]",
    "Grade 10 Students - White [District]",
    "Grade 10 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 10 Students - Two or More Races [District]",
    "Grade 11 Students - American Indian/Alaska Native [District]",
    "Grade 11 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 11 Students - Hispanic [District]",
    "Grade 11 Students - Black or African American [District]",
    "Grade 11 Students - White [District]",
    "Grade 11 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 11 Students - Two or More Races [District]",
    "Grade 12 Students - American Indian/Alaska Native [District]",
    "Grade 12 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 12 Students - Hispanic [District]",
    "Grade 12 Students - Black or African American [District]",
    "Grade 12 Students - White [District]",
    "Grade 12 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 12 Students - Two or More Races [District]",
    "Grade 13 Students - American Indian/Alaska Native [District]",
    "Grade 13 Students - Asian or Asian/Pacific Islander [District]",
    "Grade 13 Students - Hispanic [District]",
    "Grade 13 Students - Black or African American [District]",
    "Grade 13 Students - White [District]",
    "Grade 13 Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Grade 13 Students - Two or More Races [District]",
    "Ungraded Students - American Indian/Alaska Native [District]",
    "Ungraded Students - Asian or Asian/Pacific Islander [District]",
    "Ungraded Students - Hispanic [District]",
    "Ungraded Students - Black or African American [District]",
    "Ungraded Students - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Ungraded Students - White [District]",
    "Ungraded Students - Two or More Races [District]",
    "Adult Education Students - American Indian/Alaska Native [District]",
    "Adult Education Students - Asian or Asian/Pacific Islander [District]",
    "Adult Education Students - Hispanic [District]",
    "Adult Education Students - Black or African American [District]",
    "Adult Education Students - White [District]",
    "Adult Education - Nat. Hawaiian or Other Pacific Isl. [District]",
    "Adult Education Students - Two or More Races [District]",
    "Prekindergarten Students - American Indian/Alaska Native - male [District]",
    "Prekindergarten Students - American Indian/Alaska Native - female [District]",
    "Prekindergarten Students - Asian or Asian/Pacific Islander - male [District]",
    "Prekindergarten Students - Asian or Asian/Pacific Islander - female [District]",
    "Prekindergarten Students - Hispanic - male [District]",
    "Prekindergarten Students - Hispanic - female [District]",
    "Prekindergarten Students - Black or African American - male [District]",
    "Prekindergarten Students - Black or African American - female [District]",
    "Prekindergarten Students - White - male [District]",
    "Prekindergarten Students - White - female [District]",
    "Prekindergarten Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Prekindergarten Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Prekindergarten Students - Two or More Races - male [District]",
    "Prekindergarten Students - Two or More Races - female [District]",
    "Kindergarten Students - American Indian/Alaska Native - male [District]",
    "Kindergarten Students - American Indian/Alaska Native - female [District]",
    "Kindergarten Students - Asian or Asian/Pacific Islander - male [District]",
    "Kindergarten Students - Asian or Asian/Pacific Islander - female [District]",
    "Kindergarten Students - Hispanic - male [District]",
    "Kindergarten Students - Hispanic - female [District]",
    "Kindergarten Students - Black or African American - male [District]",
    "Kindergarten Students - Black or African American - female [District]",
    "Kindergarten Students - White - male [District]",
    "Kindergarten Students - White - female [District]",
    "Kindergarten Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Kindergarten Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Kindergarten Students - Two or More Races - male [District]",
    "Kindergarten Students - Two or More Races - female [District]",
    "Grade 1 Students - American Indian/Alaska Native - male [District]",
    "Grade 1 Students - American Indian/Alaska Native - female [District]",
    "Grade 1 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 1 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 1 Students - Hispanic - male [District]",
    "Grade 1 Students - Hispanic - female [District]",
    "Grade 1 Students - Black or African American - male [District]",
    "Grade 1 Students - Black or African American - female [District]",
    "Grade 1 Students - White - male [District]",
    "Grade 1 Students - White - female [District]",
    "Grade 1 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 1 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 1 Students - Two or More Races - male [District]",
    "Grade 1 Students - Two or More Races - female [District]",
    "Grade 2 Students - American Indian/Alaska Native - male [District]",
    "Grade 2 Students - American Indian/Alaska Native - female [District]",
    "Grade 2 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 2 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 2 Students - Hispanic - male [District]",
    "Grade 2 Students - Hispanic - female [District]",
    "Grade 2 Students - Black or African American - male [District]",
    "Grade 2 Students - Black or African American - female [District]",
    "Grade 2 Students - White - male [District]",
    "Grade 2 Students - White - female [District]",
    "Grade 2 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 2 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 2 Students - Two or More Races - male [District]",
    "Grade 2 Students - Two or More Races - female [District]",
    "Grade 3 Students - American Indian/Alaska Native - male [District]",
    "Grade 3 Students - American Indian/Alaska Native - female [District]",
    "Grade 3 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 3 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 3 Students - Hispanic - male [District]",
    "Grade 3 Students - Hispanic - female [District]",
    "Grade 3 Students - Black or African American - male [District]",
    "Grade 3 Students - Black or African American - female [District]",
    "Grade 3 Students - White - male [District]",
    "Grade 3 Students - White - female [District]",
    "Grade 3 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 3 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 3 Students - Two or More Races - male [District]",
    "Grade 3 Students - Two or More Races - female [District]",
    "Grade 4 Students - American Indian/Alaska Native - male [District]",
    "Grade 4 Students - American Indian/Alaska Native - female [District]",
    "Grade 4 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 4 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 4 Students - Hispanic - male [District]",
    "Grade 4 Students - Hispanic - female [District]",
    "Grade 4 Students - Black or African American - male [District]",
    "Grade 4 Students - Black or African American - female [District]",
    "Grade 4 Students - White - male [District]",
    "Grade 4 Students - White - female [District]",
    "Grade 4 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 4 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 4 Students - Two or More Races - male [District]",
    "Grade 4 Students - Two or More Races - female [District]",
    "Grade 5 Students - American Indian/Alaska Native - male [District]",
    "Grade 5 Students - American Indian/Alaska Native - female [District]",
    "Grade 5 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 5 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 5 Students - Hispanic - male [District]",
    "Grade 5 Students - Hispanic - female [District]",
    "Grade 5 Students - Black or African American - male [District]",
    "Grade 5 Students - Black or African American - female [District]",
    "Grade 5 Students - White - male [District]",
    "Grade 5 Students - White - female [District]",
    "Grade 5 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 5 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 5 Students - Two or More Races - male [District]",
    "Grade 5 Students - Two or More Races - female [District]",
    "Grade 6 Students - American Indian/Alaska Native - male [District]",
    "Grade 6 Students - American Indian/Alaska Native - female [District]",
    "Grade 6 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 6 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 6 Students - Hispanic - male [District]",
    "Grade 6 Students - Hispanic - female [District]",
    "Grade 6 Students - Black or African American - male [District]",
    "Grade 6 Students - Black or African American - female [District]",
    "Grade 6 Students - White - male [District]",
    "Grade 6 Students - White - female [District]",
    "Grade 6 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 6 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 6 Students- Two or More Races - male [District]",
    "Grade 6 Students - Two or More Races - female [District]",
    "Grade 7 Students - American Indian/Alaska Native - male [District]",
    "Grade 7 Students - American Indian/Alaska Native - female [District]",
    "Grade 7 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 7 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 7 Students - Hispanic - male [District]",
    "Grade 7 Students - Hispanic - female [District]",
    "Grade 7 Students - Black or African American - male [District]",
    "Grade 7 Students - Black or African American - female [District]",
    "Grade 7 Students - White - male [District]",
    "Grade 7 Students - White - female [District]",
    "Grade 7 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 7 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 7 Students - Two or More Races - male [District]",
    "Grade 7 Students - Two or More Races - female [District]",
    "Grade 8 Students - American Indian/Alaska Native - male [District]",
    "Grade 8 Students - American Indian/Alaska Native - female [District]",
    "Grade 8 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 8 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 8 Students- Hispanic - male [District]",
    "Grade 8 Students - Hispanic - female [District]",
    "Grade 8 Students - Black or African American - male [District]",
    "Grade 8 Students - Black or African American - female [District]",
    "Grade 8 Students - White - male [District]",
    "Grade 8 Students - White - female [District]",
    "Grade 8 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 8 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 8 Students - Two or More Races - male [District]",
    "Grade 8 Students - Two or More Races - female [District]",
    "Grade 9 Students - American Indian/Alaska Native - male [District]",
    "Grade 9 Students - American Indian/Alaska Native - female [District]",
    "Grade 9 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 9 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 9 Students - Hispanic - male [District]",
    "Grade 9 Students - Hispanic - female [District]",
    "Grade 9 Students - Black or African American - male [District]",
    "Grade 9 Students - Black or African American - female [District]",
    "Grade 9 Students - White - male [District]",
    "Grade 9 Students - White - female [District]",
    "Grade 9 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 9 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 9 Students - Two or More Races - male [District]",
    "Grade 9 Students - Two or More Races - female [District]",
    "Grade 10 Students - American Indian/Alaska Native - male [District]",
    "Grade 10 Students - American Indian/Alaska Native - female [District]",
    "Grade 10 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 10 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 10 Students - Hispanic - male [District]",
    "Grade 10 Students - Hispanic - female [District]",
    "Grade 10 Students - Black or African American - male [District]",
    "Grade 10 Students - Black or African American - female [District]",
    "Grade 10 Students - White - male [District]",
    "Grade 10 Students - White - female [District]",
    "Grade 10 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 10 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 10 Students - Two or More Races - male [District]",
    "Grade 10 Students - Two or More Races - female [District]",
    "Grade 11 Students - American Indian/Alaska Native - male [District]",
    "Grade 11 Students - American Indian/Alaska Native - female [District]",
    "Grade 11 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 11 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 11 Students - Hispanic - male [District]",
    "Grade 11 Students - Hispanic - female [District]",
    "Grade 11 Students - Black or African American - male [District]",
    "Grade 11 Students - Black or African American - female [District]",
    "Grade 11 Students - White - male [District]",
    "Grade 11 Students - White - female [District]",
    "Grade 11 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 11 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 11 Students - Two or More Races - male [District]",
    "Grade 11 Students - Two or More Races - female [District]",
    "Grade 12 Students - American Indian/Alaska Native - male [District]",
    "Grade 12 Students - American Indian/Alaska Native - female [District]",
    "Grade 12 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 12 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 12 Students - Hispanic - male [District]",
    "Grade 12 Students - Hispanic - female [District]",
    "Grade 12 Students - Black or African American - male [District]",
    "Grade 12 Students - Black or African American - female [District]",
    "Grade 12 Students - White - male [District]",
    "Grade 12 Students - White - female [District]",
    "Grade 12 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 12 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 12 Students - Two or More Races - male [District]",
    "Grade 12 Students - Two or More Races - female [District]",
    "Grade 13 Students - American Indian/Alaska Native - male [District]",
    "Grade 13 Students - American Indian/Alaska Native - female [District]",
    "Grade 13 Students - Asian or Asian/Pacific Islander - male [District]",
    "Grade 13 Students - Asian or Asian/Pacific Islander - female [District]",
    "Grade 13 Students - Hispanic - male [District]",
    "Grade 13 Students - Hispanic - female [District]",
    "Grade 13 Students - Black or African American - male [District]",
    "Grade 13 Students - Black or African American - female [District]",
    "Grade 13 Students - White - male [District]",
    "Grade 13 Students - White - female [District]",
    "Grade 13 Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Grade 13 Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Grade 13 Students - Two or More Races - male [District]",
    "Grade 13 Students - Two or More Races - female [District]",
    "Ungraded Students - American Indian/Alaska Native - male [District]",
    "Ungraded Students - American Indian/Alaska Native - female [District]",
    "Ungraded Students - Asian or Asian/Pacific Islander - male [District]",
    "Ungraded Students - Asian or Asian/Pacific Islander - female [District]",
    "Ungraded Students - Hispanic - male [District]",
    "Ungraded Students - Hispanic - female [District]",
    "Ungraded Students - Black or African American - male [District]",
    "Ungraded Students - Black or African American - female [District]",
    "Ungraded Students - White - male [District]",
    "Ungraded Students - White - female [District]",
    "Ungraded Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Ungraded Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Ungraded Students - Two or More Races - male [District]",
    "Ungraded Students - Two or More Races - female [District]",
    "Adult Education Students - American Indian/Alaska Native - male [District]",
    "Adult Education Students - American Indian/Alaska Native - female [District]",
    "Adult Education Students - Asian or Asian/Pacific Islander - male [District]",
    "Adult Education Students - Asian or Asian/Pacific Islander - female [District]",
    "Adult Education Students - Hispanic - male [District]",
    "Adult Education Students - Hispanic - female [District]",
    "Adult Education Students - Black or African American - male [District]",
    "Adult Education Students - Black or African American - female [District]",
    "Adult Education Students - White - male [District]",
    "Adult Education Students - White - female [District]",
    "Adult Education Students - Nat. Hawaiian or Other Pacific Isl. - male [District]",
    "Adult Education Students - Nat. Hawaiian or Other Pacific Isl. - female [District]",
    "Adult Education Students - Two or More Races - male [District]",
    "Adult Education Students - Two or More Races - female [District]",
    "Full-Time Equivalent (FTE) Teachers [District]",
    "Pupil/Teacher Ratio [District]", "Prekindergarten Teachers [District]",
    "Kindergarten Teachers [District]", "Elementary Teachers [District]",
    "Secondary Teachers [District]", "Ungraded Teachers [District]",
    "Total Staff [District]", "Paraprofessionals/Instructional Aides [District]",
    "Instructional Coordinators [District]",
    "Elementary School Counselor [District]",
    "Secondary School Counselor [District]",
    "Other Guidance Counselors [District]",
    "Total Guidance Counselors [District]",
    "Librarians/media specialists [District]", "Media Support Staff [District]",
    "LEA Administrators [District]",
    "LEA Administrative Support Staff [District]",
    "School Administrators [District]",
    "School Administrative Support Staff [District]",
    "Student Support Services Staff (w/o Psychology) [District]",
    "School Psychologist [District]", "Other Support Services Staff [District]",
    "Student Support Services Staff [District]"
]

KEY_COLUMNS_PUBLIC = ["13392"]
KEY_COLUMNS_PRIVATE = ["13391"]
KEY_COLUMNS_DISTRICT = ["13393"]
