# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import pandas as pd
import unittest

from pandas.testing import assert_frame_equal
from tools.import_differ import import_differ
from tools.import_differ import differ_utils

module_dir = os.path.dirname(__file__)


class TestImportDiffer(unittest.TestCase):
    '''
  Test Class to compare expected output in test/ directory to the
  output generated by ImportDiffer class
  '''

    def test_diff_analysis(self):
        current_data = os.path.join(module_dir, 'test', 'current.mcf')
        previous_data = os.path.join(module_dir, 'test', 'previous.mcf')
        output_location = os.path.join(module_dir)
        self.differ = import_differ.ImportDiffer(current_data, previous_data,
                                                 output_location, 'differ.jar',
                                                 'project-1', 'test', 'mcf',
                                                 'native')
        current_df = differ_utils.load_mcf_file(self.differ.current_data)
        previous_df = differ_utils.load_mcf_file(self.differ.previous_data)
        diff = self.differ.generate_diff(previous_df, current_df)
        summary, result = self.differ.point_analysis(diff)
        result = pd.read_csv(
            os.path.join(module_dir, 'test', 'point_analysis_summary.csv'))
        assert_frame_equal(summary, result)

        summary, result = self.differ.series_analysis(diff)
        result = pd.read_csv(
            os.path.join(module_dir, 'test', 'series_analysis_summary.csv'))
        assert_frame_equal(summary, result)


if __name__ == '__main__':
    unittest.main()
