# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import pandas as pd
import unittest

from pandas.testing import assert_frame_equal
from tools.import_differ import import_differ
from tools.import_differ import differ_utils

module_dir = os.path.dirname(__file__)


class TestImportDiffer(unittest.TestCase):
    '''
  Test Class to compare expected output in test/ directory to the
  output generated by ImportDiffer class
  '''

    def test_diff_analysis(self):
        groupby_columns = 'variableMeasured,observationAbout,observationDate'
        value_columns = 'value'
        job_name = 'test'
        current_data = os.path.join(module_dir, job_name, 'current.mcf')
        previous_data = os.path.join(module_dir, job_name, 'previous.mcf')
        output_location = os.path.join(module_dir)

        differ = import_differ.ImportDiffer(current_data, previous_data,
                                            output_location, 'differ.jar',
                                            'project-1', job_name, 'mcf',
                                            'local')
        current = differ_utils.load_mcf_file(current_data)
        previous = differ_utils.load_mcf_file(previous_data)

        diff_path = os.path.join(module_dir, job_name, 'diff.csv')
        diff = differ.process_data(diff_path)

        summary, result = differ.point_analysis(diff)
        result = pd.read_csv(
            os.path.join(module_dir, job_name, 'point_analysis_summary.csv'))
        assert_frame_equal(summary, result)

        summary, result = differ.series_analysis(diff)
        result = pd.read_csv(
            os.path.join(module_dir, job_name, 'series_analysis_summary.csv'))
        assert_frame_equal(summary, result)


if __name__ == '__main__':
    unittest.main()
