# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import json
import os
import pandas as pd
import unittest

from pandas.testing import assert_frame_equal
from tools.import_differ import import_differ
from tools.import_differ import differ_utils

module_dir = os.path.dirname(__file__)


class TestImportDiffer(unittest.TestCase):
    '''
  Test Class to compare expected output in test/ directory to the
  output generated by ImportDiffer class
  '''

    def test_diff_analysis(self):
        current_data = os.path.join(module_dir, 'test', 'current', '*.mcf')
        previous_data = os.path.join(module_dir, 'test', 'previous', '*.mcf')
        output_location = os.path.join(module_dir, 'test', 'output')
        if os.path.exists(output_location):
            import shutil
            shutil.rmtree(output_location)
        os.makedirs(output_location)

        differ = import_differ.ImportDiffer(current_data=current_data,
                                            previous_data=previous_data,
                                            output_location=output_location,
                                            runner_mode='native')
        differ.run_differ()

        # Check for expected files
        expected_files = [
            'nodes-added.mcf', 'nodes-deleted.mcf', 'nodes-modified.mcf',
            'differ_summary.json'
        ]

        for f in expected_files:
            file_path = os.path.join(output_location, f)
            self.assertTrue(os.path.exists(file_path),
                            f"File {f} was not generated")

        # Verify content of the combined MCF files
        for f_name in [
                'nodes-added.mcf', 'nodes-deleted.mcf', 'nodes-modified.mcf'
        ]:
            with open(os.path.join(output_location, f_name), 'r') as f:
                content = f.read().strip()

            with open(os.path.join(module_dir, 'test', 'results', f_name),
                      'r') as f:
                expected_content = f.read().strip()

            # Split into individual nodes, strip whitespace, and sort to avoid ordering issues
            actual_nodes = sorted([
                node.strip() for node in content.split('\n\n') if node.strip()
            ])
            expected_nodes = sorted([
                node.strip()
                for node in expected_content.split('\n\n')
                if node.strip()
            ])

            self.assertListEqual(actual_nodes, expected_nodes)

        # Verify content of the summary file
        with open(os.path.join(output_location, 'differ_summary.json'),
                  'r') as f:
            summary_content = json.load(f)

        with open(
                os.path.join(module_dir, 'test', 'results',
                             'differ_summary.json'), 'r') as f:
            expected_summary_content = json.load(f)

        # The version paths might differ based on where the test is run,
        # so we normalize or remove them for the comparison
        summary_content.pop('current_version', None)
        summary_content.pop('previous_version', None)
        expected_summary_content.pop('current_version', None)
        expected_summary_content.pop('previous_version', None)

        self.assertDictEqual(summary_content, expected_summary_content)

        if os.path.exists(output_location):
            import shutil
            shutil.rmtree(output_location)


if __name__ == '__main__':
    unittest.main()
