"""
Renaming all the word "Liquefied" to "Liquified" as source has data with "Liquified".``
"""
new_mapping_names = {
    "Annual_Consumption_Fuel_OtherSector_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_OtherSector_LiquifiedPetroleumGas",
    "Annual_Generation_Fuel_LiquefiedPetroleumGas":
        "Annual_Generation_Fuel_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_Households_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_Households_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_Manufacturing_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_Manufacturing_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_OtherManufacturingIndustry_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_OtherManufacturingIndustry_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_CommerceAndPublicServices_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_CommerceAndPublicServices_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_OtherIndustry_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_OtherIndustry_LiquifiedPetroleumGas",
    "Annual_Generation_Fuel_LiquefiedPetroleumGas_Refinery":
        "Annual_Generation_Fuel_LiquifiedPetroleumGas_Refinery",
    "Annual_Exports_Fuel_LiquefiedPetroleumGas":
        "Annual_Exports_Fuel_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_UnspecifiedSector_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_UnspecifiedSector_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_TransportIndustry_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_TransportIndustry_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_RoadTransport_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_RoadTransport_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_Agriculture_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_Agriculture_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_FoodAndTobaccoIndustry_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_FoodAndTobaccoIndustry_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_EnergyIndustry_LiquefiedPetroleumGas_EnergyIndustryOwnUse":
        "Annual_Consumption_Fuel_EnergyIndustry_LiquifiedPetroleumGas_EnergyIndustryOwnUse",
    "Annual_Consumption_Fuel_ChemicalPetrochemicalIndustry_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_ChemicalPetrochemicalIndustry_LiquifiedPetroleumGas",
    "Annual_Generation_Fuel_LiquefiedPetroleumGas_PetroleumPlants":
        "Annual_Generation_Fuel_LiquifiedPetroleumGas_PetroleumPlants",
    "Annual_Consumption_Fuel_MiningAndQuarryingIndustry_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_MiningAndQuarryingIndustry_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_IronSteel_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_IronSteel_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_ConstructionIndustry_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_ConstructionIndustry_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_NonMetallicMineralsIndustry_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_NonMetallicMineralsIndustry_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_MachineryIndustry_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_MachineryIndustry_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_FuelTransformationIndustry_LiquefiedPetroleumGas_FuelTransformation":
        "Annual_Consumption_Fuel_FuelTransformationIndustry_LiquifiedPetroleumGas_FuelTransformation",
    "Annual_Consumption_Fuel_OilRefineries_LiquefiedPetroleumGas_EnergyIndustryOwnUse":
        "Annual_Consumption_Fuel_OilRefineries_LiquifiedPetroleumGas_EnergyIndustryOwnUse",
    "Annual_Consumption_Fuel_PaperPulpPrintIndustry_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_PaperPulpPrintIndustry_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_TextileAndLeatherIndustry_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_TextileAndLeatherIndustry_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_WoodAndWoodProductsIndustry_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_TextileAndLeatherIndustry_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_NonFerrousMetalsIndustry_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_NonFerrousMetalsIndustry_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_TransportEquipmentIndustry_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_TransportEquipmentIndustry_LiquifiedPetroleumGas",
    "Annual_Loss_Fuel_LiquefiedPetroleumGas":
        "Annual_Loss_Fuel_LiquifiedPetroleumGas",
    "Annual_ProductReclassification_Fuel_LiquefiedPetroleumGas":
        "Annual_ProductReclassification_Fuel_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_LiquefiedNaturalGasPlants_NaturalGas_EnergyIndustryOwnUse":
        "Annual_Consumption_Fuel_LiquifiedNaturalGasPlants_NaturalGas_EnergyIndustryOwnUse",
    "Annual_Consumption_Fuel_OtherTransport_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_OtherTransport_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_Industry_LiquefiedPetroleumGas_EnergyIndustryOwnUse":
        "Annual_Consumption_Fuel_Industry_LiquifiedPetroleumGas_EnergyIndustryOwnUse",
    "Annual_Consumption_Fuel_OilGasExtraction_LiquefiedPetroleumGas_EnergyIndustryOwnUse":
        "Annual_Consumption_Fuel_OilGasExtraction_LiquifiedPetroleumGas_EnergyIndustryOwnUse",
    "Annual_Consumption_Fuel_GasWorks_LiquefiedPetroleumGas_FuelTransformation":
        "Annual_Consumption_Fuel_GasWorks_LiquifiedPetroleumGas_FuelTransformation",
    "Annual_Consumption_Fuel_AutoProducerCombinedHeatPowerPlants_LiquefiedPetroleumGas_FuelTransformation":
        "Annual_Consumption_Fuel_AutoProducerCombinedHeatPowerPlants_LiquifiedPetroleumGas_FuelTransformation",
    "Annual_Consumption_Fuel_AutoProducerElectricityPowerPlants_LiquefiedPetroleumGas_FuelTransformation":
        "Annual_Consumption_Fuel_AutoProducerElectricityPowerPlants_LiquifiedPetroleumGas_FuelTransformation",
    "Annual_Consumption_Fuel_PetrochemicalPlants_LiquefiedPetroleumGas_FuelTransformation":
        "Annual_Consumption_Fuel_PetrochemicalPlants_LiquifiedPetroleumGas_FuelTransformation",
    "Annual_Consumption_Fuel_ElectricityGeneration_LiquefiedPetroleumGas_EnergyIndustryOwnUse":
        "Annual_Consumption_Fuel_ElectricityGeneration_LiquifiedPetroleumGas_EnergyIndustryOwnUse",
    "Annual_Consumption_Fuel_MainActivityProducerHeatPowerPlants_LiquefiedPetroleumGas_FuelTransformation":
        "Annual_Consumption_Fuel_MainActivityProducerHeatPowerPlants_LiquifiedPetroleumGas_FuelTransformation",
    "Annual_Consumption_Fuel_MainActivityProducerElectricityPowerPlants_LiquefiedPetroleumGas_FuelTransformation":
        "Annual_Consumption_Fuel_MainActivityProducerElectricityPowerPlants_LiquifiedPetroleumGas_FuelTransformation",
    "Annual_Consumption_Fuel_GasWorks_LiquefiedPetroleumGas_EnergyIndustryOwnUse":
        "Annual_Consumption_Fuel_GasWorks_LiquifiedPetroleumGas_EnergyIndustryOwnUse",
    "Annual_Consumption_Fuel_AutoProducerHeatPowerPlants_LiquefiedPetroleumGas_FuelTransformation":
        "Annual_Consumption_Fuel_AutoProducerHeatPowerPlants_LiquifiedPetroleumGas_FuelTransformation",
    "Annual_Consumption_Fuel_MainActivityProducerCombinedHeatPowerPlants_LiquefiedPetroleumGas_FuelTransformation":
        "Annual_Consumption_Fuel_MainActivityProducerCombinedHeatPowerPlants_LiquifiedPetroleumGas_FuelTransformation",
    "Annual_Consumption_Fuel_CoalMines_LiquefiedPetroleumGas_EnergyIndustryOwnUse":
        "Annual_Consumption_Fuel_CoalMines_LiquifiedPetroleumGas_EnergyIndustryOwnUse",
    "Annual_Consumption_Fuel_RailTransport_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_RailTransport_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_DomesticNavigationTransport_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_DomesticNavigationTransport_LiquifiedPetroleumGas",
    "Annual_Consumption_Electricity_LiquefiedNaturalGasPlants_EnergyIndustryOwnUse":
        "Annual_Consumption_Electricity_LiquifiedNaturalGasPlants_EnergyIndustryOwnUse",
    "Annual_Consumption_Fuel_OtherIndustry_LiquefiedPetroleumGas_FuelTransformation":
        "Annual_Consumption_Fuel_OtherIndustry_LiquifiedPetroleumGas_FuelTransformation",
    "Annual_Consumption_Fuel_NaturalGasPlants_LiquefiedPetroleumGas_FuelTransformation":
        "Annual_Consumption_Fuel_NaturalGasPlants_LiquifiedPetroleumGas_FuelTransformation",
    "Annual_Consumption_Fuel_PipelineTransport_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_PipelineTransport_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_BlastFurnaces_LiquefiedPetroleumGas_EnergyIndustryOwnUse":
        "Annual_Consumption_Fuel_BlastFurnaces_LiquifiedPetroleumGas_EnergyIndustryOwnUse",
    "Annual_Consumption_Fuel_CokeOvens_LiquefiedPetroleumGas_EnergyIndustryOwnUse":
        "Annual_Consumption_Fuel_CokeOvens_LiquifiedPetroleumGas_EnergyIndustryOwnUse",
    "Annual_Consumption_Fuel_DomesticAviationTransport_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_DomesticAviationTransport_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_CokeOvens_LiquefiedPetroleumGas_FuelTransformation":
        "Annual_Consumption_Fuel_DomesticAviationTransport_LiquifiedPetroleumGas",
    "Annual_Consumption_Energy_LiquefiedNaturalGasPlants_Heat_EnergyIndustryOwnUse":
        "Annual_Consumption_Energy_LiquifiedNaturalGasPlants_Heat_EnergyIndustryOwnUse",
    "Annual_Consumption_Fuel_ElectricityGeneration_LiquefiedPetroleumGas_FuelTransformation":
        "Annual_Consumption_Fuel_ElectricityGeneration_LiquifiedPetroleumGas_FuelTransformation",
    "Annual_Consumption_Fuel_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_LiquifiedPetroleumGas",
    "Annual_Consumption_Fuel_LiquefiedPetroleumGas_NonEnergyUse":
        "Annual_Consumption_Fuel_LiquifiedPetroleumGas_NonEnergyUse",
    "Annual_Consumption_Fuel_WoodAndWoodProductsIndustry_LiquefiedPetroleumGas":
        "Annual_Consumption_Fuel_WoodAndWoodProductsIndustry_LiquifiedPetroleumGas",
    "Annual_Generation_Fuel_LiquefiedPetroleumGas_PetroleumPlants":
        "Annual_Generation_Fuel_LiquifiedPetroleumGas_PetroleumPlants",
    "Annual_Imports_Fuel_LiquefiedPetroleumGas":
        "Annual_Imports_Fuel_LiquifiedPetroleumGas",
    "Annual_Receipts_Fuel_LiquefiedPetroleumGas":
        "Annual_Receipts_Fuel_LiquifiedPetroleumGas",
    "AnnualChange_Stocks_Fuel_LiquefiedPetroleumGas":
        "AnnualChange_Stocks_Fuel_LiquifiedPetroleumGas"
}
