#!/bin/bash
set -e

SCRIPT_PATH=$(realpath "$(dirname "$0")")

python3 "$SCRIPT_PATH/../../../tools/statvar_importer/stat_var_processor.py" --input_data="$SCRIPT_PATH/input_files/by_age_and_state/*.csv" --pv_map="$SCRIPT_PATH/brfss_asthma_by_age_and_state_pvmap.csv" --config_file="$SCRIPT_PATH/common_metadata.csv" --output_path="$SCRIPT_PATH/output_files/brfss_asthma_by_age_and_state_output" --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --places_resolved_csv="$SCRIPT_PATH/places_resolver.csv" --statvar_dcid_remap_csv="$SCRIPT_PATH/statvar_remap.csv" || { echo "Error: Processing brfss_asthma_by_age_and_state failed!"; exit 1; }

python3 "$SCRIPT_PATH/../../../tools/statvar_importer/stat_var_processor.py" --input_data="$SCRIPT_PATH/input_files/by_education_and_state/*.csv" --pv_map="$SCRIPT_PATH/brfss_asthma_by_education_and_state_pvmap.csv" --config_file="$SCRIPT_PATH/common_metadata.csv" --output_path="$SCRIPT_PATH/output_files/brfss_asthma_by_education_and_state_output" --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --places_resolved_csv="$SCRIPT_PATH/places_resolver.csv" --statvar_dcid_remap_csv="$SCRIPT_PATH/statvar_remap.csv" || { echo "Error: Processing brfss_asthma_by_education_and_state failed!"; exit 1; }

python3 "$SCRIPT_PATH/../../../tools/statvar_importer/stat_var_processor.py" --input_data="$SCRIPT_PATH/input_files/by_income_and_state/*.csv" --pv_map="$SCRIPT_PATH/brfss_asthma_by_income_and_state_pvmap.csv" --config_file="$SCRIPT_PATH/common_metadata.csv" --output_path="$SCRIPT_PATH/output_files/brfss_asthma_by_income_and_state_output" --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --places_resolved_csv="$SCRIPT_PATH/places_resolver.csv" --statvar_dcid_remap_csv="$SCRIPT_PATH/statvar_remap.csv" || { echo "Error: Processing brfss_asthma_by_income_and_state failed!"; exit 1; }

python3 "$SCRIPT_PATH/../../../tools/statvar_importer/stat_var_processor.py" --input_data="$SCRIPT_PATH/input_files/by_race_ethnicity_and_state/*.csv" --pv_map="$SCRIPT_PATH/brfss_asthma_by_race_and_ethnicity_state_pvmap.csv" --config_file="$SCRIPT_PATH/common_metadata.csv" --output_path="$SCRIPT_PATH/output_files/brfss_asthma_by_race_and_ethnicity_state_output" --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --places_resolved_csv="$SCRIPT_PATH/places_resolver.csv" --statvar_dcid_remap_csv="$SCRIPT_PATH/statvar_remap.csv" || { echo "Error: Processing brfss_asthma_by_race_and_ethnicity_state failed!"; exit 1; }

python3 "$SCRIPT_PATH/../../../tools/statvar_importer/stat_var_processor.py" --input_data="$SCRIPT_PATH/input_files/by_sex_and_state/*.csv" --pv_map="$SCRIPT_PATH/brfss_asthma_by_sex_and_state_pvmap.csv" --config_file="$SCRIPT_PATH/metadata_by_sex_and_state.csv" --output_path="$SCRIPT_PATH/output_files/brfss_asthma_by_sex_and_state_output" --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --places_resolved_csv="$SCRIPT_PATH/places_resolver.csv" --statvar_dcid_remap_csv="$SCRIPT_PATH/statvar_remap.csv" || { echo "Error: Processing brfss_asthma_by_sex_and_state failed!"; exit 1; }

python3 "$SCRIPT_PATH/../../../tools/statvar_importer/stat_var_processor.py" --input_data="$SCRIPT_PATH/input_files/overall_by_state/*.csv" --pv_map="$SCRIPT_PATH/brfss_asthma_by_state_pvmap.csv" --config_file="$SCRIPT_PATH/metadata_by_sex_and_state.csv" --output_path="$SCRIPT_PATH/output_files/brfss_asthma_by_state_output" --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --places_resolved_csv="$SCRIPT_PATH/places_resolver.csv" --statvar_dcid_remap_csv="$SCRIPT_PATH/statvar_remap.csv" || { echo "Error: Processing brfss_asthma_by_state failed!"; exit 1; }

echo "All processing steps completed successfully."
exit 0   
