# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import pandas as pd
import unittest

from pandas.testing import assert_frame_equal
from tools.import_validation import import_validation

module_dir = os.path.dirname(__file__)


class TestValidation(unittest.TestCase):
    '''
  Test Class to run compare expected output in test/ directory to the
  output generated by ImportValidation class
  '''

    def test_validation(self):
        result_file = os.path.join(module_dir, 'test', 'test_output.csv')
        config_file = os.path.join(module_dir, 'test', 'test_config.json')
        differ_output = os.path.join(module_dir, 'test', 'differ_output.csv')
        validation_output = os.path.join(module_dir, 'validation_output.csv')

        validation = import_validation.ImportValidation(config_file,
                                                        differ_output, '',
                                                        validation_output)
        validation.run_validations()

        expected = pd.read_csv(result_file)
        actual = pd.read_csv(os.path.join(module_dir, 'validation_output.csv'))
        assert_frame_equal(actual, expected)


if __name__ == '__main__':
    unittest.main()
