runtime: python37
entrypoint: gunicorn --timeout 600 -b :$PORT app.main:app 
env_variables:
    EXECUTOR_PRODUCTION: "True"
    TMPDIR: "/tmp"
basic_scaling:
  max_instances: 1
  idle_timeout: 10m
instance_class: B4_1G