runtime: python37
entrypoint: gunicorn --timeout 600 -b :$PORT app.main:FLASK_APP
env_variables:
    EXECUTOR_PRODUCTION: "True"
    TMPDIR: "/tmp"
basic_scaling:
  max_instances: 5
  idle_timeout: 10m
# 2048 MB RAM and 4.8 GHz CPU.
# See https://cloud.google.com/appengine/docs/standard#instance_classes.
instance_class: B8
