# Builds the docker image of import executor and pushes it to artifact registry.
# 
# Run it using:
# gcloud builds submit --config=cloudbuild.yaml --substitutions=_DOCKER_IMAGE="us-docker.pkg.dev/datcom-ci/gcr.io/dc-import-executor:latest" .

steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'import-automation/executor'
    args: ['build', '-t', '${_DOCKER_IMAGE}', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  '${_DOCKER_IMAGE}']

# Store images in Google Artifact Registry
images:
  - ${_DOCKER_IMAGE}
