#!/bin/bash
set -e

SCRIPT_PATH=$(realpath "$(dirname "$0")")

python3 $SCRIPT_PATH/../../../tools/statvar_importer/stat_var_processor.py --input_data=$SCRIPT_PATH/input_files/students_of_universities_and_colleges_by_professional_field.csv --pv_map=$SCRIPT_PATH/students_of_universities_and_colleges_by_professional_field_pvmap.csv --config_file=$SCRIPT_PATH/mongolia_metadata.csv --output_path=$SCRIPT_PATH/output_files/students_of_universities_and_colleges_by_professional_field_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --places_resolved_csv=$SCRIPT_PATH/mongolia_place_resolver.csv || { echo "Error: Processing students_of_universities_and_colleges_by_professional_field.csv failed!"; exit 1; }

python3 $SCRIPT_PATH/../../../tools/statvar_importer/stat_var_processor.py --input_data=$SCRIPT_PATH/input_files/students_in_teritary_educational_institutions_by_sex_and_educational_degree.csv --pv_map=$SCRIPT_PATH/students_in_teritary_educational_institutions_by_sex_and_educational_degree_pvmap.csv --config_file=$SCRIPT_PATH/mongolia_metadata.csv --output_path=$SCRIPT_PATH/output_files/students_in_teritary_educational_institutions_by_sex_and_educational_degree_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --places_resolved_csv=$SCRIPT_PATH/mongolia_place_resolver.csv || { echo "Error: Processing students_in_teritary_educational_institutions_by_sex_and_educational_degree.csv failed!"; exit 1; }

python3 $SCRIPT_PATH/../../../tools/statvar_importer/stat_var_processor.py --input_data=$SCRIPT_PATH/input_files/number_of_students_in_universities_and_colleges_by_region.csv --pv_map=$SCRIPT_PATH/number_of_students_in_universities_and_colleges_by_region_pvmap.csv --config_file=$SCRIPT_PATH/mongolia_metadata.csv --output_path=$SCRIPT_PATH/output_files/number_of_students_in_universities_and_colleges_by_region_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --places_resolved_csv=$SCRIPT_PATH/mongolia_place_resolver.csv || { echo "Error: Processing number_of_students_in_universities_and_colleges_by_region.csv failed!"; exit 1; }

python3 $SCRIPT_PATH/../../../tools/statvar_importer/stat_var_processor.py --input_data=$SCRIPT_PATH/input_files/number_of_kindergartens_by_region.csv --pv_map=$SCRIPT_PATH/number_of_kindergartens_by_region_pvmap.csv --config_file=$SCRIPT_PATH/mongolia_metadata.csv --output_path=$SCRIPT_PATH/output_files/number_of_kindergartens_by_region_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf || { echo "Error: Processing number_of_kindergartens_by_region_pvmap.csv failed!"; exit 1; }

python3 $SCRIPT_PATH/../../../tools/statvar_importer/stat_var_processor.py --input_data=$SCRIPT_PATH/input_files/number_of_full_time_teachers_in_universities_and_colleges_by_sex.csv --pv_map=$SCRIPT_PATH/number_of_full_time_teachers_in_universities_and_colleges_by_sex_pvmap.csv --config_file=$SCRIPT_PATH/mongolia_metadata.csv --output_path=$SCRIPT_PATH/output_files/number_of_full_time_teachers_in_universities_and_colleges_by_sex_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf || { echo "Error: Processing number_of_full_time_teachers_in_universities_and_colleges_by_sex.csv failed!"; exit 1; }

python3 $SCRIPT_PATH/../../../tools/statvar_importer/stat_var_processor.py --input_data=$SCRIPT_PATH/input_files/graduates_of_universities_and_colleges_by_professional_field.csv --pv_map=$SCRIPT_PATH/graduates_of_universities_and_colleges_by_professional_field_pvmap.csv --config_file=$SCRIPT_PATH/mongolia_metadata.csv --output_path=$SCRIPT_PATH/output_files/graduates_of_universities_and_colleges_by_professional_field_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --places_resolved_csv=$SCRIPT_PATH/mongolia_place_resolver.csv || { echo "Error: Processing graduates_of_universities_and_colleges_by_professional_field.csv failed!"; exit 1; }

echo "All processing steps completed successfully."
exit 0