#!/bin/bash
#This script is generated from the manifest.json file.

python3 ../../../tools/statvar_importer/stat_var_processor.py --input_data=input_files/sagdp1__all_areas_1997_2024.csv --pv_map=pv_map/sagdp1__all_areas_1997_2024_pvmap.csv --config_file=pv_map/sagdp1__all_areas_1997_2024_metadata.csv --output_path=output_files/sagdp1_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --log_level=-2 --log_every_n=1000 --statvar_dcid_remap_csv=pv_map/sagdp1__all_areas_1997_2024_remap.csv --places_resolved_csv=pv_map/sagdp_places_resolved.csv
python3 ../../../tools/statvar_importer/stat_var_processor.py --input_data=input_files/sagdp2__all_areas_1997_2024.csv --pv_map=pv_map/sagdp2__all_areas_1997_2024_pvmap.csv --config_file=pv_map/sagdp2__all_areas_1997_2024_metadata.csv --output_path=output_files/sagdp2_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --log_level=-2 --log_every_n=1000 --statvar_dcid_remap_csv=pv_map/sagdp2__all_areas_1997_2024_remap.csv --places_resolved_csv=pv_map/sagdp_places_resolved.csv
python3 ../../../tools/statvar_importer/stat_var_processor.py --input_data=input_files/sagdp3__all_areas_1997_2024.csv --pv_map=pv_map/sagdp3__all_areas_1997_2024_pvmap.csv --config_file=pv_map/sagdp3__all_areas_1997_2024_metadata.csv --output_path=output_files/sagdp3_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --log_level=-2 --log_every_n=1000 --statvar_dcid_remap_csv=pv_map/sagdp3__all_areas_1997_2024_remap.csv --places_resolved_csv=pv_map/sagdp_places_resolved.csv
python3 ../../../tools/statvar_importer/stat_var_processor.py --input_data=input_files/sagdp4__all_areas_1997_2024.csv --pv_map=pv_map/sagdp4__all_areas_1997_2024_pvmap.csv --config_file=pv_map/sagdp4__all_areas_1997_2024_metadata.csv --output_path=output_files/sagdp4_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --log_level=-2 --log_every_n=1000 --statvar_dcid_remap_csv=pv_map/sagdp4__all_areas_1997_2024_remap.csv --places_resolved_csv=pv_map/sagdp_places_resolved.csv
python3 ../../../tools/statvar_importer/stat_var_processor.py --input_data=input_files/sagdp5__all_areas_1997_2024.csv --pv_map=pv_map/sagdp5__all_areas_1997_2024_pvmap.csv --config_file=pv_map/sagdp5__all_areas_1997_2024_metadata.csv --output_path=output_files/sagdp5_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --log_level=-2 --log_every_n=1000 --statvar_dcid_remap_csv=pv_map/sagdp5__all_areas_1997_2024_remap.csv --places_resolved_csv=pv_map/sagdp_places_resolved.csv
python3 ../../../tools/statvar_importer/stat_var_processor.py --input_data=input_files/sagdp6__all_areas_1997_2024.csv --pv_map=pv_map/sagdp6__all_areas_1997_2024_pvmap.csv --config_file=pv_map/sagdp6__all_areas_1997_2024_metadata.csv --output_path=output_files/sagdp6_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --log_level=-2 --log_every_n=1000 --statvar_dcid_remap_csv=pv_map/sagdp6__all_areas_1997_2024_remap.csv --places_resolved_csv=pv_map/sagdp_places_resolved.csv
python3 ../../../tools/statvar_importer/stat_var_processor.py --input_data=input_files/sagdp7__all_areas_1997_2024.csv --pv_map=pv_map/sagdp7__all_areas_1997_2024_pvmap.csv --config_file=pv_map/sagdp7__all_areas_1997_2024_metadata.csv --output_path=output_files/sagdp7_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --log_level=-2 --log_every_n=1000 --statvar_dcid_remap_csv=pv_map/sagdp7__all_areas_1997_2024_remap.csv --places_resolved_csv=pv_map/sagdp_places_resolved.csv
python3 ../../../tools/statvar_importer/stat_var_processor.py --input_data=input_files/sagdp8__all_areas_1997_2024.csv --pv_map=pv_map/sagdp8__all_areas_1997_2024_pvmap.csv --config_file=pv_map/sagdp8__all_areas_1997_2024_metadata.csv --output_path=output_files/sagdp8_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --log_level=-2 --log_every_n=1000 --statvar_dcid_remap_csv=pv_map/sagdp8__all_areas_1997_2024_remap.csv --places_resolved_csv=pv_map/sagdp_places_resolved.csv
python3 ../../../tools/statvar_importer/stat_var_processor.py --input_data=input_files/sagdp9__all_areas_1997_2024.csv --pv_map=pv_map/sagdp9__all_areas_1997_2024_pvmap.csv --config_file=pv_map/sagdp9__all_areas_1997_2024_metadata.csv --output_path=output_files/sagdp9_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --log_level=-2 --log_every_n=1000 --statvar_dcid_remap_csv=pv_map/sagdp9__all_areas_1997_2024_remap.csv --places_resolved_csv=pv_map/sagdp_places_resolved.csv
python3 ../../../tools/statvar_importer/stat_var_processor.py --input_data=input_files/sagdp11__all_areas_1998_2024.csv --pv_map=pv_map/sagdp11__all_areas_1997_2024_pvmap.csv --config_file=pv_map/sagdp11__all_areas_1997_2024_metadata.csv --output_path=output_files/sagdp11_output --existing_statvar_mcf=gs://unresolved_mcf/scripts/statvar/stat_vars.mcf --log_level=-2 --log_every_n=1000 --statvar_dcid_remap_csv=pv_map/sagdp11__all_areas_1997_2024_remap.csv --places_resolved_csv=pv_map/sagdp_places_resolved.csv
